owncloud/android

src/com/owncloud/android/db/DbHandler.java
This fixes a crash after downgrading the upload db (that is, when coming back from reliable_uploads to develop branch) and then uploading a file.
Without this patch upload succeeds but oc app crashes.
@davivel  This will make live easier when inspecting reliable_uploads branch. Please grant it priority. It is only 3 lines of code.
=> on downgrading upload db, delete and re-create

res/values/strings.xml, src/com/owncloud/android/operations/CreateShareOperation.java, src/com/owncloud/android/services/OperationsService.java
When the authentication is done via shibboleth, the subject of the email when sharing a file/folder by link  was "null shared X with you". 
Searching for a solution, I found that in the class OwnCloudSamlSsoCredentials we have this method 
public String getUsername() {
// its unknown
return null;
}
And it is the reason why is null.
As if seen that it's unknown I decided to change the subject in shibboleth for "x has been shared with you". 
If it is not a good solution, decline the pr
=> change the subject when sharing in saml

res/layout-land/account_setup.xml, res/layout/account_setup.xml
As mentioned in #1160 there were some problems on the login screen, while the crash not being present on the 1.8 branch (but on my actual material branches, sorry for that). Two issues remained, being:
* refresh icon size on landscape
* hoping server status text
Both are fixed with this PR and my guess would be that they both were present in 1.7.2 but I haven't tested this. At least for the refresh icon I found an issue: #192
This PR is a UI change only, no code changes as in java, just xml fixes.
Before:
After:
=> Fix refresh click on login screen

src/com/owncloud/android/files/services/FileUploader.java
After a successful upload, the uploaded file is saved locally on the device but the media scan was not getting triggered.
This meant newly uploaded files were being stored on the users device but the files would not show up until a media rescan was issued (via restart etc..).
=> Trigger media scan after file upload

res/values/strings.xml, src/com/owncloud/android/files/FileOperationsHelper.java
This fixes the isse as described in #1182 
The solution is implemented across all versions. So from now on the app will always "just" display a Toast message when no app was found to open the file that has been clicked.
=> Fix for #1182 on Android 5

src/com/owncloud/android/ui/fragment/FileDetailFragment.java
Thumbnail is displayed instead of icon.
If small thumbnail on OCFileListFragment list view, go FileDetailFragment.
We can see bigger thumbnail. It's better.
=> Display thumbnail when file is image on FileDetailFragment

.travis.yml
Restrictions, but they should not affect us:
- Using sudo isn’t possible (right now)
- Databases don’t run off a memory disk
=> switch from legacy infrastructure to container

res/layout/ssl_untrusted_cert_layout.xml, res/values/strings.xml, src/com/owncloud/android/ui/adapter/X509CertificateViewAdapter.java
+ show SHA-256, SHA-1 and MD5 certificate fingerprint
instead of signature hex dump
when certificate is untrusted
+ show error string if one of the digest algorithms is not available
+ added check and error msg for certificate load problems
@AndyScherzinger @davivel pls. can you review my improved PR (I tested the code).
output example for an "untrusted" certificate:
output example for "null" certificate as suggested by @AndyScherzinger previously in https://github.com/owncloud/android/pull/1134#issuecomment-142615727 :
> Only thing but that is rather an optimization is that if your cert byte-Array is null you can quite passing it on to further methods and return since then you won't be able to print any.
(tested by changing the null test temporarily).
Let me know, if you want me to …
=> fix #1024 show cert fingerprints when adding new account w/ untrusted certificate

src/com/owncloud/android/authentication/AuthenticatorActivity.java
When copying the server URL from the browser windows, it is something like
`http://localhost/ownCloud/master/core/index.php/apps/files/`
This patch removes trailing `index.php` and other `/index.php/apps/*` parts for the user
I will make the same patch for the desktop client soon. It lowers the burden for the user a bit.
=> Strip away index.php/apps/files to allow copy pasting from the server

src/com/owncloud/android/ui/activity/LocalDirectorySelectorActivity.java, src/com/owncloud/android/ui/activity/UploadFilesActivity.java
This should also be cherry-picked after merging 'do not duplicate files' (#1168) and 'change storage' (#1293) to master
=> Remove radios for copy or move in while searching for target dir in migration wizard

src/com/owncloud/android/syncadapter/FileSyncAdapter.java
Sets a minimum time of three hours between automatic synchronizations. 
Should be enough to fix #1338.
=> #1338: Correctly use delayUntil property of SyncResult

issue_template.md
=> add question to test with official server

src/com/owncloud/android/ui/activity/FileActivity.java, src/com/owncloud/android/ui/activity/FileDisplayActivity.java, src/com/owncloud/android/ui/activity/FolderPickerActivity.java, src/com/owncloud/android/ui/activity/Uploader.java
Report about a change in the server certificate when I refresh the list of files so that I am aware of possible man-in-the-middle attacks
Related issues: 
- After a manually accepted certificate on an owncloud server is updated, the android app stops communicating with the server #609
=> Ssl changed certificate warning

src/com/owncloud/android/ui/dialog/SamlWebViewDialog.java
This is probably not required here and good practise as a further hardening.
Fixes https://github.com/owncloud/android/issues/1143
=> Disable file access from the web view

.travis.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties, oc_jb_workaround/build.gradle
The new Android Studio 2.0 uses gradle 2.10 and also comes with a new build tools version.
So this is a simple bump PR. Be aware that gradle it now quite picky, warning you about the apache http implementation quite heavily.
```
AGPBI: {"kind":"error","text":"warning: Ignoring InnerClasses attribute for an anonymous inner class","sources":[{}]}
AGPBI: {"kind":"error","text":"(org.apache.commons.httpclient.HttpMethodBase$1) that doesn\u0027t come with an","sources":[{}]}
AGPBI: {"kind":"error","text":"associated EnclosingMethod attribute. This class was probably produced by a","sources":[{}]}
AGPBI: {"kind":"error","text":"compiler that did not target the modern .class file format. The recommended","sources":[{}]}
AGPBI: {"kind":"error","text":"solution is to recompile the class from …
```
=> Android Studio 2.0 Upgrade (build tools 23.0.3 + gradle 2.10)

build.gradle, oc_jb_workaround/build.gradle
app issue ticket corresponding to the library ticket: https://github.com/owncloud/android-library/pull/120
as discussed with @davivel: https://github.com/owncloud/android/pull/1596#issuecomment-215044896
Difference to the android-lib PR is the extraction of the support lib version into a variable to make sure that all support libs referenced in the dependency always have the same version.
=> Gradle android plugin v2.1.0, consistent support lib version

src/com/owncloud/android/datamodel/FileDataStorageManager.java
replaces https://github.com/owncloud/android/pull/1028
if OCFile is null --> cannot delete ==> return false.
Note: if `removeDBData` and `removeLocalCopy` are false, nothing will be deleted, but function still returns `true`. This might be intended, though.
=> return false if remove failed

res/values/drawer_resources.xml, res/values/setup.xml, res/values/strings.xml, res/xml/preferences.xml, src/com/owncloud/android/ui/activity/FileActivity.java, src/com/owncloud/android/ui/activity/Preferences.java
As discussed in #1432 the Logs menu item from the drawer has been moved to the settings screen.
@jancborchardt I moved it to the "more" section instead of the "advanced" section - is this correct or should I move it to the "advanced section?
=> moved logs from drawer menu to the settings

README.md
Same as for iOS https://github.com/owncloud/ios/pull/636 – @tobiasKaminsky @AndyScherzinger @davivel please review. :)
@DeepDiver1975 can you also add https://play.google.com/store/apps/details?id=com.owncloud.android to the URL field of the repository? And change the description to:
> :iphone: Android app for ownCloud
=> make readme/repository more attractive for contributors

AndroidManifest.xml, res/layout/uploader_layout.xml, res/layout/uploader_list_item_layout.xml, res/values/strings.xml, src/com/owncloud/android/db/PreferenceManager.java, src/com/owncloud/android/ui/activity/FileDisplayActivity.java, src/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java, src/com/owncloud/android/ui/adapter/FileListListAdapter.java, src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java, src/com/owncloud/android/ui/adapter/UploaderAdapter.java, src/com/owncloud/android/utils/DisplayUtils.java
For the detailed discussion please see #1193, see attached the screenshots for both sortings from my local tests. Works fine switching the sorting in app and then launching the uploader screen via another app.
This branch is based on ``master``
Beware of certain "details":
* The buttons are still white since the primary action coloring is part of the ``material_buttons`` branch
* The list is styled according to @jancborchardt's latests wishes (background white, devider #eee), as it is done for all other lists on the ``material_buttons`` branch
* The add folder action is shown on the action bar which will be hidden in the future, as seen on the ``material_fab`` branch since with the introduction of the fab the general guideline has been to hide non-primary actions in the actionbar in the …
=> #1193 - optimizing the uploader layout & taking user configured sorting into account

AndroidManifest.xml, res/values-v19/bools.xml, res/values/setup.xml, src/com/owncloud/android/authentication/AccountUtils.java, src/com/owncloud/android/providers/DocumentsStorageProvider.java, src/com/owncloud/android/providers/cursors/FileCursor.java, src/com/owncloud/android/providers/cursors/RootCursor.java
--------- edited by @jabarros
TASKs:
----------
=> #296: Add documents provider

src/com/owncloud/android/authentication/AuthenticatorActivity.java, src/com/owncloud/android/files/BootupBroadcastReceiver.java, src/com/owncloud/android/files/FileOperationsHelper.java, src/com/owncloud/android/services/OperationsService.java, src/com/owncloud/android/ui/activity/ConflictsResolveActivity.java, src/com/owncloud/android/ui/activity/FileActivity.java, src/com/owncloud/android/ui/activity/FileDisplayActivity.java, src/com/owncloud/android/ui/activity/FolderPickerActivity.java, src/com/owncloud/android/ui/activity/ShareActivity.java
This will prevent crashing when running on a userdebug phone. Log#wtf
should only be used when the program can not go on because a critical
assertion fails. These all don't seem to meet that criteria.
Fixes #1603
=> Replace Log.wtf calls with Log.e

src/com/owncloud/android/media/MediaService.java
This PR replaces the #1292, "Internal music player does not stop playing when file is deleted"
____
=> Internal music player does not stop playing when file is deleted

res/values/strings.xml, src/com/owncloud/android/authentication/AuthenticatorActivity.java, src/com/owncloud/android/db/UploadResult.java, src/com/owncloud/android/files/services/FileDownloader.java, src/com/owncloud/android/files/services/FileUploader.java, src/com/owncloud/android/operations/DetectAuthenticationMethodOperation.java, src/com/owncloud/android/operations/OAuth2GetAccessToken.java, src/com/owncloud/android/operations/UpdateOCVersionOperation.java, src/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java, src/com/owncloud/android/ui/activity/ErrorsWhileCopyingHandlerActivity.java, src/com/owncloud/android/ui/activity/FileActivity.java, src/com/owncloud/android/ui/activity/FileDisplayActivity.java, src/com/owncloud/android/ui/activity/FolderPickerActivity.java, src/com/owncloud/android/ui/activity/LogHistoryActivity.java, src/com/owncloud/android/ui/activity/ManageSpaceActivity.java, src/com/owncloud/android/ui/activity/PassCodeActivity.java, src/com/owncloud/android/ui/activity/Preferences.java, src/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, src/com/owncloud/android/ui/activity/ShareActivity.java, src/com/owncloud/android/ui/activity/UploadListActivity.java, src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java, src/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java, src/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java, src/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java, src/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.java, src/com/owncloud/android/ui/fragment/OCFileListFragment.java, src/com/owncloud/android/ui/fragment/ShareFileFragment.java, src/com/owncloud/android/ui/helpers/FileOperationsHelper.java, src/com/owncloud/android/ui/preview/PreviewAudioFragment.java, test/java/com/owncloud/android/utils/ErrorMessageAdapterUnitTest.java
Fixes #966 
Requires https://github.com/owncloud/android-library/pull/146
To be more specific:
- when uploads fail due to an untrusted server certificate, a specific error is shown, both in the notification and in list of failed uploads (no more "Unkown error" for this situation";
- additionally, HTTP status phrase is saved in RemoteOperationResults to use as a fallback when ErrorMessageAdapter does not know a better user message for the result; this message will be used instead of the current "Unknown error" for HTTP error responses that are currently not translated to a localized error message in the app; 
- Toasts have been replaced with Snackbars where possible (Toasts created by Services or Activities finishing need to remain that way)
Not done:
- ask the user to accept untrusted …
=> Improve error feedback

.gitmodules
To prevent network problems in certain environments while cloning the repo.
Fixes #1943.
Read more in http://stackoverflow.com/questions/6631694/replace-git-submodule-protocol-from-git-to-http/6632693#6632693
=> Ref to submodule via https instead of ssh

res/layout/share_file_layout.xml, res/values/strings.xml, src/com/owncloud/android/datamodel/OCFile.java, src/com/owncloud/android/ui/activity/ShareActivity.java, src/com/owncloud/android/ui/adapter/SharePublicLinkListAdapter.java, src/com/owncloud/android/ui/fragment/ShareFileFragment.java, src/com/owncloud/android/ui/fragment/ShareFragmentListener.java, src/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Implements #1970 
~~Requires https://github.com/owncloud/android-library/pull/165~~
=> Private link

androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java, androidTest/java/com/owncloud/android/authentication/SAMLAuthenticatorActivityTest.java, androidTest/java/com/owncloud/android/utils/AccountsManager.java, build.gradle
Test cases to check the login view with SAML servers. Checked positive cases ftm.
SAML servers use a web view to validate credentials against an idP. For this reason, `WebEspresso` was added as a dependence for instrumented tests in gradle build file.
@davigonz @davivel
=> [Espresso] Add UI tests on login view with SAML auth

androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java, build.gradle
Lookup servers (with a dispatcher to several server instances) are now totally supported by the login suite with basic auth. Before, they were already supported, but the test case related with login in an already attached account (negative test). This test case will be skipped for lookup servers. It is not worthwhile to parameterize a test matrix [userX, instanceX] just to check an error message, also supported for other kind of servers.
@davivel @davigonz
=> [Espresso] Adapt login suite to lookup servers

build.gradle
With command ```./gradlew assembleBeta``` , before this PR the file generated is called ```android_null-beta.apk```; with this PR it becomes ```android_2.5.0-beta.1-beta.apk```
Last minute fix.
=> Show beta version in name of beta APK generated with gradle

src/com/owncloud/android/datamodel/FileDataStorageManager.java
Fix #1996 
Requires https://github.com/owncloud/android-library/pull/171
=> Save support_upload_only capability in DB properly

build.gradle, src/com/owncloud/android/MainApp.java, src/com/owncloud/android/ui/activity/LogHistoryActivity.java, src/com/owncloud/android/ui/activity/Preferences.java
Related to #1993 
When we designed the beta app, the beta buildType included debug mode to log different events in the app. 
Since FDroid doesn't allow to upload the app with debug mode and besides, it makes no sense because beta app needs to be signed to be published, I've enabled the logs in the beta buildType, so enabling debug is not longer needed to include logs in the beta app.
@jesmrec
=> Log enabled in beta

androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java, androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java, androidTest/java/com/owncloud/android/utils/AccountsManager.java, androidTest/java/com/owncloud/android/utils/FileManager.java, androidTest/java/com/owncloud/android/utils/ServerType.java
This suite covers:
- "Single" public link feature (oC < 10.0)
- Multiple public link feature (oC > 9.1)
- Test on options of public link, included "Show listing", available from 10.0.1
- Permalink
- Capability test & management (local changes)
- Separate file & folder tests (different features)
- Refactor: ServerType is now global (affects Authentication suite)
Parameters needed:
- Server URL
- Username
- Password
- ServerType
Ready to review @davivel @davigonz
=> [Espresso] Public Share Automatic test suite

androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
Right now, login view only shows URL field from scratch and not username and password. These changes have been developed in automatic tests to adapt new login view:
- Check username and password are hidden, as precondition
- Check status message after URL connection, by clicking on scroll and not in username field as before
=> Fix Espresso tests after UI changes in login view

.travis.yml, build.gradle, oc_jb_workaround/build.gradle
Dependencies to update:
- Update locally via SDK Manager and select version to use in build.gradle: `buildToolsVersion '26.0.2'`
- .travis.yml: `- build-tools-26.0.2`
- Update locally via SDK Manager to 26.0.1
- .travis.yml: `- platform-tools`
- Update locally via SDK Manager to 26.1.1
- .travis.yml: `- tools` and `yes | - sdkmanager --verbose tools` (not updating properly, travis first install tools 25.2.5 and replace it with 25.2.3 version) [WIP]
**Important info**, new command to use: https://developer.android.com/studio/command-line/sdkmanager.html
=> [WIP] Update Android tools and dependencies

res/values/strings.xml
According to the final design of new [Upload from camera](https://github.com/owncloud/android/issues/2027) feature, the name to be included in the bottom sheet should be "Picture from camera" instead of "Upload from camera" since the _upload_ word already appears in the bottom sheet title.
=> Use proper name for the Upload from camera feature

res/anim/dir_fadein_back.xml, res/anim/dir_fadein_front.xml, res/anim/dir_fadeout_back.xml, res/anim/dir_fadeout_front.xml, res/values/integers.xml, src/com/owncloud/android/ui/fragment/OCFileListFragment.java
This will introduce a (ugly) fix for the animation but that triggers an exception if the sub folder contains more folders.
=> fix exception during animation

androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
App has currently three modes:
- Debug
- Beta
- Release
currently, the welcome wizard is shown in all of them when the app is installed from scratch. To skip it, an automatic click on SKIP is performed in the first test, so only once per execution of the suite. After that, the check over the credential fields' visibility is moved to the first test as well.
The best approach would be to show the welcome wizard only in Release and Beta, and avoid it in Debug mode. Maybe this tweak can be faced in the next version.
=> Skip Welcome Wizard to let run the Espresso tests

src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java
This pr solves #2112 and merge the code included in #2115. It adds the feature to toggle visibility of password in public link share dialog.
______
=> Password toggle

src/com/owncloud/android/datamodel/FileDataStorageManager.java, src/com/owncloud/android/operations/SynchronizeFolderOperation.java
The will make the "available offline" flag keep being there even if the file got renamed remotely.
=> add fix for av offline flag gets removed when file gets renamed

gradle/wrapper/gradle-wrapper.properties, res/layout/share_public_dialog.xml, res/values/strings.xml, src/com/owncloud/android/ui/activity/FileActivity.java, src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java
Implements https://github.com/owncloud/android/issues/2066
____
=> make permission selection for link sharing a radio group

androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java
New public link options: https://github.com/owncloud/android/pull/2150
Espresso tests fixed to adapt this new UI. Included fix for the welcome wizard and removed unused code.
=> Adapt Espresso tests to new public link 

res/layout-land/activity_pattern_lock.xml, res/layout/activity_pattern_lock.xml, res/layout/fingerprint_dialog.xml, res/layout/generic_explanation.xml, res/layout/passcodelock.xml, res/layout/upload_files_layout.xml, res/layout/uploader_layout.xml, res/values/strings.xml, src/com/owncloud/android/authentication/AuthenticatorActivity.java, src/com/owncloud/android/ui/activity/FileActivity.java, src/com/owncloud/android/ui/activity/FileDisplayActivity.java, src/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, src/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java, src/com/owncloud/android/ui/dialog/CredentialsDialogFragment.java, src/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java, src/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.java
* Change `ownCloud Android app` to `ownCloud app for Android`
> "Android", or anything confusingly similar to "Android", cannot be used in names of applications or accessory products, including phones, tablets, TVs, speakers, headphones, watches, and other devices. Instead, use "for Android".
Incorrect: "Android MediaPlayer" or "Ndroid MediaPlayer"
Correct: "MediaPlayer for Android"
from https://developer.android.com/distribute/marketing-tools/brand-guidelines
* Capitalize `Version 1.2.3`
* Remove commented strings. If you need removed lines of code, git is
your friend ;)
* Remove quotation marks as they aren't shown if unescaped
* Change … to it's unicode representation
* Remove whitespace between … and the previous words
* Remove ellipses on buttons
>  Omit ellipses from menu items or …
=> String improvements

androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java, androidTest/java/com/owncloud/android/authentication/SAMLAuthenticatorActivityTest.java, androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java, androidTest/java/com/owncloud/android/utils/AccountsManager.java
Changes included:
- Login button is now hidden till the URL is accepted. So, changed `isEnabled()` to `isDisplayed()`
- Add `context` as parameter of `FileDataStorageManager`
- return empty object for `OCCapability` till it is mocked using new networking stuff
=> Fix Espresso tests to fit new login view

docs/modules/ROOT/pages/release_notes.adoc
This fixes https://github.com/owncloud/docs/issues/204.
=> Remove unrequired (and inaccessible) image links in the release notes

docs/modules/ROOT/pages/release_notes.adoc
For some reason, incorrect link syntax was used in the release notes. This PR corrects them.
#2298.
=> Fix release note links

androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
The PR: https://github.com/owncloud/android/issues/2302 hides the button till credentials are typed, so some tweaks to do in the tests:
- Visibility asserts of the button till credentials are typed
- Remove test about blank credentials. It is not useful anymore
- Add clicks to URL arrow to assure URL checking (extra)
=> Fix espresso tests after merging PR 2302

docs/README.md, docs/antora.yml, site.local.yml, site.yml
This PR allows the Android docs to be built independently of the other documentation; especially helpful for previewing local changes.
=> Add playbook

build.gradle
see https://developer.android.com/studio/releases/
=> Android Studio 3.3.1

CHANGELOG.md, owncloudApp/build.gradle
I forgot to include a couple of contributions and the versionCode was not the good one, since `21000100` should be used in the final 2.10.0 version. Can you review this quickly @jesmrec , @hosy, @abelgardep ?
=> Include missing contributions and use proper versionCode in 2.10 beta 1

.travis.yml
To figure out release problems earlier
In https://github.com/owncloud/android/pull/2402 I run into this https://github.com/owncloud/android/pull/2402/files#r254872669
That's why I recommend to build in `release` as well
=> deeper assemble test

.gitmodules, .travis.yml, owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java, owncloudApp/src/main/res/values/setup.xml
Implements:
- Include TLSv1.2 support and make it work on 19 devices: https://github.com/owncloud/android-library/issues/236
- Make brandable the option to click in commit hash: #2480
- Update Android dependencies to API 28 in Travis
Needs https://github.com/owncloud/android-library/pull/243
**IMPORTANT**: tag `oc-android-2.10.0_oem` in this branch
=> Release 2.10.0 oem

CONTRIBUTING.md
I think this is needed as part of the implicit contract with community.
=> Add code of conduct link to Contributing file

owncloudApp/src/main/java/com/owncloud/android/operations/RenameFileOperation.java
If/when an IOException occurs during a `FileRenameOperation`, the `result` variable is guaranteed to be `null`. I don't think there's any more information to send to the logger when this happens.
This issue was flagged up by LGTM.com: https://lgtm.com/projects/g/owncloud/android/alerts/
There are a few other alerts for this repository (including a few more potential NPEs and resource leaks), but I'm not familiar enough with the code base to assess whether these issues should be addressed (and if so, how).
It's possible to have LGTM perform automated code review for every pull request; here's an example how Google's AMPHTML open source project use that to catch potential security vulnerabilities: https://github.com/ampproject/amphtml/pull/13060
There are some more alerts on other ownCloud …
=> Avoid NPE in RenameFileOperation on IOException

owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
Fixes #2612 
QA
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.12.0/2613%20-%20trigger%20media%20scan.md
=> Fix trigger media scan

TROUBLESHOOTING.md
Implements #2554
Adding the troubleshooting doc, as in the other clients.
Document added to the root folder, since te `doc` and `docs` folders aims to the automatic documentation processes handled by antora.
Let me know any issue or improvement
=> Add troubleshooting doc

docs/yarn.lock
There are a number of vulnerabilities with the current versions of some of the dependencies. This change helps mitigate these problems. Thanks for reporting this in the documentation channel, @davigonz.
=> Update Antora/Documentation dependencies to the latest versions

owncloudApp/build.gradle
especially where I'm the last changed user and git blame points to me.
It's just noise
=> remove pointless comments

.drone.yml
This step has been shown to dramatically lengthen build times. As it's just an output of the generated content, it's not strictly necessary, so is being removed.
=> Remove the build-artifacts Drone step

owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPasscodeTest.kt
The UI test `secondTryIncorrect` in the passcode suite has been failing. 
The problem is that one of the assertions in the test check the error message in the snackbar when the second try does not match the first one. But, this happens when the softkeyboard is on the front, so the `isDisplayed()` assertion returns false.
This fix needs some elaboration to make the test pass, so, an `@Ignore` annotation is temporarily set, and new issue is created:  https://github.com/owncloud/android/issues/2722
@davigonz @abelgardep
=> Ignore "Second Try incorrect" test

owncloudApp/src/androidTest/java/com/owncloud/android/settings/camerauploads/OCSettingsCameraUploadsTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsLogTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsMoreTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPatternLockTest.kt
Issues: #2732 #2709
Some actions performed:
- Camera Uploads section:
For these tests, the whole preferences activity was loaded, taking advantage that the section is on the top (visible at a glance). Some tests were flaky because the activity takes a bit longer in loading, before the action over the camera uploads checkbox is done (this is something not desirable that the testing framework should take care). Therefore, the dialog warning users to set up correctly the camera uploads is not displayed, failing the matcher over the "OK" button.
As fix, the activity is only loaded with the camera uploads section. 
- LocalFolderPicker activity
Here, the fix is a bit hacky. An implicit wait till the UI componentes are visible to launch the tests. Although there is a loop, it will not be …
=> Adjustments in Settings UI tests to avoid flakyness

owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java, owncloudApp/src/main/java/com/owncloud/android/operations/CopyFileOperation.java, owncloudApp/src/main/java/com/owncloud/android/operations/MoveFileOperation.java, owncloudApp/src/main/java/com/owncloud/android/operations/UploadFileOperation.java, owncloudApp/src/main/java/com/owncloud/android/utils/RemoteFileUtils.kt
Fixes https://github.com/owncloud/android/issues/2623
QA
Test plan:
https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.14.0/2734-%20overwritten_files_copy.md
=> Fix overwritten files when copying and moving

owncloudApp/src/androidTest/java/com/owncloud/android/settings/camerauploads/OCSettingsLocalFolderPickerTest.kt
Ignore flaky tests to check a better way to implement. Those test check that an activity is finished after clicking a dismiss button, but the assertion is being checked before the activity is finally finished. The tests are not covering any important part of the app, so, if no better solution is found out, they will be removed.
@abelgardep @davigonz
=> Ignore flaky tests

owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/28.json
You changed with 348dcc0d35176a5956bfc201c83f03059ffd5eb4 for [2.14.1](https://github.com/owncloud/android/releases/tag/oc-android-2.14.1) the database structure by removing from 
`@ColumnInfo(name = CAPABILITIES_SHARING_PUBLIC_EXPIRE_DATE_DAYS, defaultValue = "0")` the `defaultValue`.
As follow up, room changed the database structure and **this changed file was ignored.** -sad-
Because ownCloud use `exportSchema = true` room is now no more able to open the database -sad-
The tests were fine, because I guess, you do only `InMemory` database tests. But I didn't checked this.
I don't use the GooglePlaystore and I don't know if you already rolled out this version. If you did it, I would not surprised about a disaster. But I don't know, so please double check this.
This pull request is to …
=> update Room schema 28

.github/ISSUE_TEMPLATE/release_template.md
add the missing line to the template, in order not to forget uploading the APK
=> Add new task to release template: upload APK to internal instance

owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java, owncloudApp/src/main/java/com/owncloud/android/services/SyncFolderHandler.java, owncloudApp/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java, owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java, owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FilesUploadHelper.java, owncloudApp/src/main/res/layout/list_fragment.xml
These are just code format lines and some minor lint issues. I opened this as an additional pull request to keep https://github.com/owncloud/android/pull/2776 small.
Normally it should bot be a big deal to accept them.
=> code format and minor lint issues

CHANGELOG.md, owncloudApp/build.gradle, owncloudApp/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java, owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java, owncloudApp/src/main/java/com/owncloud/android/services/SyncFolderHandler.java
=> [Release] 2.14.2

.idea/codeStyles/Project.xml
Sorry, I accidentally added an old markup plugin setting.
This should be removed on a more recent version of the plugin
=> fix code style

README.md
Travis is not used as Android CI anymore. Instead, we are using BitRise, so the status badge should be replaced:
|Before | This | 
| :-: | :-: |
|![Screenshot 2020-06-10 at 16 34 49](https://user-images.githubusercontent.com/14894746/84284024-fd575280-ab3b-11ea-977e-4b17480dd48d.png)|![Screenshot 2020-06-10 at 16 57 59](https://user-images.githubusercontent.com/14894746/84284082-0d6f3200-ab3c-11ea-8fca-218e5d2c4bef.png)|
=> Replace Travis status CI for Bitrise

owncloudApp/src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java, owncloudApp/src/main/java/com/owncloud/android/authentication/oauth/OAuthUtils.kt, owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt, owncloudApp/src/main/java/com/owncloud/android/datamodel/OCFile.java, owncloudApp/src/main/java/com/owncloud/android/datamodel/OCUpload.java, owncloudApp/src/main/java/com/owncloud/android/db/PreferenceManager.java, owncloudApp/src/main/java/com/owncloud/android/files/services/IndexedForest.java, owncloudApp/src/main/java/com/owncloud/android/operations/CopyFileOperation.java, owncloudApp/src/main/java/com/owncloud/android/operations/MoveFileOperation.java, owncloudApp/src/main/java/com/owncloud/android/operations/RenameFileOperation.java, owncloudApp/src/main/java/com/owncloud/android/operations/UploadFileOperation.java, owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java, owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java, owncloudApp/src/main/java/com/owncloud/android/utils/DisplayUtils.java, owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
There is no need of an homemade `PATH_SEPARATOR = "/"` 
when there is in Android a `File.separator`
Library: https://github.com/owncloud/android-library/pull/329
=> Use Android separator instead of homemade one

owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Crash when browsing up reported to Google play console. 
Stacktrace:
```
java.lang.NullPointerException: 
at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory (OCFileListFragment.java:983)
at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$listDirectoryWidthAnimationUp$4$OCFileListFragment (OCFileListFragment.java:764)
at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$xZj3WyovpoK7b0u2-N-Y6ClHENE.run (Unknown Source:4)
at android.os.Handler.handleCallback (Handler.java:873)
at android.os.Handler.dispatchMessage (Handler.java:99)
at android.os.Looper.loop (Looper.java:214)
at android.app.ActivityThread.main (ActivityThread.java:6986)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run …
```
=> Fix npe when browsing up

owncloudApp/src/main/java/com/owncloud/android/files/services/TransferRequester.java
It may fix #2561 according to logs.
We have this log:
`Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{24fee0 u0 com.owncloud.android/.files.services.FileUploader}`
This code determines if it is needed to call startForegroundService.
`if ((isCameraUploadFile || isAvailableOfflineFile || isRequestedFromWifiBackEvent) &&
Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {`
In the retry function, we launch a foreground service but we send only `isRequestedFromWifiBackEvent`. If it is not, `startForegroundService` is not called in the FileUploader.
With this change, we will send how it was created, and if it was created by camera uploads, it will call `startForegroundService`
=> Potential fix to anr related with camera uploads retries

owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
This will resolve cookie persistence which should solve braking the cookiejar after restarting the app.
Related app PR: https://github.com/owncloud/android-library/pull/354
=> Remove cookie persistence

owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt
Implements #3003 
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.16/3007-share_link_list_extended.md
=> Align shared by link behaviour with other platforms

owncloudApp/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
Steps to reproduce this crash:
- Share an external file with ownCloud
- In the picker, click on create a new folder
- Rotate the device when create folder dialog appears
=> Fix crash when rotating create folder dialog

owncloudApp/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java, owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java, owncloudApp/src/main/java/com/owncloud/android/ui/adapter/FileListListAdapter.java
Implements #2926 and #2927 
____
=> Use public preview api to retrieve thumbnails

owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
Fixes #3021 
Visual bug. Image is updated properly after a remote change, but cached one was shown in the app.
=> Refresh image preview after remote change

owncloudApp/build.gradle, owncloudApp/src/main/AndroidManifest.xml, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt, owncloudApp/src/main/res/values/setup.xml, owncloudData/build.gradle
Implements #2883 
Needs https://github.com/owncloud/android-library/pull/358
Requires some changes in oB
Old string: 
`"oauth2_redirect_uri" -> oc://android.owncloud.com`
New strings:
`"oauth2_redirect_uri_scheme" -> oc`
`"oauth2_redirect_uri_path" -> android.owncloud.com`
=> Redirection callback from oauth2 brandable

owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
Added `return` after `finish()` as discussed in #2895 to fix the crash.
Fixes #2895
=> Fix crash when Back pressed in root directory

owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt, owncloudApp/src/main/java/com/owncloud/android/datamodel/OCFile.java, owncloudApp/src/main/java/com/owncloud/android/operations/CreateFolderOperation.java, owncloudApp/src/main/java/com/owncloud/android/operations/UploadFileOperation.java, owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt, owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java, owncloudApp/src/main/java/com/owncloud/android/utils/MimetypeIconUtil.java, owncloudDomain/src/main/java/com/owncloud/android/domain/files/MimeTypeConstants.kt
Fixes a problem where file size was 0 in ocis due to hardcoded mimetypes.
Could fix a problem when removing a folder in ocis.
Needs: https://github.com/owncloud/android-library/pull/362
oc10 -> "DIR"
ocis -> "httpd/unix-directory"
=> Use constants instead of hardcoded values for dir mimetypes

owncloudApp/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
=> Improve thumbnails

.github/dependabot.yml, build.gradle
It is enough with the `dependencies` label. We don't need the `java` one.
BTW, update library reference.
=> Update dependabot labels

owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Fix #3055 
Do not finish the activity till files are copied to temp dir. That way we won't get the security exception and files will be copied to a temp folder and then uploaded to the server.
=> Fix sharing with ownCloud

owncloudApp/src/main/res/values/dims.xml
Fix a glitch introduced here: https://github.com/owncloud/android/pull/3087#issuecomment-784140145
Custom avatar is displayed fine, but default avatar is not as big as expected.
| Current | Expected |
| ---------------------------------------------- | -------------------------------------------- |
| ![avatar_size_small](https://user-images.githubusercontent.com/47524927/109943948-fbd74700-7cd5-11eb-8fee-de245f755dd7.png) | ![avatar_normal](https://user-images.githubusercontent.com/47524927/109943917-f8dc5680-7cd5-11eb-9ab6-a9731bbf823a.png) |
=> Increase a little bit default avatar size in toolbar

owncloudApp/build.gradle, owncloudApp/src/main/java/com/owncloud/android/ui/preview/CustomHttpDataSourceFactory.java, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFragment.java, owncloudApp/src/main/res/layout/custom_playback_control.xml, owncloudApp/src/main/res/layout/video_preview.xml
Bump Exoplayer to version 2.13.1
=> bump exoplayer to version 2.13.2

README.md
This will update the url of the fdroid badge icon in the README.md. The old url was broken.
=> update fdroid badge url

README.md
After moving CI workflows to public ones, badges ir README must be updated.
** stable is empty because no jobs were executed over that branch yet. In the moment they are, the badge will be displayed there
=> Show new CI badges on README file

CHANGELOG.md, changelog/unreleased/3121, changelog/unreleased/3177, changelog/unreleased/3184
`We've`  ->  passive.
From my pov, changelog describes new stuff, no matter who did it.
=> Replace first person compositions for passive in calens descriptions

CHANGELOG.md, changelog/unreleased/3202, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/authentication/oauth/model/OIDCServerConfiguration.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/oauth/ClientRegistrationRequest.kt
`registration_endpoint` is mandatory at the moment but it should not according to https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata
It should fix a problem that happens when `registration_endpoint` is not retrieved in the discovery.
Library PR (if needed): https://github.com/owncloud/android-library/pull/392
_____
=> Make some fields not mandatory in discovery response

changelog/unreleased/3221, owncloudApp/src/main/java/com/owncloud/android/ui/activity/PatternLockActivity.java, owncloudApp/src/main/res/layout-land/activity_pattern_lock.xml, owncloudApp/src/main/res/layout/activity_pattern_lock.xml
App: https://github.com/owncloud/android/issues/3215
_____
QA checks: https://github.com/owncloud/android/pull/3221#issuecomment-831732883
Reports:
=> [Feature] Error handling for pattern lock

CHANGELOG.md, changelog/unreleased/3218, owncloudApp/src/androidTest/java/com/owncloud/android/authentication/LoginActivityTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/settings/SettingsFragmentTest.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsLogsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/providers/OCContextProvider.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/utils/PermissionUtil.java, owncloudApp/src/main/res/layout-land/account_setup.xml, owncloudApp/src/main/res/layout/account_setup.xml, owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsViewModelTest.kt
App: https://github.com/owncloud/android/issues/2638
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.18/3218-Settings_login.md
Reports:
=> [Feature] Settings accessible even when no account is attached

CHANGELOG.md, changelog/unreleased/3230, owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/SettingsSecurityFragmentTest.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsSecurityFragment.kt, owncloudApp/src/main/res/values-ar/strings.xml, owncloudApp/src/main/res/values-bg-rBG/strings.xml, owncloudApp/src/main/res/values-ca/strings.xml, owncloudApp/src/main/res/values-cs-rCZ/strings.xml, owncloudApp/src/main/res/values-de-rCH/strings.xml, owncloudApp/src/main/res/values-de-rDE/strings.xml, owncloudApp/src/main/res/values-de/strings.xml, owncloudApp/src/main/res/values-en-rGB/strings.xml, owncloudApp/src/main/res/values-es-rAR/strings.xml, owncloudApp/src/main/res/values-es-rMX/strings.xml, owncloudApp/src/main/res/values-es/strings.xml, owncloudApp/src/main/res/values-eu/strings.xml, owncloudApp/src/main/res/values-gl/strings.xml, owncloudApp/src/main/res/values-he/strings.xml, owncloudApp/src/main/res/values-id/strings.xml, owncloudApp/src/main/res/values-it/strings.xml, owncloudApp/src/main/res/values-nb-rNO/strings.xml, owncloudApp/src/main/res/values-nl/strings.xml, owncloudApp/src/main/res/values-pl/strings.xml, owncloudApp/src/main/res/values-pt-rBR/strings.xml, owncloudApp/src/main/res/values-ru/strings.xml, owncloudApp/src/main/res/values-sq/strings.xml, owncloudApp/src/main/res/values-th-rTH/strings.xml, owncloudApp/src/main/res/values-tr/strings.xml, owncloudApp/src/main/res/values-zh-rTW/strings.xml, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/android/issues/3217
_____
QA checks: https://github.com/owncloud/android/pull/3230#issuecomment-838242849
=> [Feature] Hide biometrical if device does not support it

CHANGELOG.md, changelog/unreleased/3234, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/PublicShareDialogFragment.kt
Capabilities were observed just one time, and when rotating the device, they were not taken into account to show the options.
App: https://github.com/owncloud/android/issues/3204
_____
Checks: https://github.com/owncloud/android/pull/3234#issuecomment-842134199
=> Fix rotation when sharing a file

changelog/unreleased/3297, owncloudApp/src/main/res/drawable/ic_place_holder_music_cover_art.xml
App: #3272 
Let's use the same color as the toolbar, I think it is the more consistent way.
_____
=> Update the music icon with the branded toolbar color

.idea/codeStyles/Project.xml, owncloudApp/src/main/res/drawable/round_button.xml, owncloudApp/src/main/res/layout-sw600dp/whats_new_activity.xml, owncloudApp/src/main/res/layout/whats_new_activity.xml
App:  #3351
Changed the previous oval shape to what it was intended to be, a Circular round button on the What's New Activity Screen after it reaches the final screen.
Attached screenshot below.
_____
=> [FIX] Oval Shape button to a Circle in the What's New screen section

CHANGELOG.md, changelog/unreleased/3381, owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
=> [Fix] Account removed from "Settings" is not removed from the drawer

CHANGELOG.md, changelog/unreleased/3380, changelog/unreleased/3381, owncloudApp/src/main/java/com/owncloud/android/MainApp.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/drawer/DrawerViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
=> [FIX] App leads to ANR after removing account if there were too many downloaded files

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsPictureUploadsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsVideoUploadsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsPictureUploadsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsVideoUploadsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java, owncloudData/src/main/java/com/owncloud/android/data/storage/LocalStorageProvider.kt
Clean some old code related to camera uploads.
This code was used previously to select the default camera folder but it is not working anymore after moving to the native way.
_____
=> Remove old way to retrieve the default camera folder path

CHANGELOG.md, changelog/unreleased/3418, owncloudApp/src/main/java/com/owncloud/android/files/services/TransferRequester.java, owncloudApp/src/main/java/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java, owncloudApp/src/main/java/com/owncloud/android/usecases/RetryUploadFromContentUriUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/workers/CameraUploadsWorker.kt
App: https://github.com/owncloud/android/issues/3417
_____
=> [Fix] Camera Uploads manual retry

CHANGELOG.md, changelog/unreleased/3431, owncloudApp/src/main/AndroidManifest.xml
=> [FIX] Device rotation moves to root in folder picker

owncloudApp/src/main/res/layout/fragment_migration_completed.xml, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/android/issues/3325#issuecomment-960656573
_____
=> [FIX] Scoped Storage Wizard Text 

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/extensions/ImageViewExt.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/diffutils/FileListDiffCallback.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt, owncloudApp/src/main/res/layout/main_file_list_fragment.xml
=> Simple list have been created.

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/UIResult.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt, owncloudApp/src/main/res/layout/main_file_list_fragment.xml
=> New arch/footer and other changes

CHANGELOG.md, changelog/unreleased/3434, owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/SettingsSecurityFragmentTest.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt, owncloudApp/src/main/java/com/owncloud/android/interfaces/ISecurityEnforced.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PatternActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsSecurityFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/res/values/setup.xml, owncloudApp/src/main/res/values/strings.xml, owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModelTest.kt
App: #3400
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.20/3434-security_enforced.md
Reports:
=> [FEATURE REQUEST] Security enforced

.github/ISSUE_TEMPLATE/release_template.md
Previously Android announcements were posted here:
https://central.owncloud.org/tags/c/news/5/android
=> Specify Category + Tag for Central post

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/extensions/SwipeRefreshExt.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/diffutils/FileListDiffCallback.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/utils/WrapContentLinearLayoutManager.kt, owncloudApp/src/main/res/layout/main_file_list_fragment.xml, owncloudDomain/src/main/java/com/owncloud/android/domain/files/model/OCFooterFile.kt
=> Swipe to Refresh

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt, owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetFilesAvailableOfflineUseCase.kt
=> New arch/shared files

CHANGELOG.md, changelog/unreleased/3438, owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt, owncloudApp/src/main/java/com/owncloud/android/operations/SyncProfileOperation.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/manager/AvatarManager.kt, owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/36.json, owncloudData/src/androidTest/java/com/owncloud/android/data/roommigrations/MigrationTest.kt, owncloudData/src/androidTest/java/com/owncloud/android/data/roommigrations/MigrationToDB36Test.kt, owncloudData/src/main/java/com/owncloud/android/data/OwncloudDatabase.kt, owncloudData/src/main/java/com/owncloud/android/data/ProviderMeta.java, owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/implementation/OCLocalCapabilitiesDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/mapper/RemoteCapabilityMapper.kt, owncloudData/src/main/java/com/owncloud/android/data/capabilities/db/OCCapabilityEntity.kt, owncloudData/src/main/java/com/owncloud/android/data/migrations/Migration_36.kt, owncloudData/src/test/java/com/owncloud/android/data/capabilities/db/OCCapabilityEntityTest.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/capabilities/model/OCCapability.kt, owncloudDomain/src/test/java/com/owncloud/android/domain/capabilities/model/OCCapabilityTest.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCCapability.kt
App: #3285 
Library: https://github.com/owncloud/android-library/pull/442
_____
QA checklist: https://github.com/owncloud/android/pull/3438#issuecomment-972898235
=> [FEATURE] Respect capability for Avatar support.

owncloudApp/src/androidTest/java/com/owncloud/android/datamodel/OCFileUnitTest.java, owncloudApp/src/androidTest/java/com/owncloud/android/files/SortBottomSheetFragmentTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/PassCodeActivityTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/PatternActivityTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/sharing/sharees/ui/SearchShareesFragmentTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/EditPrivateShareFragmentTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/PublicShareEditionDialogFragmentTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/ShareFileFragmentTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/ShareFolderFragmentTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/SharesContentProviderTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/TestShareFileActivity.kt, owncloudApp/src/androidTest/java/com/owncloud/android/utils/IntentsUtil.kt, owncloudApp/src/androidTest/java/com/owncloud/android/utils/matchers/CountViewMatchers.kt, owncloudApp/src/androidTest/java/com/owncloud/android/utils/matchers/MatcherExt.kt
The deprecations and warnings were removed from tests, so that they are cleaner and pass Lint.
This is part of the UI tests congress: https://confluence.owncloud.com/display/AT/2021-11-17+UI+tests+congress
=> [TESTS] Removed deprecations and warnings

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/res/layout/main_file_list_fragment.xml
=> Sort by name, size, and date

owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt
=> The images are displayed correctly in the list.

owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
=> Fixed Footer Bug

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
=> Filtering has been controlled on all screens

CHANGELOG.md, changelog/unreleased/3499, owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java, owncloudApp/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java, owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java, owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java, owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt, owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java, owncloudApp/src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java, owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
App: https://github.com/owncloud/android/issues/3475
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.20/3499-open_with_save.md
=> [FEATURE REQUEST] Open with action trigger an edit action

owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/SelectableAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
=> Selected items controlled and hide/show FAB button

owncloudApp/src/androidTest/java/com/owncloud/android/authentication/LoginActivityTest.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt, owncloudApp/src/main/res/layout-land/account_setup.xml, owncloudApp/src/main/res/layout/account_setup.xml
In branded builds, the check server button should be visible only when the connection is not established. Otherwise, it should be hidden. 
__
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.20/3523-hide_button_check.md
=> Update check server button visibility when connection fails

CONTRIBUTING.md
Code of conduct link in [CONTRIBUTING.md](https://github.com/owncloud/android/blob/master/CONTRIBUTING.md) was broken. Now it points to the new and correct URL.
=> Updated "code of conduct" link

.idea/codeStyles/Project.xml, CHANGELOG.md
Since we have upgraded to the [Android Studio Bumblebee](https://android-developers.googleblog.com/2022/01/android-studio-bumblebee-202111-stable.html) version this file has been modified by removing a line that seems to be no longer needed.
=> Project.xml updated

owncloudApp/src/debug/java/com/owncloud/android/utils/DebugInjector.kt
As we bump the SDK to Android 12, we have seen that it is important to control [unsafe intent launches](https://developer.android.com/about/versions/12/behavior-changes-12#unsafe-intent-launches) and [non-SDK restrictions](https://developer.android.com/about/versions/12/behavior-changes-12#non-sdk-restrictions).
By adding this restriction, the `log file` will show those bugs that exist or may arise from now on to see if they can be fixed.
For more info, please check: [Behavior changes: Apps targeting Android 12 ](https://developer.android.com/about/versions/12/behavior-changes-12#unsafe-intent-launches)
=> StrictMode added.

owncloudApp/src/main/java/com/owncloud/android/MainApp.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/providers/MdmProvider.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt, owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt, owncloudApp/src/main/res/values/strings__not_to_translate.xml, owncloudApp/src/main/res/xml/managed_configurations.xml, owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModelTest.kt
Added a new mdm configuration to allow/disallow lock delay via MDM.
_____
Checks: https://github.com/owncloud/android/pull/3595#issuecomment-1085833258
Reports:
=> [MDM] Lock delay configuration

owncloudApp/lint.xml
To unblock the CI problem regarding plurals in translations
=> Ignore plurals error in lint

check_code_script.sh
`verify_license_script.sh` is the wrong name for what the script does. This name implies that the license is checkt, where in fact more than this happens. Thus because of good coding we should go back to a more general description that could contain license verification as well as linting, or whatever is going to be added to in the future.
Therefore we should go back to `check_script`.
Library: https://github.com/owncloud/android-library/pull/479
=> rename verify_licnese_script back to check_script

owncloudApp/build.gradle, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsPictureUploadsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsVideoUploadsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsPictureUploadsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsVideoUploadsViewModel.kt
POC to start using StateFlow instead of LiveData. Several benefits including null safety.
`repeatOnLifecycle` API available since lifecycle-runtime-ktx 2.4.0, so we need to merge #3512 first
_____
=> Replace livedata with stateflow in camera uploads screens

owncloudApp/src/main/java/com/owncloud/android/extensions/DialogExt.kt, owncloudApp/src/main/java/com/owncloud/android/extensions/FragmentExt.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsSecurityFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/PublicShareDialogFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/ConfirmationDialogFragment.java, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/ExpirationDatePickerDialogFragment.java, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/LoadingDialog.java, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RateMeDialog.java, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RemoveAccountDialogFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.java, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RemoveShareDialogFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/ShareLinkToDialog.java, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.java, owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
=> [FEATURE] Prevent taking screenshots in Dialogs (Android 12)

owncloudApp/src/main/AndroidManifest.xml
Remove "install" permission from Manifest due to new Google policy
App: https://github.com/owncloud/android/issues/3648
_____
=> Remove "install" permission

CHANGELOG.md, changelog/unreleased/3659, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java, owncloudApp/src/main/res/menu/main_menu.xml
App: #1441
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.21/3659-Share%20folder%20from%20inside.md
=> share a folder from inside the folder

CHANGELOG.md, changelog/unreleased/3696, owncloudApp/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
Fix a crash when opening a file that was not downloaded from the details view
1. Select a file
2. Open the details view without downloading it
3. Select open with
```
java.lang.NullPointerException: 
at com.owncloud.android.ui.helpers.FileOperationsHelper.getIntentForGuessedMimeType (FileOperationsHelper.java:78)
at com.owncloud.android.ui.helpers.FileOperationsHelper.openFile (FileOperationsHelper.java:94)
at com.owncloud.android.ui.fragment.FileDetailFragment.onOptionsItemSelected (FileDetailFragment.java:284)
```
_____
=> Fix crash when opening a non downloaded file from Details view

owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Condition added to share oC external storage files, f.e. logs, but not needed anymore. With scoped storage, we don't own any file in that directory anymore. Introduced: https://github.com/owncloud/android/commit/073c8e8173e122a373ab0af6be310e7a9375a88d
_____
=> Remove legacy condition to share oC external storage files 

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/transfers/TransfersViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
App: https://github.com/owncloud/android/issues/3721
_____
=> [FIX] [New arch] Crash when removing account

owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt, owncloudApp/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/extensions/FragmentExt.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/diffutils/FileListDiffCallback.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortOptionsView.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortType.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/activity/UploadPathActivity.java, owncloudApp/src/main/res/layout/item_file_list.xml, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt, owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt, owncloudDomain/build.gradle, owncloudDomain/src/main/java/com/owncloud/android/domain/availableoffline/usecases/GetFilesAvailableOfflineFromAccountAsStreamUseCase.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/DisableThumbnailsForFileUseCase.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetFolderContentAsStreamUseCase.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetSharedByLinkForAccountAsStreamUseCase.kt, owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/GetSharedByLinkForAccountAsStreamUseCaseTest.kt
Replace LiveData with Flow/StateFlow and retrieve directly the filtered data from the database.
The final state for the screen is generated by combining 4 other states: FileListOption, AccountName, FolderDisplayed, SortTypeAndOrder, and SearchFilter. This way, the bottom navigation shortcuts should be fixed and more could be added in the future.
Adding StateFlow also removes some nullability checks we had when retrieving the value from the LiveData.
It should fix also this issue #3666 [FIXED]
Includes support for hidden files (It was pending): https://github.com/owncloud/android/issues/2818#issuecomment-1155087211 [DONE]
Potential fix to thumbnails generation [FIXED]
Grid/List configuration from the previous version will be reset
Glitch: Search, navigate to a folder and browse back shows …
=> [New arch] Fix bottom navigation shortcuts

owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/ShareFileFragmentTest.kt, owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/ShareFileFragment.kt, owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/37.json, owncloudData/src/main/java/com/owncloud/android/data/ProviderMeta.java, owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/implementation/OCLocalCapabilitiesDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/mapper/RemoteCapabilityMapper.kt, owncloudData/src/main/java/com/owncloud/android/data/capabilities/db/OCCapabilityEntity.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/capabilities/model/OCCapability.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCCapability.kt
App: https://github.com/owncloud/android/issues/3732
Library PR (if needed): https://github.com/owncloud/android-library/pull/505
_____
=> [Feature] Respect private link capability

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/res/layout/main_file_list_fragment.xml
- [Vertical scrollbar in file list](https://github.com/owncloud/android/issues/2818#issuecomment-1155087211)  (6) -> 55a6505251bfc85043afa2d6fe260a41b2d2c112 [FIXED]
- [Error message when refreshing with no connection](https://github.com/owncloud/android/issues/2818#issuecomment-1176105909) (5) -> 4fab544fb0730d97052c9849b10dd6aa49a5d860 [FIXED]
- [Set as available offline didn't trigger a synchronization till manual refresh](https://github.com/owncloud/android/issues/2818#issuecomment-1198961987) (1) and (3) ->  (1)-> [FIXED]
- [Too many requests when syncing folder](https://github.com/owncloud/android/issues/2818#issuecomment-1176105909) (8) -> 0eb53b6cba380ab7fe5167febd9c7b0f262146ef Instead of 2Propfind+Get, now 1Propfind+Get. Pending further clarification
- [Refresh recursively after …
=> [New arch] Fixes for QA reports in synchronization

owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
Uses [ACTION_OPEN_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT) instead of [ACTION_GET_CONTENT](https://developer.android.com/reference/android/content/Intent#ACTION_GET_CONTENT) to open the file picker from the floating action button.
It should retain the access for enough time so we have time to upload the file.
Should fix some reports we have in #2818 where we lose access to the file
_____
=> [New Arch] Uploads open document

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/details/FileDetailsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/operations/FileOperation.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/SettingsActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt, owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt, owncloudData/src/test/java/com/owncloud/android/data/file/repository/OCFileRepositoryTest.kt
Fixes some issues regarding available offline: https://github.com/owncloud/android/issues/2818#issuecomment-1198961987
_____
=> [New arch] Available offline fixes

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/CancelUploadWithIdUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/ClearFailedTransfersUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/UploadFilesFromContentUriUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/UploadFilesFromSystemUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/workers/UploadFileFromContentUriWorker.kt, owncloudApp/src/main/java/com/owncloud/android/workers/UploadFileFromFileSystemWorker.kt, owncloudData/src/main/java/com/owncloud/android/data/storage/LocalStorageProvider.kt, owncloudData/src/main/java/com/owncloud/android/data/transfers/datasources/LocalTransferDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/transfers/datasources/implementation/OCLocalTransferDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/transfers/db/TransferDao.kt, owncloudData/src/main/java/com/owncloud/android/data/transfers/repository/OCTransferRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/transfers/TransferRepository.kt
When doing a manual content URI upload, now files are copied to local storage before uploading them.
Library PR: https://github.com/owncloud/android-library/pull/508
_____
=> [New arch] Chunking bugfixing

owncloudApp/src/main/AndroidManifest.xml
This reverts commit 2015ecaffd8f9326eca94564c30154fc8b0fbb68.
I made this in 2019 and I guess, it's now obsolete
=> Revert "remove a lint warning"

owncloudApp/src/main/AndroidManifest.xml
During a2854fae21ac14d00dcb78063ba680938cc8ec36 (Logging 2.0) the comment is now somehow in a misleading line
=> fix comment

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/synchronization/SynchronizeFileUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/workers/DownloadFileWorker.kt, owncloudApp/src/main/java/com/owncloud/android/workers/UploadFileFromFileSystemWorker.kt, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt, owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/CleanConflictUseCase.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/SaveConflictUseCase.kt
App: https://github.com/owncloud/android/issues/3005
It includes:
- Propagation of the conflict to the parent folders
- Fix in move and remove behaviour in conflicted files and folders
- New feature: when moving a file in conflict, now the conflict is automatically propagated to the parents in the destination. Previously, it was needed to navigate to the file location for the conflict to propagate.
- [TO DISCUSS] Fix to conflicts QA report (1) (https://github.com/owncloud/android/pull/3762#issuecomment-1265085401) -> Current behaviour is consistent, so it won't be changed
It is expected to fulfill all the requirements stated for conflicts in 3.0: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_3.0/Conflicts.md
_____
Test plan: …
=> [New arch] Advanced conflicts management

owncloudData/src/test/java/com/owncloud/android/data/shares/datasources/OCRemoteShareDataSourceTest.kt
App: https://github.com/owncloud/android/issues/3824
Library PR (if needed): https://github.com/owncloud/android-library/pull/523
There is no need to parse the response anymore. The app is not using that data, just checks if it was successful or not.
oC10 returned an empty list
oCIS returns an object
That's why it was not working properly on oCIS accounts
_____
=> Fix error when unsharing but network request was successfully done

CHANGELOG.md, changelog/unreleased/3837, owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt, owncloudApp/src/main/res/values/strings.xml
The app crashes if it's updated from a DB version previous to 34 to the latest one. This PR should fix that
_____
=> [FIX] Database upgrade to 3.0 app version

CHANGELOG.md, changelog/unreleased/3841, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/res/values/strings.xml, owncloudData/src/main/java/com/owncloud/android/data/transfers/datasources/implementation/OCLocalTransferDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/transfers/db/OCTransferEntity.kt
Old uploads with FORGET behaviour weren't taken into account when migrating to the new database. Now, they are.
How to reproduce the crash:
1. Install 2.21.2
2. Share a text with oC
3. Remove device connection so upload does not complete
4. Migrate to 3.0
5. Open transfers view (crash here)
_____
=> [FIX] Migrate old uploads with FORGET behaviour

CHANGELOG.md, changelog/unreleased/3852, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
App: https://github.com/owncloud/android/issues/3820
_____
=> [FIX] Error message too long in copy operation

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/accounts/RemoveAccountUseCase.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/LocalSpacesDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/implementation/OCLocalSpacesDataSource.kt
Spaces are now deleted from database when the account they are attached to is removed from the app.
_____
=> [SPACES] Remove attached spaces when removing account

.github/workflows/calens.yml, .github/workflows/gradle-wrapper-validation.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/DocumentsStorageProvider.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/cursors/FileCursor.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/cursors/RootCursor.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/cursors/SpaceCursor.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/LocalSpacesDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/implementation/OCLocalSpacesDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/db/SpacesDao.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/db/SpacesEntity.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/repository/OCSpacesRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/usecases/GetPersonalAndProjectSpacesForAccountUseCase.kt
App: https://github.com/owncloud/android/issues/3809
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_4.0/Spaces%20Document%20Provider.md
Reports:
=> [SPACES] Document Provider showing available Spaces

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/RemoteDataSourceModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/providers/sharing/UsersAndGroupsSearchProvider.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/sharing/OCShareViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.kt, owncloudData/src/main/java/com/owncloud/android/data/ClientManager.kt, owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/implementation/OCRemoteCapabilitiesDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/oauth/datasource/impl/RemoteOAuthDataSourceImpl.kt, owncloudData/src/main/java/com/owncloud/android/data/sharing/sharees/datasources/RemoteShareeDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/sharing/sharees/datasources/implementation/OCRemoteShareeDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/sharing/sharees/repository/OCShareeRepository.kt, owncloudData/src/main/java/com/owncloud/android/data/sharing/shares/datasources/RemoteShareDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/sharing/shares/datasources/implementation/OCRemoteShareDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/sharing/shares/repository/OCShareRepository.kt, owncloudData/src/test/java/com/owncloud/android/data/capabilities/datasources/OCRemoteCapabilitiesDataSourceTest.kt, owncloudData/src/test/java/com/owncloud/android/data/sharees/datasources/OCRemoteShareesDataSourceTest.kt, owncloudData/src/test/java/com/owncloud/android/data/sharees/repository/OCShareeRepositoryTest.kt, owncloudData/src/test/java/com/owncloud/android/data/shares/datasources/OCRemoteShareDataSourceTest.kt, owncloudData/src/test/java/com/owncloud/android/data/shares/repository/OCShareRepositoryTest.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/sharees/GetShareesAsyncUseCase.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/sharees/ShareeRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/shares/ShareRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/shares/usecases/DeleteShareAsyncUseCase.kt, owncloudDomain/src/test/java/com/owncloud/android/domain/sharees/usecases/GetShareesAsyncUseCaseTest.kt, owncloudDomain/src/test/java/com/owncloud/android/domain/shares/usecases/DeleteShareAsyncUseCaseTest.kt
Previously, our source of clients was the SingleSessionManager and the client for the session was retrieved when opening the app/switching accounts. It caused some issues because sometimes to retrieve the client, a blocking function(to retrieve the credentials from the AccountManager) needs to be called. And it was done on the main thread when initializing the DI.
From now on, we will fetch the client on demand. So we don't need to reinitialize the DI each time we add/switch users. The most recent client will be cached on the [ClientManager](https://github.com/owncloud/android/blob/master/owncloudData/src/main/java/com/owncloud/android/data/ClientManager.kt) and we will retrieve that client on each RemoteDataSource (At this point, we are on a coroutine out of the main thread).
Potential …
=> [Technical] Remove remote client retrieval from DI

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/DocumentsStorageProvider.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java, owncloudApp/src/main/java/com/owncloud/android/ui/helpers/UriUploader.java, owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java, owncloudApp/src/main/java/com/owncloud/android/workers/DownloadFileWorker.kt, owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/40.json, owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/repository/OCSpacesRepository.kt, owncloudData/src/main/java/com/owncloud/android/data/storage/LocalStorageProvider.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetWebDavUrlForSpaceUseCase.kt
Implements https://github.com/owncloud/android/issues/3808
Library PR (if needed): https://github.com/owncloud/android-library/pull/537
_____
=> [Spaces] Local Storage

owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AccountUtils.java, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/DocumentsStorageProvider.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/cursors/RootCursor.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt, owncloudData/src/main/java/com/owncloud/android/data/authentication/AuthenticationConstants.kt, owncloudData/src/main/java/com/owncloud/android/data/authentication/datasources/implementation/OCLocalAuthenticationDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/authentication/repository/OCAuthenticationRepository.kt
Implements https://github.com/owncloud/android/issues/3906
_____
=> [SPACES] Spaces available only for fresh accounts

.github/workflows/calens.yml
Ubuntu 18.04 is deprecated and will be unsupported by 1st April 2023
https://github.com/actions/runner-images/issues/6002
=> Update GitHub actions runner to Ubuntu 22.04

owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
Group all features in 3.x releases for oem.
Contains `oc-android-3.0.3_oem` tag
=> Set release notes for oem version

owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/res/values/strings.xml, owncloudApp/src/main/res/values/strings__not_to_translate.xml
Since "space" is a brand term, it will be like that in every language. In this PR I only made the string "Spaces" non-translatable since the others strings contain more words which do are translatable, this will be solved at transifex level.
=> Make "Spaces" non-translatable

owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/DocumentsStorageProvider.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/cursors/SpaceCursor.kt
App: https://github.com/owncloud/android/issues/3881
_____
=> [SPACES] Support file and folders operations with Spaces in DocumentsProvider 

CHANGELOG.md, changelog/unreleased/3949, owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt, owncloudApp/src/main/res/layout-land/nav_drawer_footer.xml, owncloudApp/src/main/res/layout/nav_drawer_footer.xml, owncloudApp/src/main/res/values/setup.xml
App: https://github.com/owncloud/android/issues/3907
_____
=> [FEATURE REQUEST] Add link to drawer menu

owncloudApp/src/main/java/com/owncloud/android/extensions/OCTransferExt.kt, owncloudApp/src/main/java/com/owncloud/android/extensions/ThrowableExt.kt, owncloudApp/src/main/res/values/strings.xml, owncloudDomain/src/main/java/com/owncloud/android/domain/transfers/model/TransferResult.kt
Add a new message to the errors pool when uploading or doing any operation to a space where the user does not have permission.
Also, the `when` clause was sorted alphabetically
_____
=> Add specific forbidden exception to transfer errors pool

CHANGELOG.md, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AuthenticationViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt, owncloudApp/src/main/java/com/owncloud/android/providers/WorkManagerProvider.kt, owncloudApp/src/main/java/com/owncloud/android/workers/AccountDiscoveryWorker.kt, owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/authentication/AuthenticationViewModelTest.kt, owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt
After login, a worker will be launched, which will perform a discovery of the account (capabilities, spaces and root folders) in the background. This will help to fetch the root folders from the beginning and have all the data related to them (permissions, modification timestamp...), some of them necessary to show the proper UI.
_____
=> [FEATURE] Account discovery enhancement

CHANGELOG.md, changelog/unreleased/3982
App: https://github.com/owncloud/android/issues/3980
Library PR (if needed): https://github.com/owncloud/android-library/pull/551
_____
=> Add accept language header to all requests

owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/DocumentsStorageProvider.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/cursors/FileCursor.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/cursors/SpaceCursor.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/SortOptionsView.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, owncloudApp/src/main/res/layout/files_folder_picker.xml, owncloudApp/src/main/res/layout/uploader_layout.xml, owncloudApp/src/main/res/values/strings.xml, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/model/OCFile.kt
App: https://github.com/owncloud/android/issues/3890
In this PR we handle permissions related to folders (for oC10 as well). Specifically, we handle these cases:
- In the main file list, if we don't have `C` permission (add new files) in the current folder we hide the "Upload" mini FAB, if we don't have `K` permission (add new subdirectories) we hide the "New folder" mini FAB, and if we have none of them, we hide the main FAB as well
- In the documents provider, if we don't have the `C` permission in the current folder we hide the choose folder buttons (for copy and move), and if we don't have the `K` permission we disable the "New folder" option
- In the folder picker, if we don't have the `C` permission in the current folder we hide the choose folder button (for copy, move and sharing …
=> [SPACES] WebDAV permissions in folders

owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt, owncloudApp/src/main/java/com/owncloud/android/files/FileMenuFilter.java, owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFragment.java, owncloudApp/src/main/res/menu/file_actions_menu.xml, owncloudApp/src/main/res/values/strings.xml, owncloudDomain/src/main/java/com/owncloud/android/domain/files/model/OCFile.kt
App: https://github.com/owncloud/android/issues/3890
In this PR we handle permissions related to files (for oC10 as well). Specifically, we handle these cases:
- When a file doesn't have the `W` permission (write), we show "Open with (read only)" instead of "Open with", in the main file list with only the file selected, in the details view and in its preview. Also, this file cannot be modified by external apps since we send it without the write permission flag. NOTE: oC10 always sends `W` in the permissions although the file doesn't actually have it, so the error is handled in backend in this case (error message shown in the app)
- When a file or folder doesn't have the `R` permission (reshare), we hide the "Share" option in the main file list with only the file selected, in the details …
=> [SPACES] WebDAV permissions in files

owncloudApp/src/main/res/values/setup.xml
App: https://github.com/owncloud/android/issues/3984 
New default value for `prompt` is: `select_account consent` as [required](https://github.com/owncloud/android/issues/3769#issuecomment-1508453583)
_____
=> Add consent to default prompt value

CHANGELOG.md, changelog/unreleased/4026, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
App: https://github.com/owncloud/android/issues/3986
_____
=> [FIX] Incorrect list of av. offline files in shortcut when browsing from Details

.github/workflows/calens.yml, CHANGELOG.md, CONTRIBUTING.md
- Add prefix "technical" to calens.yml file
- Add instructions to use prefixs in [CONTRIBUTING](https://github.com/owncloud/android/blob/master/CONTRIBUTING.md) file
App:
_____
=> Add prefix "technical" to Calens 

CHANGELOG.md, changelog/unreleased/4023, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/extensions/ViewModelExt.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/common/BottomSheetFragmentItemView.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/operations/FileOperation.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/operations/FileOperationsViewModel.kt, owncloudApp/src/main/res/drawable/ic_action_create_file.xml, owncloudApp/src/main/res/layout/main_file_list_fragment.xml, owncloudApp/src/main/res/layout/newfile_bottom_sheet_fragment.xml, owncloudApp/src/main/res/values/strings.xml, owncloudData/src/main/java/com/owncloud/android/data/appregistry/OCAppRegistryRepository.kt, owncloudData/src/main/java/com/owncloud/android/data/appregistry/datasources/LocalAppRegistryDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/appregistry/datasources/RemoteAppRegistryDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/appregistry/datasources/implementation/OCLocalAppRegistryDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/appregistry/datasources/implementation/OCRemoteAppRegistryDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/appregistry/db/AppRegistryDao.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/appregistry/AppRegistryRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/appregistry/usecases/CreateFileWithAppProviderUseCase.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/appregistry/usecases/GetAppRegistryWhichAllowCreationAsStreamUseCase.kt
App: https://github.com/owncloud/android/issues/3995
Library PR (if needed): https://github.com/owncloud/android-library/pull/562
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_4.0/New%20Document%20-%20FAB.md
Reports:
=> [FEATURE REQUEST] Create new file via Open in Web

CHANGELOG.md, changelog/unreleased/4038, owncloudApp/src/main/AndroidManifest.xml
ShareActivity is not used outside of the app, so it's not needed to export it to external apps.
_____
=> [FIX] Make ShareActivity not-exported

CONTRIBUTING.md, README.md
Since we agreed to use gitflow as branching model, it's now mentioned in the CONTRIBUTING file in case we have to mention or point community to such method.
Also, removed BitRise badge of `stable` branch. `master` is more than enough
App:
_____
=> Add gitflow reference to contributing file.

CHANGELOG.md, changelog/unreleased/4058, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/extensions/FragmentExt.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListViewModel.kt
App: https://github.com/owncloud/android/issues/3860
_____
=> [FEATURE REQUEST] Create "Open in web" option in main file list

build.gradle, changelog/unreleased/4035, gradle/libs.versions.toml, owncloudApp/build.gradle, owncloudData/build.gradle, owncloudDomain/build.gradle, owncloudTestUtil/build.gradle, plugins/.gitignore, plugins/build.gradle.kts, plugins/settings.gradle.kts
Migrates current dependencies declaration to Gradle Version Catalog. More info about it can be found [here](https://developer.android.com/build/migrate-to-catalogs)
`Dependabot ` already supports this feature, so it should send PR to update the versions defined in the TOML file 🥇 
I created 2 bundles to illustrate its use, but feel free to create as many as u consider 👍 
```
espresso = ["androidx-test-espresso-contrib", "androidx-test-espresso-core", "androidx-test-espresso-intents", "androidx-test-espresso-web"]
markwon = ["markwon-core", "markwon-ext-tables", "markwon-ext-strikethrough", "markwon-ext-tasklist", "markwon-html"]
```
So we can add several dependencies that are related and are introduced all together like this:
`implementation libs.bundles.espresso`
_____
=> [Technical] Gradle Version Catalog

CHANGELOG.md, changelog/unreleased/4064, owncloudApp/src/debug/AndroidManifest.xml
I think a `tools:ignore` property in the Android manifest file specific for the debug flavour is not necessary anymore since it only prevents a warning to appear, and it doesn't happen anymore. Let's check if BitRise passes in this PR to confirm that.
_____
=> [TECHNICAL] Remove ignore from AndroidManifest in debug flavour

CHANGELOG.md, changelog/unreleased/4093, owncloudApp/src/main/java/com/owncloud/android/usecases/files/FilterFileMenuOptionsUseCase.kt
App: https://github.com/owncloud/android/issues/4077
_____
=> [FIX] Option to unset av. offline inside av. offline folder must not be visible

CHANGELOG.md, changelog/unreleased/4084, gradle/libs.versions.toml, owncloudApp/build.gradle, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/thumbnails/ThumbnailsRequester.kt, owncloudApp/src/main/res/drawable/ic_spaces_placeholder.xml, owncloudApp/src/main/res/layout/grid_item.xml, owncloudApp/src/main/res/layout/item_file_list.xml, owncloudApp/src/main/res/layout/space_header.xml, owncloudApp/src/main/res/layout/spaces_list_item.xml, owncloudData/src/main/java/com/owncloud/android/data/ClientManager.kt
App: #3959 
- Modified how images load in:
Spaces
Files list
_____
Reports and suggestions
=> [FIX] Spaces' thumbnails not loaded the first time

CHANGELOG.md, changelog/unreleased/4106, owncloudApp/src/androidTest/java/com/owncloud/android/authentication/LoginActivityTest.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt
App: https://github.com/owncloud/android/issues/4067
_____
=> [FEATURE REQUEST] Stop authentication flow after account removal if URL is fixed

CHANGELOG.md, changelog/unreleased/4110, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AuthenticationViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt, owncloudApp/src/main/res/values/setup.xml, owncloudApp/src/main/res/values/strings.xml, owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/authentication/AuthenticationViewModelTest.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/exceptions/SSLErrorException.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/server/usecases/GetServerInfoAsyncUseCase.kt, owncloudDomain/src/test/java/com/owncloud/android/domain/server/usecases/GetServerInfoAsyncUseCaseTest.kt
App: #4066  
_____
https://github.com/owncloud/android/pull/4110#issuecomment-1653444281
=> [FEATURE REQUEST] Prevent http traffic

CHANGELOG.md, changelog/unreleased/4113, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/RepositoryModule.kt, owncloudData/src/main/java/com/owncloud/android/data/appregistry/OCAppRegistryRepository.kt, owncloudData/src/main/java/com/owncloud/android/data/appregistry/datasources/RemoteAppRegistryDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/appregistry/datasources/implementation/OCRemoteAppRegistryDataSource.kt
App: https://github.com/owncloud/android/issues/4075
Library PR (if needed): https://github.com/owncloud/android-library/pull/577
_____
=> [FEATURE REQUEST] Respect app_provider values from capabilities

CHANGELOG.md, changelog/unreleased/4087, owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/security/SecurityUtils.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/settings/security/SettingsSecurityViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt, owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt, owncloudApp/src/main/res/values/setup.xml, owncloudApp/src/main/res/values/strings__not_to_translate.xml, owncloudApp/src/main/res/xml/managed_configurations.xml, owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModelTest.kt
App: https://github.com/owncloud/android/issues/4061
_____
https://github.com/owncloud/android/pull/4087#issuecomment-1630542386
=> [Feature request] Force security if not protected

.github/ISSUE_TEMPLATE/release_template.md
Some changes in release template:
- GitFlow makes us to merge first into `stable`, then into `master`
- Some tiny improvements
=> Modifications in release template

owncloudApp/src/main/res/values/strings.xml
Before: `Filename must not be more than %d characters`
Now: `Filename must not be longer than %d characters`
more is not the correct comparative for the length
No Calens added since this is just a one-line fix out of the logic.
=> Fix typo in lenght overflow error message

CHANGELOG.md, changelog/unreleased/4123, owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt, owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCRemoteFileDataSourceTest.kt
=> [TECHNICAL] Unit tests for datasources classes - Part 2

CHANGELOG.md, changelog/unreleased/4138, owncloudApp/src/main/java/com/owncloud/android/presentation/files/operations/FileOperationsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/dialog/FileAlreadyExistsDialog.kt, owncloudApp/src/main/res/layout/dialog_file_already_exists.xml, owncloudApp/src/main/res/values/strings.xml
App:
_____
Reports & improvements
=> [FEATURE REQUEST] "Apply to all" when many name conflicts arise

.github/ISSUE_TEMPLATE/release_template.md
- Add step to rebase the release branch with `stable` just after creation, in order to fast forward when it's approved.
- Add step to prepare post central (separate from publishing step)
- Add step to warn documentation team that tag is closed to be signed
- Add code review step
- Add step to wait for the release published in GP (steps below this one must wait till such event)
- Change `Bugs and improvements` section for `QA` to include more stuff beyond reports
=> More improvements in release checklist

CHANGELOG.md, changelog/unreleased/4160, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/ReceiveExternalFilesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/adapter/ReceiveExternalFilesAdapter.java, owncloudApp/src/main/res/layout/uploader_layout.xml, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/android/issues/4088
_____
Test Plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Executions/Release_4.2/Share%20with%20oC%20with%20spaces.md
=> [FEATURE REQUEST] OCIS: "Share to" allows only upload to personal "space"

CHANGELOG.md, changelog/unreleased/4170, owncloudApp/build.gradle, owncloudApp/src/androidTest/java/com/owncloud/android/utils/ReleaseNotesList.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListViewModel.kt, owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt
App: https://github.com/owncloud/android/issues/4158
_____
=> [FIX] NPEs in FileDetailsFragment (Play Store)

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/release_template.md, SETUP.md
`SETUP.md` file is intended for new contributors to get ready with the proper environment. After [removing the submodule](https://github.com/owncloud/android/pull/4183), some actions are no longer required:
- cloning repo with the `--recursive` option
- `git submodule update` command to get last reference.
Release branch no longer required in release template for library
Removed PR section at the end of the template
If any other file requires attention or changes, please ping or add by yourself.
=> Update some files after removing submodule

owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/PublicShareCreationDialogFragmentTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/ShareFileFragmentTest.kt, owncloudApp/src/main/res/values/strings.xml
Fixed various formal and some language issues I noticed while translating.
=> language review

.github/ISSUE_TEMPLATE/release_template.md, .github/pull_request_template.md
Some improvements in these templates due to the recent removal of `owncloud-library` repository, and better formatting and understanding in release steps
=> Improvements in PR and release templates

CHANGELOG.md, changelog/unreleased/4191, owncloudApp/src/main/AndroidManifest.xml, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AuthenticationViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/operations/FileOperationsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/res/values/setup.xml, owncloudApp/src/main/res/values/strings.xml, owncloudDomain/src/main/java/com/owncloud/android/domain/exceptions/DeepLinkException.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/ManageDeepLinkUseCase.kt
App: https://github.com/owncloud/android/issues/4181
_____
=> [FEATURE REQUEST] Manage deep links and open the app correctly 

CHANGELOG.md, changelog/unreleased/4199, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/res/layout/main_file_list_fragment.xml, owncloudApp/src/main/res/values/setup.xml, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/android/issues/4103
_____
Checklist:
https://github.com/owncloud/android/pull/4199#issuecomment-1784616876
Reports:
=> [FEATURE REQUEST] Auto-refresh when a file is uploaded

CHANGELOG.md, changelog/unreleased/4215, owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt, owncloudApp/src/main/java/com/owncloud/android/utils/UriUtils.java
App:https://github.com/owncloud/android/issues/4156
_____
=> Sharing Log Files seamlessly within the ownCloud Android App

CHANGELOG.md, changelog/unreleased/4257, owncloudApp/src/main/java/com/owncloud/android/MainApp.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/CommonModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/logging/LogsListActivity.kt, owncloudApp/src/main/java/com/owncloud/android/providers/LogsProvider.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt, owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt, owncloudApp/src/main/res/values/setup.xml, owncloudApp/src/main/res/values/strings__not_to_translate.xml, owncloudApp/src/main/res/xml/managed_configurations.xml, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/logging/LogInterceptor.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/OCFileLoggingTree.kt
App: https://github.com/owncloud/android/issues/4249
_____
=> [FEATURE REQUEST] Don't redact auth type HTTP request logging

CHANGELOG.md, changelog/unreleased/4241, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListViewModel.kt
App:https://github.com/owncloud/android/issues/4065
_____
=> [BUG] NPE related to MainFileListViewModel

CHANGELOG.md, changelog/unreleased/4260, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AccountAuthenticator.java, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/params/TokenRequestParams.kt, owncloudData/src/main/java/com/owncloud/android/data/oauth/datasources/implementation/OCRemoteOAuthDataSource.kt, owncloudData/src/test/java/com/owncloud/android/data/oauth/RemoteOAuthUtils.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/authentication/oauth/model/TokenRequest.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/oauth/TokenRequest.kt
=> [FIX] Add "scope" parameter to /token endpoint HTTP requests

owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/PublicShareCreationDialogFragmentTest.kt, owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/ShareFileFragmentTest.kt, owncloudApp/src/main/res/values/strings.xml, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/HttpBaseMethod.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/StatusRequester.kt
Some improvements in strings and retrieve body of HTTP responses with `peekBody()` instead of the `body` getter so that it is not closed after using `string()` over it
_____
=> [TECHNICAL] Retrieve body of HTTP requests with `peekBody()`

CHANGELOG.md, changelog/unreleased/4266, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/logging/LogBuilder.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/logging/LogInterceptor.kt
App: https://github.com/owncloud/android/issues/4258
_____
=> [FIX] Unify http log

owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt
The player will handle the audio focus shifts. Basically It would:
- Pause the already playing media when this player is started.
- Or If some other media starts this player would pause itself.
This would avoid two media's playing at the same time.
https://github.com/owncloud/android/assets/111801812/32cbe89d-71cb-4f25-97f3-8eafbd518029
> When a headset is unplugged or a Bluetooth device disconnected, the audio stream automatically reroutes to the built-in speaker. If you listen to music at a high volume, this can be a noisy surprise.
> 
> Users usually expect apps that include a music player with onscreen playback controls to pause playback in this case. Other apps, like games that don't include controls, should keep playing. The user can adjust the volume with the device's hardware …
=> Handle audio focus and becoming noisy

CHANGELOG.md, changelog/unreleased/4265, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt
App: https://github.com/owncloud/android/issues/4188
_____
Checks done: https://github.com/owncloud/android/pull/4265#issuecomment-1880888664
=> [FIX] Some bugs related to Details view

CHANGELOG.md, changelog/unreleased/4291, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/oauth/OAuthUtils.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt, owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt, owncloudApp/src/main/res/values/setup.xml, owncloudApp/src/main/res/values/strings__not_to_translate.xml, owncloudApp/src/main/res/xml/managed_configurations.xml, owncloudData/src/main/java/com/owncloud/android/data/authentication/AuthenticationConstants.kt
App: https://github.com/owncloud/android/issues/4288
_____
https://github.com/owncloud/android/pull/4291#issuecomment-1907946457
=> [FEATURE REQUEST] [OIDC] Branding option to remove `login_hint` and `user` parameter from re-login URL

CHANGELOG.md, changelog/unreleased/4287, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/GetRemoteAppRegistryOperation.kt
App: https://github.com/owncloud/android/issues/4279
_____
=> [BUG] 4.1.1 composes /app/list path wrong when instance is installed in subfolder (/owncloud)

CHANGELOG.md, changelog/unreleased/4294, changelog/unreleased/4295, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CopyRemoteFileOperation.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/CopyFileUseCase.kt
App: https://github.com/owncloud/android/issues/4222
_____
=> [BUG] Conflict in copy: File without extension

changelog/unreleased/4285, owncloudApp/src/main/java/com/owncloud/android/extensions/ThrowableExt.kt, owncloudApp/src/main/res/values/strings.xml, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java, owncloudData/src/main/java/com/owncloud/android/data/RemoteOperationHandler.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/exceptions/ResourceLockedException.kt
Fixes: #4282
What this PR includes?
- throwing exception when get HTTP 423 (resource locked)
- handling the exception by showing snackbar
https://github.com/owncloud/android/assets/111801812/5a395242-3125-4c7d-90b1-8fc38aaa17fa
@jesmrec The reason I believe this exception occurs is when file is being accessed, like in this case when the video is being fetched and we try to remove the file then it throws the exception.
=> Handle error 423 (locked file)

owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
App:https://github.com/owncloud/android/issues/4227
Everything related to cookies in the OperationsService.java class has been deleted because it is not used.
_____
=> Deleted cookies with no usage in OperationsService

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/release_template.md, CONTRIBUTING.md
Changes:
- In features template, new entry to add feature to release notes. So, it could be translated with more time in advance.
- In release template, new task to check if new screenshots are required to be generated before/during QA phase to be ready in deployment time.
- Add a new task to the release template: move the `latest` tag to the new release commit
- Replace GitFlow for OneFlow in `CONTRIBUTING.md` file
- Remove references to `stable` in release template
App:
_____
=> Modify GH templates

CHANGELOG.md, changelog/unreleased/4325, owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/AccountsManagementActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/AccountsManagementAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/workers/AccountDiscoveryWorker.kt, owncloudApp/src/main/res/layout/account_item.xml, owncloudApp/src/main/res/values/strings.xml
App:https://github.com/owncloud/android/issues/4301
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Executions/Release_4.3/Discovery.md
Some regards: https://github.com/owncloud/android/pull/4325#issuecomment-1982771824
=> [FEATURE REQUEST] Make automatic discovery of the account 

CHANGELOG.md, changelog/unreleased/4330, owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/AccountsManagementActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/AccountsManagementAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/res/layout/account_item.xml, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/android/issues/4148
_____
QA checks: https://github.com/owncloud/android/pull/4330#issuecomment-1987930235
Reports:
=> [FEATURE REQUEST] Improvements in "Manage accounts" view

CHANGELOG.md, changelog/unreleased/4339, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/android/issues/4311
_____
Checks done: https://github.com/owncloud/android/pull/4339#issuecomment-2003730072
=> [FIX] Lens icon in folder picker

.github/dependabot.yml, .github/workflows/calens.yml, CHANGELOG.md, changelog/unreleased/4346
More info: 
https://www.conventionalcommits.org/en/v1.0.0/#summary
Calens commits to add `docs: ` as prefix
Dependabot commits to add `feat: ` as prefix
App:
_____
=> Modify commit messages in calens and dependabot to fit "Conventional commits"

CHANGELOG.md, changelog/unreleased/4341, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/RetryUploadFromSystemUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/UploadFilesFromContentUriUseCase.kt, owncloudApp/src/main/res/values/strings.xml
App:https://github.com/owncloud/android/issues/4335
_____
Checks:
https://github.com/owncloud/android/pull/4341#issuecomment-2031220510
Test Matrix:
https://github.com/owncloud/android/pull/4341#issuecomment-2032537031
Reports:
=> [BUG] Retried successful uploads don't free space in /tmp folder

.github/dependabot.yml
Not required neither changelog nor release notes.
Just removing the scope from commit message in dependabot to make commit messages more consistent across all the repo.
_____
=> Remove scope from dependabot commits

changelog/unreleased/4351, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/res/layout/account_item.xml, owncloudApp/src/main/res/values/strings.xml
Resolved the bug where long display names were truncated incorrectly in the Manage Accounts view. Now, display names are properly truncated in the middle with ellipsis (...) to maintain readability.
Fixes #4351
App:
_____
=> [BUG] Fix display name truncation issue with ellipsis

CHANGELOG.md, changelog/unreleased/4354, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/res/values/strings.xml, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt, owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt, owncloudData/src/test/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSourceTest.kt, owncloudData/src/test/java/com/owncloud/android/data/files/repository/OCFileRepositoryTest.kt
App: https://github.com/owncloud/android/issues/4197
_____
Checks:
Reports:
=> Improve av. offline performance 

CHANGELOG.md, changelog/unreleased/3865, changelog/unreleased/4339, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, owncloudApp/src/main/res/values/strings.xml
=> [FEATURE REQUEST] Add search functionality to spaces list

owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt
App: https://github.com/owncloud/android/issues/4378
_____
=> [FIX] Multiselection mode enabled after removing an item

CHANGELOG.md, changelog/unreleased/4408, owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/synchronization/SynchronizeFileUseCase.kt, owncloudApp/src/main/res/values/strings.xml, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFileOperation.kt
When performing a read remote file operation (synchronization over a single file), if the account in the `OwncloudClient` is null, we'll throw an `AccountNotFoundException`. This will be handled in 3 different views:
- In the main file list view
- In the file details view
- In the image preview view
In the 3 cases, we'll show a Snackbar telling `Sync failed, you need to log in again`, suggesting that by repeating the login process, the problem can be solved (since we'll save again the account, which might have been lost in some migration process from a very old version).
Also, we changed the way to handle the 404 error of a `PROPFIND`. Previously, we deleted locally and remotely the file that we requested in the `PROPFIND`, now we just remove it locally (since if we receive a 404, the …
=> [FIX] Unwanted DELETE operations when synchronization in single file fails

owncloudApp/src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java, owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
App: https://github.com/owncloud/android/issues/4402
_____
=> [BUG] Av. offline operation does not work correctly when run from a parent folder

CHANGELOG.md, changelog/unreleased/4399, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/operations/FileOperation.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/operations/FileOperationsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/removefile/RemoveFilesDialogFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java, owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java, owncloudApp/src/main/java/com/owncloud/android/usecases/synchronization/SynchronizeFolderUseCase.kt, owncloudApp/src/main/res/values/strings.xml, owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt, owncloudData/src/main/java/com/owncloud/android/data/providers/LocalStorageProvider.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/AreAnyFileAvailableLocallyAndNotAvailableOfflineUseCase.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/IsAnyFileAvailableLocallyAndNotAvailableOfflineUseCase.kt
App:https://github.com/owncloud/android/issues/4353
_____
Reports:
=> [BUG] Av. offline files removed locally with the `Local only` option

CHANGELOG.md, changelog/unreleased/4420, owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/createshortcut/CreateShortcutDialogFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/transfers/TransfersAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.kt, owncloudApp/src/main/res/drawable/ic_action_open_shortcut.xml, owncloudApp/src/main/res/layout/create_shortcut_dialog.xml, owncloudApp/src/main/res/layout/main_file_list_fragment.xml, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/android/issues/4413
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Executions/Release_4.3/Shortcuts.md
Reports and improvements:
=> [FEATURE REQUEST] Open and create .url shortcut files

CHANGELOG.md, changelog/unreleased/4433, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/sharing/ShareActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt, owncloudApp/src/main/res/drawable/rounded_search_view.xml, owncloudApp/src/main/res/layout/owncloud_toolbar.xml, owncloudApp/src/main/res/values/colors.xml, owncloudApp/src/main/res/values/setup.xml, owncloudApp/src/main/res/values/strings.xml
App:
_____
QA checks:
https://github.com/owncloud/android/pull/4433#issuecomment-2233195218
=> [a11y] 11.1.4.11 Non-text contrast

CHANGELOG.md, changelog/unreleased/4438, owncloudApp/src/main/AndroidManifest.xml, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/sharing/ShareActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/sharing/ShareFileFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt, owncloudApp/src/main/res/layout/owncloud_toolbar.xml, owncloudApp/src/main/res/layout/share_activity.xml, owncloudApp/src/main/res/layout/share_public_dialog.xml
App: https://github.com/owncloud/android/issues/4366, https://github.com/owncloud/android/issues/4367 and https://github.com/owncloud/android/issues/4368
_____
=> [a11y] Hardware keyboard support

CHANGELOG.md, changelog/unreleased/4448, owncloudApp/src/main/res/layout/manage_accounts_dialog.xml, owncloudApp/src/main/res/layout/owncloud_toolbar.xml, owncloudApp/src/main/res/layout/share_file_layout.xml, owncloudApp/src/main/res/layout/share_public_dialog.xml, owncloudApp/src/main/res/layout/share_public_link_item.xml, owncloudApp/src/main/res/layout/share_user_item.xml
App:
_____
Review: https://github.com/owncloud/android/pull/4448#issuecomment-2277274597
Reports:
=> [a11y] 11.1.3.1a Info and relationships

CHANGELOG.md, changelog/unreleased/4437, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/RetryUploadFromSystemUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/UploadFileFromContentUriUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/UploadFileFromSystemUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/workers/DownloadFileWorker.kt, owncloudApp/src/main/java/com/owncloud/android/workers/RemoveLocalFileWorker.kt, owncloudApp/src/main/java/com/owncloud/android/workers/RemoveSourceFileWorker.kt, owncloudApp/src/main/java/com/owncloud/android/workers/UploadFileFromContentUriWorker.kt, owncloudApp/src/main/java/com/owncloud/android/workers/UploadFileFromFileSystemWorker.kt, owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/45.json, owncloudData/src/main/java/com/owncloud/android/data/OwncloudDatabase.kt, owncloudData/src/main/java/com/owncloud/android/data/ProviderMeta.java, owncloudData/src/main/java/com/owncloud/android/data/transfers/datasources/LocalTransferDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/transfers/datasources/implementation/OCLocalTransferDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/transfers/db/OCTransferEntity.kt, owncloudData/src/main/java/com/owncloud/android/data/transfers/db/TransferDao.kt, owncloudData/src/main/java/com/owncloud/android/data/transfers/repository/OCTransferRepository.kt, owncloudData/src/test/java/com/owncloud/android/data/transfers/datasources/implementation/OCLocalTransferDataSourceTest.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/transfers/TransferRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/transfers/model/OCTransfer.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCTransfer.kt
App:
_____
Checks:
https://github.com/owncloud/android/pull/4437#issuecomment-2257762959
Reports:
=> [FEATURE REQUEST] Improve the `removed from original folder` option in Auto Uploads

CHANGELOG.md, changelog/unreleased/4455, owncloudApp/src/main/java/com/owncloud/android/presentation/security/passcode/PassCodeActivity.kt
App: https://github.com/owncloud/android/issues/4447
_____
=> [ally] Keyboard navigation in security passcode view

CHANGELOG.md, changelog/unreleased/4463, owncloudApp/src/main/res/layout/manage_accounts_dialog.xml, owncloudApp/src/main/res/values/styles.xml
App: https://github.com/owncloud/android/issues/4442
_____
=> [BUG] Some colors are not correctly set up

CHANGELOG.md, changelog/unreleased/4464, changelog/unreleased/4467, owncloudApp/src/main/AndroidManifest.xml, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/res/values/strings.xml
=> [BUG] List filtering not working after rotating device

CHANGELOG.md, changelog/unreleased/4454, owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/security/passcode/NumberKeyboard.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/security/passcode/PassCodeActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/fragment/FileFragment.java, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt, owncloudApp/src/main/res/layout/passcode_edit_text.xml, owncloudApp/src/main/res/values/strings.xml
=> [TECHNICAL] Changes in accessibility role management

CHANGELOG.md, changelog/unreleased/4472, owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/EditPrivateShareFragmentTest.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/sharing/ShareActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/sharing/ShareViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/sharing/sharees/EditPrivateShareFragment.kt, owncloudApp/src/main/res/values/strings.xml, owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/sharing/ShareViewModelTest.kt
App: https://github.com/owncloud/android/issues/4397
_____
=> [TECHNICAL] Rely on `resharing` capability

CHANGELOG.md, changelog/unreleased/4470, owncloudApp/src/main/AndroidManifest.xml, owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/logging/LogsListActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/settings/SettingsActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.kt, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/android/issues/4458
_____
=> [a11y] Correct label for each activities and fragments

CHANGELOG.md, changelog/unreleased/4482, owncloudApp/src/main/java/com/owncloud/android/presentation/previews/PreviewAudioViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/previews/PreviewTextViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/previews/PreviewVideoViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.kt, owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/android/issues/4382
_____
Checks done: https://github.com/owncloud/android/pull/4482#issuecomment-2401663910
Reports:
=> [FEATURE REQUEST] Add status message when (un)setting av. offline from preview

changelog/unreleased/4484, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/res/layout/nav_coordinator_layout.xml, owncloudApp/src/main/res/values/strings.xml
Added text labels to the bottom nav bar
Used default activeStateIndicator which will show which label is selected
Now, all the items in nav bar shows the labels and upon selection the activeIndicator is enabled which shows that which item is selected.
Fix#4484
=> [FEATURE REQUEST] Add text labels to bottom nav bar

CHANGELOG.md, changelog/unreleased/4507, gradle.properties, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, owncloudApp/build.gradle, owncloudApp/src/main/java/com/owncloud/android/workers/DownloadFileWorker.kt, owncloudComLibrary/build.gradle, owncloudData/build.gradle, owncloudDomain/build.gradle, owncloudTestUtil/build.gradle
App: https://github.com/owncloud/android/issues/4478
_____
https://github.com/owncloud/android/pull/4507#issuecomment-2454737622
=> [TECHNICAL] Update Android Gradle Plugin version

CHANGELOG.md, changelog/unreleased/4389, owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt, owncloudData/src/test/java/com/owncloud/android/data/files/repository/OCFileRepositoryTest.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCFile.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCSpace.kt
App: https://github.com/owncloud/android/issues/4233
_____
=> [TECHNICAL] Unit tests for repository classes - Part 2

owncloudData/src/test/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSourceTest.kt
App: https://github.com/owncloud/android/issues/4517
_____
=> [TECHNICAL] Pending unit tests for `OCRemoteServerInfoDataSource`

CHANGELOG.md, changelog/unreleased/4518, owncloudApp/src/main/java/com/owncloud/android/MainApp.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/ManageAccountsAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/ManageAccountsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/common/DrawerViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainEmptyListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/settings/automaticuploads/SettingsPictureUploadsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/settings/automaticuploads/SettingsPictureUploadsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/settings/automaticuploads/SettingsVideoUploadsFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/settings/automaticuploads/SettingsVideoUploadsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/ReceiveExternalFilesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java, owncloudApp/src/main/res/layout/main_empty_list_fragment.xml, owncloudApp/src/main/res/values/strings.xml, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/GetBaseUrlRemoteOperation.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/repository/OCSpacesRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/user/model/UserQuota.kt
App: https://github.com/owncloud/android/issues/4490
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Executions/Release_4.5/No%20Personal%20space.md
Reports:
=> [FEATURE REQUEST] oCIS Users light

.github/workflows/detekt.yml
=> Run GH actions in parallel (Detekt)

CHANGELOG.md, changelog/unreleased/4525, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/ManageAccountsAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/common/DrawerViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt, owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/DrawerViewModelTest.kt, owncloudData/src/main/java/com/owncloud/android/data/user/datasources/LocalUserDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/user/datasources/implementation/OCLocalUserDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/user/db/UserDao.kt, owncloudData/src/main/java/com/owncloud/android/data/user/repository/OCUserRepository.kt, owncloudData/src/test/java/com/owncloud/android/data/user/datasources/implementation/OCLocalUserDataSourceTest.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/user/UserRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/user/usecases/GetStoredQuotaAsStreamUseCase.kt
App: https://github.com/owncloud/android/issues/4521
_____
Test Plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Executions/Release_4.5/Quota%20Refactor%20(4525).md
=> [TECHNICAL] Technical improvements for user quota

CHANGELOG.md, changelog/unreleased/4527, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/capabilities/CapabilityViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListAdapter.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt, owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/capabilities/CapabilityViewModelTest.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/responses/SpacesResponse.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/RemoteCapability.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/responses/CapabilityResponse.kt, owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/47.json, owncloudData/src/main/java/com/owncloud/android/data/OwncloudDatabase.kt, owncloudData/src/main/java/com/owncloud/android/data/ProviderMeta.java, owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/mapper/RemoteCapabilityMapper.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/db/SpaceSpecialEntity.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/db/SpacesEntity.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/repository/OCSpacesRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/capabilities/model/OCCapability.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/model/OCSpace.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/usecases/GetPersonalSpacesWithSpecialsForAccountAsStreamUseCase.kt
App: https://github.com/owncloud/android/issues/4514
_____
https://github.com/owncloud/android/pull/4527#issuecomment-2582707537
=> [FEATURE REQUEST] Multi-Personal (1st round)

.github/workflows/detekt.yml
=> [FIX] Fix Detekt workflow because paths makes PR not to trigger it

CHANGELOG.md, changelog/unreleased/4537, owncloudData/src/test/java/com/owncloud/android/data/spaces/repository/OCSpacesRepositoryTest.kt, owncloudData/src/test/java/com/owncloud/android/data/transfers/repository/OCTransferRepositoryTest.kt, owncloudData/src/test/java/com/owncloud/android/data/user/repository/OCUserRepositoryTest.kt, owncloudData/src/test/java/com/owncloud/android/data/webfinger/repository/OCWebFingerRepositoryTest.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCCapability.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCSpace.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCTransfer.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCUser.kt
App: https://github.com/owncloud/android/issues/4235
_____
=> [TECHNICAL] Unit tests for repository classes - Part 4

.github/workflows/detekt.yml
After latest check, just triggering `./gradlew detekt` is enough to check all the modules at the time.
If any smell raises up in a module, the execution will stop. The only way to make parallel execution is creating 5 different jobs.
=> [TECHNICAL] Send just one Detekt command against all modules

CHANGELOG.md, changelog/unreleased/4542, gradle/libs.versions.toml
App: https://github.com/owncloud/android/issues/4333
_____
=> [FIX] Crash from Google Play Store

CHANGELOG.md, changelog/unreleased/4548, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
App: https://github.com/owncloud/android/issues/4428
_____
https://github.com/owncloud/android/pull/4548#issuecomment-2654291890
=> [FIX] Removing local copy of non-previewable file leads to empty view

.github/workflows/calens.yml
=> [TECHNICAL] Change Calens configuration in order not to block Github Actions

.github/workflows/android-unit-tests.yml
=> [TECHNICAL] Move unit tests from Bitrise to GitHub Actions

changelog/unreleased/4553, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
This PR fixes an issue where the folder size was not updating correctly after replacing a file with the same name. Previously, the folder size showed duplicate files until a manual refresh was performed. 
- Auto-refreshes folder size after file replacement.
- Uses `fileOperationsViewModel.performOperation(FileOperation.RefreshFolderOperation(...))`.
- Ensures correct quota updates in `spacesListViewModel.refreshSpacesFromServer()`.
Fixes #<4505> 
1. Move a file to a folder that already contains the same file.
2. Click **Replace** in the warning dialog.
3. The folder size should update **automatically** without manual refresh.
https://github.com/user-attachments/assets/3d67bd2b-d9a8-4d41-8304-49141808e78f
=> [FIX] Ensure folder size updates automatically after file replacement 

CHANGELOG.md, changelog/unreleased/4562, owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/res/values/strings.xml, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/responses/AppRegistryResponse.kt, owncloudData/src/main/java/com/owncloud/android/data/appregistry/datasources/implementation/OCRemoteAppRegistryDataSource.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/appregistry/model/AppRegistry.kt
App: https://github.com/owncloud/android/issues/4560
_____
Checks: https://github.com/owncloud/android/pull/4562#issuecomment-2754199284
Reports
=> [FIX] Confusing behaviour when creating new files using apps provider

CHANGELOG.md, changelog/unreleased/4564, owncloudApp/src/main/java/com/owncloud/android/presentation/security/biometric/BiometricActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/security/biometric/BiometricManager.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/security/passcode/PassCodeActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/security/passcode/PassCodeManager.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/security/pattern/PatternActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/security/pattern/PatternManager.kt, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/enterprise/issues/7134
_____
=> [FIX] App crashes at start when biometrics fail

CHANGELOG.md, build.gradle, changelog/unreleased/4556, owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
App: https://github.com/owncloud/android/issues/4529
_____
=> [TECHNICAL] Bump Android SDK to API 35 (Android 15)

CHANGELOG.md, changelog/unreleased/4558, owncloudComLibrary/build.gradle
App: https://github.com/owncloud/android/issues/4536
_____
=> [TECHNICAL] Replace dav4android location

changelog/unreleased/4567, owncloudApp/src/main/res/layout/account_item.xml
App: #4566 
_____
Before fix
After fix
=> [FIX] Lack of margin when multiaccount is disabled

CHANGELOG.md, changelog/unreleased/4574, owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
App: https://github.com/owncloud/android/issues/4522
_____
=> [FIX] Content in Spaces not shown from 3rd party apps

CHANGELOG.md, changelog/unreleased/4579, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/DocumentsStorageProvider.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/cursors/FileCursor.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/res/values/strings.xml
App: https://github.com/owncloud/android/issues/4515
_____
QA checks: https://github.com/owncloud/android/pull/4579#issuecomment-2834288890
=> [FEATURE REQUEST] Shares space in Android native file explorer

CHANGELOG.md, changelog/unreleased/4581, owncloudApp/src/main/res/values/styles.xml
App: https://github.com/owncloud/android/issues/4576
_____
=> [FIX] Infinite edges Android 15

CHANGELOG.md, changelog/unreleased/4587, owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/ManageAccountsViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
App: https://github.com/owncloud/android/issues/4582
_____
QA checks:
Reports:
=> [FIX] No message when uploading a file with no quota

CHANGELOG.md, changelog/unreleased/4586, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
App: https://github.com/owncloud/android/issues/4080
_____
Checks done: https://github.com/owncloud/android/pull/4586#issuecomment-2909025118
Reports:
=> [FIX] Token request with `Bearer` returns error

.github/workflows/android-instrumented-data-tests.yml, .github/workflows/android-instrumented-tests.yml, .github/workflows/android-unit-tests.yml, CHANGELOG.md, changelog/unreleased/4602
App: https://github.com/owncloud/android/issues/4595
_____
=> [TECHNICAL] Integrate instrumented tests into GitHub Actions 

.github/workflows/sbom.yml, CHANGELOG.md, changelog/unreleased/4599
Changes: 
- Replaced the `read` permission for `write`, since we have to push
- `sbom.json` to be created when pushing to `master`. Before: in every PR, does not matter the target branch.
- `sbom.json` file in root folder of the current repository
- Added a step that will compare the `sbom.json` in `master` with the generated one. If they match, no push (no changes since the latest time).
App:
_____
=> [FEATURE REQUEST] Modify sbom workflow to push to the repo

.github/workflows/sbom.yml
=> fix: add an extra step to load ssh setup

.github/workflows/sbom.yml
=> fix: check if sbom is not triggered if it does not differ 

CHANGELOG.md, README.md, changelog/unreleased/4637
Implements: https://github.com/owncloud/android/issues/4623
Removes the status from BitRise and adds three badges from GitHub Actions
- Unit tests
- Data instrumented tests
- Detekt
Other badges could be added in the future. This is how it looks like:
Badges shows the status of the latest execution.
App:
_____
=> [FEATURE REQUEST] Add GitHub Actions badges to README removing the BitRise ones

.github/workflows/sbom.yml
Previous version tried to push the `sbom.json` file generated by CI to the `master` branch, but the branch protection rules prevented to perform such action. Current PR would fix that.
Included:
- SSH is used to perform the commit. To push the commit, an SSH public key and private key must be configured in the repository settings.
- The current version of the SBOM is normalized and compared with the previous one. A commit is only made if differences are found.
- If a commit is made, it will trigger another job, which will be skipped due to a condition defined in the job configuration.
@DeepDiver1975 you added a `DEPLOYMENT_SSH_KEY` in Deploy Keys of Settings. That's the public key, it would be required to add the private key as repo secret as well. Other option: I created a pair of keys …
=> [FIX] Push sbom into master after merging via ssh

CHANGELOG.md, changelog/unreleased/4632, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AccountAuthenticator.java, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/oauth/OAuthUtils.kt, owncloudApp/src/main/res/values/setup.xml, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/ConnectionValidator.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudAccount.java, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/SingleSessionManager.java, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java, owncloudData/src/main/java/com/owncloud/android/data/authentication/AuthenticationConstants.kt, owncloudData/src/main/java/com/owncloud/android/data/authentication/datasources/implementation/OCLocalAuthenticationDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/authentication/datasources/implementation/OCRemoteAuthenticationDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/oauth/datasources/implementation/OCRemoteOAuthDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSource.kt, owncloudData/src/test/java/com/owncloud/android/data/oauth/datasources/implementation/OCRemoteOAuthDataSourceTest.kt, owncloudData/src/test/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSourceTest.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/authentication/oauth/model/OIDCServerConfiguration.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/oauth/OIDCServerConfiguration.kt
App: https://github.com/owncloud/android/issues/4622
_____
=> [FEATURE REQUEST] Create new set of configurations for Kiteworks servers in setup.xml

.github/workflows/sbom.yml, CHANGELOG.md, changelog/unreleased/4599
What does it do?:
- Creates the SBOM file over the feature branch code
- Compares with the latest commit SBOM, after normalizing both versions
- If there are no differences, end
- If there are differences, commit  
- If the commit is sent, new job triggered and skipped because the latest commit's message matches `SBOM updated`
- Commit will be created whenever changes in the newly generated sbom happen.
App:
_____
=> [FIX] Workflow to update sbom only if different than the latest one

CHANGELOG.md, changelog/unreleased/4657, owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/RetryUploadFromSystemUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/UploadFileFromSystemUseCase.kt, owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/UploadFilesFromSystemUseCase.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/chunks/ChunkedUploadFromFileSystemOperation.kt
App: https://github.com/owncloud/android/issues/4653
_____
=> [FIX] Removed files in failed uploads 

CHANGELOG.md, changelog/unreleased/4685, owncloudApp/src/main/java/com/owncloud/android/extensions/OCTransferExt.kt, owncloudApp/src/main/java/com/owncloud/android/extensions/ThrowableExt.kt, owncloudApp/src/main/res/values/strings.xml, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java, owncloudData/src/main/java/com/owncloud/android/data/RemoteOperationHandler.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/exceptions/PayloadTooLongException.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/transfers/model/TransferResult.kt
App: https://github.com/owncloud/android/issues/4094
_____
https://github.com/owncloud/android/pull/4685#issuecomment-3365419895
=> [FIX] Handling of HTTP response code 413

CHANGELOG.md, changelog/unreleased/4687, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt, owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt, owncloudApp/src/main/java/com/owncloud/android/extensions/SpaceMenuOptionExt.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListDiffUtil.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListFragment.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListViewModel.kt, owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/createspace/CreateSpaceDialogFragment.kt, owncloudApp/src/main/res/layout/create_space_dialog.xml, owncloudApp/src/main/res/values/strings.xml, owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/nonwebdav/PatchMethod.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/EditRemoteSpaceOperation.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/GetRemoteSpacePermissionsOperation.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/services/OCSpacesService.kt, owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/services/SpacesService.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/implementation/OCRemoteSpacesDataSource.kt, owncloudData/src/main/java/com/owncloud/android/data/spaces/repository/OCSpacesRepository.kt, owncloudData/src/test/java/com/owncloud/android/data/spaces/datasources/implementation/OCRemoteSpacesDataSourceTest.kt, owncloudData/src/test/java/com/owncloud/android/data/spaces/repository/OCSpacesRepositoryTest.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/SpacesRepository.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/model/OCSpace.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/model/SpaceMenuOption.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/usecases/EditSpaceUseCase.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/usecases/FilterSpaceMenuOptionsUseCase.kt, owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/usecases/GetSpacePermissionsAsyncUseCase.kt, owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCSpace.kt
App: https://github.com/owncloud/android/issues/4607
_____
Test Plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Executions/Release_4.7/Spaces%20-%20Edit.md
Reports
=> [FEATURE REQUEST] Edit space

.github/workflows/update.yml, CHANGELOG.md, changelog/unreleased/4690
The update test executed in GitHub actions has some flaky executions. In order to make it more robust and deterministic, some changes were done in the workflow:
- Adding `-no-snapshot` to the emulator options: That options will assure that no leftovers from other executions affect to the current one. It will work together with the `force-avd-creation` parameter.
- Switching `auto` for `on` in the `-accel` parameter: if hardware acceleration is available, it will be used making the test more robust. If not available, test will fail. GitHub actions' runners have the option available, so, we can assume that "con"
- Increasing memory assigned to the emulator, so, it will be less likely to hang (from 2048 to 4096 MB)
- Added `--no-daemon` to `gradlew` command. That should not affect because …
=> [FIX] Improve some emulator and gradle parameters 
