owncloud/android

src/com/owncloud/android/ui/activity/FileDisplayActivity.java

This code never worked as intended. Please consider adding unit tests.

Use .equals instead of !=

---

res/values/strings.xml
src/com/owncloud/android/ui/fragment/OCFileListFragment.java

…osition)
Conflicts FIXED:
res/values/strings.xml

Message with count of list(s) and folder(s) reestructured for better translations

---

src/com/owncloud/android/ui/adapter/FileListListAdapter.java

ShareWithMe icon is shown in the file list.
In the gridview, if it is a folder, shareWithMe icon is not shown. 
In the gridview, if it is a folder, ShareByLink is shown. The folder can be also be shared with me and It would be lose of information, because the icon above the folder is the ShareWithMe. If it is not correct and the icon should not be there, there is a commented line to be use.
In the gridview, if it is a file, both of them are shown

ShareWithMe icon in file list

---

res/layout/file_details_fragment.xml
res/menu/file_actions_menu.xml
res/values/strings.xml
src/com/owncloud/android/datamodel/FileDataStorageManager.java
src/com/owncloud/android/datamodel/OCFile.java
src/com/owncloud/android/files/FileMenuFilter.java
src/com/owncloud/android/files/FileOperationsHelper.java
src/com/owncloud/android/operations/RefreshFolderOperation.java
src/com/owncloud/android/operations/SynchronizeFileOperation.java
src/com/owncloud/android/operations/SynchronizeFolderOperation.java
src/com/owncloud/android/operations/UploadFileOperation.java
src/com/owncloud/android/ui/activity/FileActivity.java
src/com/owncloud/android/ui/activity/FileDisplayActivity.java
src/com/owncloud/android/ui/adapter/FileListListAdapter.java
src/com/owncloud/android/ui/dialog/RemoveFileDialogFragment.java
src/com/owncloud/android/ui/fragment/FileDetailFragment.java
src/com/owncloud/android/ui/fragment/OCFileListFragment.java
src/com/owncloud/android/ui/preview/PreviewImageActivity.java
src/com/owncloud/android/ui/preview/PreviewImageFragment.java
src/com/owncloud/android/ui/preview/PreviewMediaFragment.java

This PR will fix this issue #786 .
There is a bug. Menu is not refreshed in the gallery neither in the preview of the video when Unfavorite is clicked. @davivel , @masensio could you give me some tips to fix this?
It is pending to change name of variables from keepInSync to favorites. But I's rather wait until the bug is fixed.
Also, we should take into account transifex if we merge that. british english, spanish

Favourites context menu

---

res/layout/file_actions.xml
src/com/owncloud/android/ui/dialog/FileActionsDialogFragment.java
src/com/owncloud/android/ui/fragment/OCFileListFragment.java

solution as discussed and decided on in issue #559

Show file name in the long press menu, see #559

---

src/com/owncloud/android/ui/activity/FileDisplayActivity.java
src/com/owncloud/android/ui/fragment/FileDetailFragment.java

Branch created by @masensio 
Fixed bug, found by @Dianafg76, by me

Display thumbnails details view pr 1065

---

res/values/strings.xml
src/com/owncloud/android/datamodel/FileDataStorageManager.java
src/com/owncloud/android/datamodel/OCFile.java
src/com/owncloud/android/db/ProviderMeta.java
src/com/owncloud/android/files/FileOperationsHelper.java
src/com/owncloud/android/operations/CreateShareOperation.java
src/com/owncloud/android/operations/CreateShareViaLinkOperation.java
src/com/owncloud/android/operations/CreateShareWithShareeOperation.java
src/com/owncloud/android/operations/UnshareOperation.java
src/com/owncloud/android/providers/FileContentProvider.java
src/com/owncloud/android/services/OperationsService.java
src/com/owncloud/android/ui/activity/FileActivity.java
src/com/owncloud/android/ui/activity/FileDisplayActivity.java
src/com/owncloud/android/ui/activity/ShareActivity.java
src/com/owncloud/android/ui/adapter/FileListListAdapter.java
src/com/owncloud/android/ui/fragment/ShareFileFragment.java
src/com/owncloud/android/ui/preview/PreviewImageActivity.java
src/com/owncloud/android/utils/ErrorMessageAdapter.java

Another increment on the 'share with users' functionality. Added the operation to create new shares when a user is chosen in the list of suggestions.
Once again, not ready for formal QA yet.
@masensio, @AndyScherzinger , @tobiasKaminsky , @all : code reviews are welcome.

Share with users -- add share

---

src/com/owncloud/android/files/FileOperationsHelper.java
src/com/owncloud/android/operations/CreateShareViaLinkOperation.java
src/com/owncloud/android/operations/CreateShareWithShareeOperation.java
src/com/owncloud/android/ui/activity/FileActivity.java
src/com/owncloud/android/ui/activity/FileDisplayActivity.java
src/com/owncloud/android/ui/activity/FolderPickerActivity.java
src/com/owncloud/android/ui/activity/ShareActivity.java
src/com/owncloud/android/ui/activity/Uploader.java
src/com/owncloud/android/ui/fragment/FileFragment.java
src/com/owncloud/android/ui/fragment/OCFileListFragment.java
src/com/owncloud/android/ui/fragment/SearchShareesFragment.java
src/com/owncloud/android/ui/fragment/ShareFileFragment.java
src/com/owncloud/android/ui/preview/PreviewImageActivity.java
src/com/owncloud/android/ui/preview/PreviewImageFragment.java
src/com/owncloud/android/ui/preview/PreviewMediaFragment.java
src/com/owncloud/android/ui/preview/PreviewTextFragment.java
src/com/owncloud/android/utils/ErrorMessageAdapter.java
src/com/owncloud/android/utils/GetShareWithUsersAsyncTask.java

Share with users  fixes

---

src/com/owncloud/android/utils/DisplayUtils.java

This PR contains the Fix for the date/time display for files and folders for certain locales as discussed in #1192 
@rperezb hope I labelled it correctly.
Please review @davivel @tobiasKaminsky @masensio

fix for #1192

---

res/values/setup.xml

As mentioned by @jancborchardt here #1288

Use correct name capitalization in application name

---

src/com/owncloud/android/files/InstantUploadBroadcastReceiver.java

[Beta] Fix NPE in instant uploads

---

build.gradle
project.properties

Reverts owncloud/android#1321 due to protocol sidestep

Revert "Force ant and android studio to use Java7"

---

build.gradle
project.properties

Force ant and android studio to use Java7

---

res/values/strings.xml

Fix some wording, mostly:
- fix capitalization to only capitalize first word of any given action. This is how it should always be.
- change »Switch to list/grid view« to simpler »Grid/List view«.
- fixed various technical instances of words like »URL« etc.
Please review @tobiasKaminsky @AndyScherzinger 
@davivel @masensio @rperezb please make sure we also fix this in the iOS app.

wording fixes, simplify some strings and fix capitalization

---

res/values/strings.xml
res/xml/preferences.xml

and moved position
ref: https://github.com/owncloud/android/issues/1309#issuecomment-160066159

renamed security category to details for further use

---

src/com/owncloud/android/authentication/AuthenticatorActivity.java

Fixes #7541: Catched invalid argument in URI parsing

---

CONTRIBUTING.md

* Added references to SETUP.md and Github issues tracker
* fixes some typos/formatting

Added further references in CONTRIBUTING.md documentation

---

res/values/strings.xml
src/com/owncloud/android/datamodel/FileDataStorageManager.java
src/com/owncloud/android/db/ProviderMeta.java
src/com/owncloud/android/operations/CreateShareWithShareeOperation.java
src/com/owncloud/android/operations/UnshareOperation.java
src/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
src/com/owncloud/android/ui/activity/ShareActivity.java
src/com/owncloud/android/ui/fragment/EditShareFragment.java

Enabled federate sharing, and autocompletion of users from well known servers. 
@davivel @rperezb

Federated sharing

---

res/layout/share_file_layout.xml
res/values/strings.xml
src/com/owncloud/android/files/FileOperationsHelper.java
src/com/owncloud/android/operations/UpdateShareViaLinkOperation.java
src/com/owncloud/android/services/OperationsService.java
src/com/owncloud/android/ui/fragment/ShareFileFragment.java

As an Android user I want to decide whether edit is allowed or not when sharing via link a FOLDER so that I control the level of access

Edit public share permission

---

CONTRIBUTING.md
SETUP.md

Replacing #1488, rebased on master

Improved contribution and setup docs by sudhirkhanger

---

res/layout-land/account_setup.xml
res/layout/account_setup.xml
res/values/colors.xml
res/values/oauth2_configuration.xml
res/values/setup.xml

New branding for login text color, changing all text but hints and text of AppCompat buttons
Moved 'New to ownCloud' link to bottom of display screen.

Text color config login view

---

res/layout/edit_box_dialog.xml

Replicate of @sudhirkhanger PR https://github.com/owncloud/android/pull/1543

Capitalize folder name  review

---

.travis.yml
build.gradle
test/java/com/owncloud/android/utils/ErrorMessageAdapterUnitTest.java

Added first local unit test, runnable in Gradle/Android Studio environment

Automatic unit tests

---

issue_template.md

With this it is more logical: In Topic is a brief description of the problem, then the steps, then actual behaviour, then desired behaviour.
@jancborchardt @davivel

reorder issue template

---

res/values/strings.xml

Remove comment xml element

---

AndroidManifest.xml
build.gradle
res/values/setup.xml
res/xml/users_and_groups_searchable.xml
src/com/owncloud/android/MainApp.java
src/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
src/com/owncloud/android/ui/activity/ShareActivity.java

Fixes #1734 
Fixes #1735 
cc @jesmrec

Customizable strings for users&groups search provider

---

src/com/owncloud/android/ui/activity/ShareActivity.java
src/com/owncloud/android/ui/fragment/EditShareFragment.java

To be merged after #1749 .
Requires https://github.com/owncloud/android-library/pull/127 .
Fixes #1725

Allow unshareable federated shares

---

.travis.yml
AndroidManifest.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
oc_jb_workaround/build.gradle

Replaces #1744, after rebase and update of reference to library

Update of build target to Android Nougat, with multiwindow

---

src/com/owncloud/android/MainApp.java

@jesmrec , could receive minimal testing to check that logs are OK. I wouldn't create a test plan.
Needed for owncloud/android-library#96

Adapt to new OC_Log.startLogging(...) with path parameter

---

AndroidManifest.xml
CHANGELOG.md
oc_jb_workaround/AndroidManifest.xml
res/values/strings.xml
src/com/owncloud/android/broadcastreceivers/BootupBroadcastReceiver.java
src/com/owncloud/android/broadcastreceivers/ConnectivityActionReceiver.java
src/com/owncloud/android/broadcastreceivers/InstantUploadBroadcastReceiver.java
src/com/owncloud/android/services/observer/InstantUploadsHandler.java
src/com/owncloud/android/services/observer/InstantUploadsObserver.java
src/com/owncloud/android/ui/activity/Preferences.java

Fixes broken instant uploads in multiple Android 6 devices after changes in version 2.1.1

Release 2.1.2

---

gradle.properties

Update reference to OC library after increasing timeout for last chunk

---

src/com/owncloud/android/ui/fragment/EditShareFragment.java

Federated sharing edit options

---

src/com/owncloud/android/operations/UploadFileOperation.java

Updated android library to fix bug related to file modification date

---

src/com/owncloud/android/MainApp.java
src/com/owncloud/android/authentication/AuthenticatorActivity.java

Fixes #1841 
Requires owncloud/android-library#141

Keep a single session with the server if its version is >= 9.1

---

src/com/owncloud/android/ui/fragment/OCFileListFragment.java

Fixes https://github.com/owncloud/android/issues/1847#issuecomment-266687493

App stops orientation changed

---

AndroidManifest.xml
CHANGELOG.md
oc_jb_workaround/AndroidManifest.xml
src/com/owncloud/android/datamodel/FileDataStorageManager.java
src/com/owncloud/android/ui/fragment/OCFileListFragment.java

Validation in https://github.com/owncloud/android/issues/1847

Release 2.2.0

---

build.gradle
res/values-b+crp/strings.xml
res/values/strings.xml
src/com/owncloud/android/authentication/AuthenticatorActivity.java
src/com/owncloud/android/db/UploadResult.java
src/com/owncloud/android/operations/UnshareOperation.java
src/com/owncloud/android/operations/UploadFileOperation.java
src/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java
src/com/owncloud/android/ui/notifications/NotificationUtils.java
src/com/owncloud/android/utils/ErrorMessageAdapter.java

Fix #1722 
Requires: https://github.com/owncloud/android-library/pull/144

Bug 1722 maintenance mode

---

src/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java

Encode properly the password

---

res/values/strings.xml
src/com/owncloud/android/db/UploadResult.java
src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java
src/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.java

Fix #1767
~~Requires https://github.com/owncloud/android-library/pull/147~~

Insufficient storage error

---

src/com/owncloud/android/authentication/AuthenticatorActivity.java

Fixes #1863 
Fixes #1874 
Requires owncloud/android-library#148

Fix log into OC server version 10

---

res/values/strings.xml
src/com/owncloud/android/authentication/AuthenticatorActivity.java
src/com/owncloud/android/db/UploadResult.java
src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java
src/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.java

Requires https://github.com/owncloud/android-library/pull/152
Fix #1759

Firewall error messages

---

res/values-bg-rBG/strings.xml
res/values-de-rDE/strings.xml
res/values-de/strings.xml
res/values-es/strings.xml
res/values-fi-rFI/strings.xml
res/values-he/strings.xml
res/values-it/strings.xml
res/values-nl/strings.xml
res/values-pt-rBR/strings.xml
res/values-pt-rPT/strings.xml
res/values-ru/strings.xml
res/values-sl/strings.xml
res/values-sq/strings.xml
res/values-th-rTH/strings.xml
res/values-uk/strings.xml
res/values/strings.xml
src/com/owncloud/android/authentication/AuthenticatorActivity.java
src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java
src/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.java

Login error messages

---

AndroidManifest.xml
res/layout/activity_privacy_policy.xml
res/values/setup.xml
res/values/strings.xml
res/xml/preferences.xml
src/com/owncloud/android/ui/activity/Preferences.java
src/com/owncloud/android/ui/activity/PrivacyPolicyActivity.java

Privacy policy

---

src/com/owncloud/android/authentication/AuthenticatorActivity.java

This fixes #1852. It will automatically convert the subdomain part of the url to lower case.

Fix uppercase domain bug

---

src/com/owncloud/android/ui/activity/FileDisplayActivity.java

Correct drawer button behaviour on tablets

---

res/layout/upload_list_group.xml
res/values/strings.xml
src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java

Show section file count in uploads screen

---

res/layout/edit_box_dialog.xml

Add dialog padding

---

res/values/strings.xml
src/com/owncloud/android/datamodel/FileDataStorageManager.java
src/com/owncloud/android/db/ProviderMeta.java
src/com/owncloud/android/operations/RemoveShareOperation.java
src/com/owncloud/android/providers/FileContentProvider.java
src/com/owncloud/android/services/OperationsService.java
src/com/owncloud/android/ui/activity/FileActivity.java
src/com/owncloud/android/ui/activity/ShareActivity.java
src/com/owncloud/android/ui/adapter/SharePublicLinkListAdapter.java
src/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.java
src/com/owncloud/android/ui/fragment/SearchShareesFragment.java
src/com/owncloud/android/ui/fragment/ShareFileFragment.java
src/com/owncloud/android/ui/fragment/ShareFragmentListener.java
src/com/owncloud/android/ui/helpers/FileOperationsHelper.java

Requires https://github.com/owncloud/android-library/pull/160

Connect 'trash' and 'link' buttons of public shares to actions

---

res/values/setup.xml
src/com/owncloud/android/datamodel/FileDataStorageManager.java
src/com/owncloud/android/db/ProviderMeta.java
src/com/owncloud/android/providers/FileContentProvider.java
src/com/owncloud/android/ui/fragment/ShareFileFragment.java

Requires https://github.com/owncloud/android-library/pull/162

Show warning about public shares is enabled by admin in server side

---

androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
androidTest/java/com/owncloud/android/utils/AccountsManager.java
build.gradle

UI testing suite on the ´AuthenticatorActivity´ activity to check the login feature.
Included:
- Positive and negative test cases. 
- Checks in both orientations 
- Accounts Manager: to add/remove ownCloud accounts from device.
To do:
- SAML Servers

Login Test Suite Espresso

---

.github/release_template.md

It would be great to have the information prior to the release so we can publish this stuff better.

added community to make releases more prominent in public

---

res/layout/share_public_dialog.xml
res/values/strings.xml
src/com/owncloud/android/datamodel/FileDataStorageManager.java
src/com/owncloud/android/db/ProviderMeta.java
src/com/owncloud/android/operations/CreateShareViaLinkOperation.java
src/com/owncloud/android/operations/CreateShareWithShareeOperation.java
src/com/owncloud/android/operations/UpdateShareViaLinkOperation.java
src/com/owncloud/android/providers/FileContentProvider.java
src/com/owncloud/android/services/OperationsService.java
src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java
src/com/owncloud/android/ui/helpers/FileOperationsHelper.java

Fixes #1971 
Requires https://github.com/owncloud/android-library/pull/168

Write only share

---

src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java

Fix #1993 
Requires https://github.com/owncloud/android-library/pull/170

Fix write only 10.0.0

---

res/values/strings.xml
src/com/owncloud/android/db/UploadResult.java
src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java

FIx #1977 
Requires https://github.com/owncloud/android-library/pull/166

Improve feedback when uploading virus files

---

src/com/owncloud/android/files/FileMenuFilter.java

Fix https://github.com/owncloud/android/issues/2004

Forbidden reshare

---

src/com/owncloud/android/media/MediaService.java

fix a memory leak prior Android N (WIFI_SERVICE)

---

.travis.yml
AndroidManifest.xml
build.gradle
oc_jb_workaround/AndroidManifest.xml
oc_jb_workaround/build.gradle
res/values/strings.xml
src/com/owncloud/android/files/services/FileDownloader.java
src/com/owncloud/android/files/services/FileUploader.java
src/com/owncloud/android/media/MediaService.java
src/com/owncloud/android/syncadapter/FileSyncAdapter.java
src/com/owncloud/android/ui/notifications/NotificationUtils.java

Needs https://github.com/owncloud/android-library/pull/179

Migrate to Android O

---

androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java
res/layout/share_file_layout.xml
res/values/strings.xml
src/com/owncloud/android/datamodel/FileDataStorageManager.java
src/com/owncloud/android/datamodel/OCFile.java
src/com/owncloud/android/db/ProviderMeta.java
src/com/owncloud/android/providers/FileContentProvider.java
src/com/owncloud/android/ui/activity/ShareActivity.java
src/com/owncloud/android/ui/fragment/ShareFileFragment.java
src/com/owncloud/android/ui/fragment/ShareFragmentListener.java
src/com/owncloud/android/ui/helpers/FileOperationsHelper.java
src/com/owncloud/android/utils/FileStorageUtils.java

Fixes #2032 
Needs https://github.com/owncloud/android-library/issues/175
**Do not merge before 2.5.0 is released.**
cc @davigonz, @jesmrec .

Private link in webdav

---

CHANGELOG.md
build.gradle

Including the versions and changelog for the new 2.5.1 beta, could you have a look at it? @jesmrec

Including new versions and changelog for 2.5.1 beta v1 version

---

build.gradle

This PR includes the signing configuration to compile the beta app automatically

Include beta signing configuration

---

src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java

This pr solves issue #2080. It thus displays file size during upload.

show file size while uploading

---

src/com/owncloud/android/files/services/FileUploader.java
src/com/owncloud/android/files/services/TransferRequester.java

Fix ownCloud notification always visible in Android 8

---

res/values/strings.xml
src/com/owncloud/android/ui/activity/UploadFilesActivity.java

Issue #2141 fixed. Now the file of the picture taken from the device's camera is uploaded. Instead of their thumbnails.

Fix to Issue #2141

---

res/drawable/ic_star_black_24dp.xml
res/layout/rate_me_dialog.xml
res/values/setup.xml
res/values/strings.xml
src/com/owncloud/android/AppRater.java
src/com/owncloud/android/ui/activity/FileDisplayActivity.java
src/com/owncloud/android/ui/dialog/RateMeDialog.java

fixed the requested changes for the [title view](https://github.com/owncloud/android/pull/2102#pullrequestreview-100779423) of https://github.com/owncloud/android/pull/2102, and only make it visible on beta releases.

add Rateme

---

src/com/owncloud/android/ui/activity/PatternLockActivity.java

fixes https://github.com/owncloud/android/issues/2135#issuecomment-378140629

fix dissmiss pattern lock on back button

---

src/com/owncloud/android/authentication/FingerprintManager.java
src/com/owncloud/android/authentication/PassCodeManager.java
src/com/owncloud/android/authentication/PatternManager.java
src/com/owncloud/android/ui/activity/FileDisplayActivity.java

@jesmrec I've created a pull request for this bug because I wan't your opinion about this. Can it be seen as a whole punched into the idea of security fingerprint unlock tries to create?
Related to this https://github.com/owncloud/android/issues/2135#issuecomment-376111631 and this https://github.com/owncloud/android/issues/2135#issuecomment-374153626

fix no requthentification return form requesting other apps

---

CHANGELOG.md
androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
build.gradle
oc_jb_workaround/build.gradle
res/layout/whats_new_element.xml
src/com/owncloud/android/authentication/FingerprintManager.java
src/com/owncloud/android/authentication/PassCodeManager.java
src/com/owncloud/android/authentication/PatternManager.java
src/com/owncloud/android/features/FeatureList.java
src/com/owncloud/android/ui/activity/FileActivity.java
src/com/owncloud/android/ui/activity/FileDisplayActivity.java
src/com/owncloud/android/ui/activity/PatternLockActivity.java
src/com/owncloud/android/ui/activity/UploadFilesActivity.java
src/com/owncloud/android/ui/dialog/FingerprintAuthDialogFragment.java
src/com/owncloud/android/ui/fragment/ExtendedListFragment.java
src/com/owncloud/android/ui/fragment/OCFileListFragment.java
src/com/owncloud/android/ui/helpers/FilesUploadHelper.java
src/com/owncloud/android/ui/preview/PreviewImageFragment.java

implements https://github.com/owncloud/android/issues/2135

Release v2.7.0

---

src/com/owncloud/android/authentication/AccountAuthenticator.java
src/com/owncloud/android/broadcastreceivers/ConnectivityActionReceiver.java
src/com/owncloud/android/features/FeatureList.java
src/com/owncloud/android/services/OperationsService.java
src/com/owncloud/android/ui/activity/Preferences.java

Remove unused methodes listed here:
https://github.com/owncloud/android/issues/2153

remove unused methodes

---

src/com/owncloud/android/ui/fragment/SearchShareesFragment.java

Implements #2111 by merging #2113

Hide soft keyboard

---

README.md

PR to update our README with the new beta channels

Include some instructions to join new beta channels

---

res/menu/main_menu.xml
res/values/strings.xml
src/com/owncloud/android/ui/activity/FileDisplayActivity.java
src/com/owncloud/android/utils/FileStorageUtils.java

This will add an option to have every sort type in an ascending or descending order.
____ 

add option for descending file sort order

---

res/layout/list_fragment.xml
res/layout/top_progress_bar.xml
src/com/owncloud/android/ui/activity/FileActivity.java
src/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
src/com/owncloud/android/ui/fragment/OCFileListFragment.java

Fixes #2104, merging code included in #2105 by @harshitbansal05

Fab snackbar bug

---

src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java

This also fixed a bug regarding the link password edit. There was a button with which you can toggle the password visibility. That button was not visible before due to a bug. Now it is.

refactor PublicShareDialogFragment

---

src/com/owncloud/android/ui/preview/PreviewVideoErrorAdapter.java

Code Putzen 2: refactor PreviewVideoErrorAdapter

---

src/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.java

Code Putzen: refactor ErrorMessageAdapter

---

res/layout/drawer.xml
res/values/strings.xml
src/com/owncloud/android/datamodel/UserProfile.java
src/com/owncloud/android/datamodel/UserProfilesRepository.java
src/com/owncloud/android/db/ProviderMeta.java
src/com/owncloud/android/operations/GetUserProfileOperation.java
src/com/owncloud/android/operations/RefreshFolderOperation.java
src/com/owncloud/android/providers/FileContentProvider.java
src/com/owncloud/android/ui/activity/DrawerActivity.java
src/com/owncloud/android/utils/DisplayUtils.java

Implements #2205 
Needs https://github.com/owncloud/android-library/pull/189

User quota

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
oc_jb_workaround/build.gradle
res/values/styles.xml

Implements #2109 
Needs https://github.com/owncloud/android-library/pull/188

Migrate gradle to 3.1.2 and include Java 8 support

---

CONTRIBUTING.md

It will include the changes added by @fuentesj11 in https://github.com/owncloud/android/pull/2166

Fix typo contribution

---

src/com/owncloud/android/utils/BitmapUtils.java

refactor BitmapUtils

---

res/values/strings.xml
src/com/owncloud/android/ui/activity/FileActivity.java
src/com/owncloud/android/ui/activity/FileDisplayActivity.java

fixes https://github.com/owncloud/android/issues/1825
____

fix block for deleted basic/oauth accounts

---

src/com/owncloud/android/ui/fragment/OCFileListFragment.java

This will disable Animations when phone is in power save mode.

add powersave mode to animations

---

src/com/owncloud/android/ui/activity/FileDisplayActivity.java

fixes https://github.com/owncloud/android/issues/2238#issuecomment-396660454

direcly show login screen on saml expiration

---

gradle/wrapper/gradle-wrapper.properties
src/com/owncloud/android/files/services/FileDownloader.java
src/com/owncloud/android/files/services/FileUploader.java

Fixes #2188 by merging the changes included in https://github.com/owncloud/android/pull/2196 by @mueller-ma

Set notification time on file upload and download

---

src/com/owncloud/android/operations/GetSharesForFileOperation.java
src/com/owncloud/android/ui/asynctasks/GetSharesForFileAsyncTask.java

Fix #2264 
Needs https://github.com/owncloud/android-library/pull/194

Show reshares

---

res/menu/file_actions_menu.xml
res/menu/main_menu.xml
res/values/strings.xml
src/com/owncloud/android/files/FileMenuFilter.java
src/com/owncloud/android/ui/activity/FileDisplayActivity.java
src/com/owncloud/android/ui/fragment/FileDetailFragment.java
src/com/owncloud/android/ui/fragment/OCFileListFragment.java
src/com/owncloud/android/ui/preview/PreviewAudioFragment.java
src/com/owncloud/android/ui/preview/PreviewImageFragment.java
src/com/owncloud/android/ui/preview/PreviewTextFragment.java
src/com/owncloud/android/ui/preview/PreviewVideoFragment.java

Select and deselect all functionality added

---

res/drawable/black_gradient.xml
res/drawable/shadow_gradient.xml
res/layout/files.xml
res/layout/files_folder_picker.xml
res/layout/top_progress_bar.xml
src/com/owncloud/android/ui/activity/FileDisplayActivity.java
src/com/owncloud/android/ui/activity/FolderPickerActivity.java
src/com/owncloud/android/ui/fragment/ExtendedListFragment.java
src/com/owncloud/android/ui/fragment/OCFileListFragment.java

Fix to Issue #2089 
_____
**BUGS & IMPROVEMENTS**

Gradient added in place of Progressbar when files not syncing

---

build.gradle
oc_jb_workaround/build.gradle
src/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.java

Implements #2322
Needs https://github.com/owncloud/android-library/pull/197

Fix crash when creating public link

---

THIRD_PARTY.txt
build.gradle

Complete: https://github.com/owncloud/android-library/issues/205
Needs: https://github.com/owncloud/android-library/pull/206

Delete jackrabbit dependencies and include OkHttp and Dav4Android ones

---

CHANGELOG.md
androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
androidTest/java/com/owncloud/android/authentication/SAMLAuthenticatorActivityTest.java
androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java
androidTest/java/com/owncloud/android/utils/AccountsManager.java
oc_jb_workaround/build.gradle
res/layout/files_folder_picker.xml
src/com/owncloud/android/broadcastreceivers/ConnectivityActionReceiver.java
src/com/owncloud/android/files/services/FileDownloader.java
src/com/owncloud/android/files/services/FileUploader.java
src/com/owncloud/android/files/services/RetryDownloadJobService.java
src/com/owncloud/android/files/services/RetryUploadJobService.java
src/com/owncloud/android/files/services/TransferRequester.java
src/com/owncloud/android/operations/RefreshFolderOperation.java
src/com/owncloud/android/operations/SynchronizeFileOperation.java
src/com/owncloud/android/operations/UploadFileOperation.java
src/com/owncloud/android/providers/DocumentsStorageProvider.java
src/com/owncloud/android/providers/FileContentProvider.java
src/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
src/com/owncloud/android/providers/cursors/FileCursor.java
src/com/owncloud/android/ui/activity/ManageSpaceActivity.java
src/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
src/com/owncloud/android/ui/activity/UploadListActivity.java
src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java
src/com/owncloud/android/ui/fragment/FileDetailFragment.java
src/com/owncloud/android/ui/preview/PreviewTextFragment.java
src/com/owncloud/android/ui/preview/PreviewVideoFragment.java
src/com/owncloud/android/utils/FileStorageUtils.java

Release 2.9.0

---

CHANGELOG.md
build.gradle
src/com/owncloud/android/authentication/AccountUtils.java
src/com/owncloud/android/authentication/AuthenticatorAsyncTask.java
src/com/owncloud/android/features/FeatureList.java
src/com/owncloud/android/operations/CheckCurrentCredentialsOperation.java
src/com/owncloud/android/operations/DetectAuthenticationMethodOperation.java
src/com/owncloud/android/operations/GetUserProfileOperation.java
src/com/owncloud/android/operations/RemoveShareOperation.java
src/com/owncloud/android/operations/SynchronizeFolderOperation.java
src/com/owncloud/android/operations/UploadFileOperation.java

Fixes https://github.com/owncloud/android/issues/2338 via https://github.com/owncloud/android/issues/2340
Needs https://github.com/owncloud/android-library/pull/210

Release 2.9.1

---

CHANGELOG.md
build.gradle
src/com/owncloud/android/features/FeatureList.java

Fixes #2347 via #2353
Needs https://github.com/owncloud/android-library/pull/213

Release 2.9.2

---

CHANGELOG.md
build.gradle
src/com/owncloud/android/features/FeatureList.java

Fixes owncloud/android#2365 via https://github.com/owncloud/android/issues/2364
Needs https://github.com/owncloud/android-library/pull/216

Release 2.9.3

---

AndroidManifest.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
oc_jb_workaround/AndroidManifest.xml
oc_jb_workaround/build.gradle

Needs https://github.com/owncloud/android-library/pull/198

Android Studio 3.2.1

---

docs/modules/ROOT/pages/release_notes.adoc

The information in this update is taken from #2268.

Update release notes for 2.8.0 build

---

src/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
src/com/owncloud/android/ui/adapter/ReceiveExternalFilesAdapter.java

Sorting options in sharing view

---

src/com/owncloud/android/authentication/AuthenticatorActivity.java

Fix a crash in AuthenticatorActivity

---

src/com/owncloud/android/authentication/AuthenticatorActivity.java

Log in button only enabled when credentials are typed only during basic auth

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java
owncloudApp/src/main/res/values/strings.xml

Warning to properly set camera folder when enabling camera uploads

---

owncloudApp/build.gradle
owncloudApp/src/main/AndroidManifest.xml
owncloudApp/src/main/java/com/owncloud/android/MainApp.java

and add VersionName to Log start
Now you have a variable `public static final String VERSION_NAME = "2.9.3"` everywhere access able.
Btw, I changed how it's stored now, and **not** the content and it's possible auto generation

rework VersionName/Code

---

build.gradle
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java

Let a click jump to Github commit
I split https://github.com/owncloud/android/pull/2391
Now you can see commit sha1 and a click opens the last changes

Show commit SHA1 in preferences

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/LogListAdapter.java
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
owncloudApp/src/main/java/com/owncloud/android/utils/DisplayUtils.java

Not so important, but someone has to start to improve code quality
eg:

remove some lints

---

CHANGELOG.md
owncloudApp/build.gradle

Implements https://github.com/owncloud/android/issues/2446

2.10.0 beta v1

---

owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
owncloudApp/src/main/java/com/owncloud/android/db/ProviderMeta.java
owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.java
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java

Implements https://github.com/owncloud/android/issues/2228
Needs https://github.com/owncloud/android-library/pull/237

Enforce password in public share dialog depending on new enforced_for

---

owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
owncloudApp/src/main/java/com/owncloud/android/db/ProviderMeta.java
owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.java
owncloudApp/src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/ShareUserListAdapter.java

Implements #2284 
Needs https://github.com/owncloud/android-library/pull/229

Show shareWithAdditionalInfo in shares autocompletion and list

---

owncloudApp/build.gradle
owncloudApp/src/androidTest/AndroidManifest.xml
owncloudApp/src/androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
owncloudApp/src/androidTest/java/com/owncloud/android/authentication/SAMLAuthenticatorActivityTest.java
owncloudApp/src/androidTest/java/com/owncloud/android/datamodel/OCFileUnitTest.java
owncloudApp/src/androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java
owncloudApp/src/androidTest/java/com/owncloud/android/uiautomator/InitialTest.java

Now it builds at least, but current situation is complete useless

make Espresso test at least build

---

owncloudApp/src/androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java

Clean up and removing some innecesary code.

Clean up espresso legacy public share tests

---

build.gradle

see what's changed https://androidstudio.googleblog.com/2019/03/android-studio-332-available.html

Android Studio 3.3.2

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java

Notch support

---

owncloudApp/src/main/res/layout/uploader_layout.xml

Fix to crash during creating new folder

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java

Fix and cleanup confirmation dialogs in settings

---

owncloudApp/src/main/java/com/owncloud/android/MainApp.java
owncloudApp/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
owncloudApp/src/main/java/com/owncloud/android/authentication/FingerprintManager.java
owncloudApp/src/main/java/com/owncloud/android/authentication/PassCodeManager.java
owncloudApp/src/main/java/com/owncloud/android/authentication/PatternManager.java
owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java
owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/PatternLockActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/DiskLruImageCache.java
owncloudApp/src/main/res/values/setup.xml
owncloudApp/src/main/res/values/strings.xml

Merge code included in https://github.com/owncloud/android/pull/2439
BUGS & IMPROVEMENT

Developer menu on version click

---

owncloudApp/src/main/res/menu/file_actions_menu.xml

Select all and select inverse removed from app bar

---

owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
owncloudApp/src/main/java/com/owncloud/android/providers/cursors/FileCursor.kt

Implements #2499 
____
Bugs & improvements

[Document Provider] Delete File/Folder

---

owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
owncloudApp/src/main/java/com/owncloud/android/providers/cursors/FileCursor.kt

Implements #2500 
___
Test Plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.11.0/2510-document_provider_create_folder.md
___

[Document Provider] Create Folder

---

owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java
owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
owncloudApp/src/main/java/com/owncloud/android/providers/cursors/FileCursor.kt
owncloudApp/src/main/java/com/owncloud/android/ui/notifications/NotificationUtils.java

Implements #2498 
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.11.0/2527-document_provider_edit_file.md

[Document Provider] Edit files and save changes

---

docs/modules/ROOT/pages/index.adoc

This PR adds a Table Of Contents to the documentation pages.
We did this in docs too, live example see: https://doc.owncloud.com/server/admin_manual/installation/system_requirements.html

Add TOC Table Of Contents

---

owncloudApp/build.gradle

Fixes #2481 
It needs https://github.com/owncloud/android-library/pull/248

Fix "Folder with brackets [ ] does not show the content"

---

owncloudApp/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RemoveAccountDialogFragment.java

Implements #2518 
____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.11.0/2528-document_provider_account_manager.md
bugs & improvements:

[Document Provider] Account management

---

.idea/codeStyles/Project.xml
owncloudApp/src/main/java/com/owncloud/android/operations/RenameFileOperation.java

From https://github.com/owncloud/android/pull/2432

Avoid NPE in RenameFileOperation on IOException

---

fastlane/metadata/android/de-DE/full_description.txt
fastlane/metadata/android/de-DE/short_description.txt
fastlane/metadata/android/en-US/full_description.txt

Merge #2488 developed by @mueller-ma

Use Play Store description for F-Droid

---

CHANGELOG.md
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/db/ProviderMeta.java
owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.java

Release 2.10.1

---

CHANGELOG.md
owncloudApp/build.gradle

Implements #2547 
It needs https://github.com/owncloud/android-library/pull/251

[Release] 2.11.0 beta v1

---

owncloudApp/src/main/java/com/owncloud/android/operations/RemoveChunksFolderOperation.java
owncloudApp/src/main/java/com/owncloud/android/operations/RemoveFileOperation.java
owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
owncloudApp/src/test/java/com/owncloud/android/utils/ErrorMessageAdapterUnitTest.java

Fix #2471 , code from https://github.com/owncloud/android/pull/2474

Fix batched permission errors

---

owncloudApp/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java

Clear successful / failed uploads bug fix

---

owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java

Fix just created folder dissapears when synchronizing parent folder

---

.idea/codeStyles/Project.xml

File  `Projects.xml` needed to get correct styling in the project. Recently added to `master` but also needed in `new_arch` after latest Android Studio updates

Add Projects.xml to new_arch

---

owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java

Fix crash when notifying upload result

---

CHANGELOG.md
owncloudApp/build.gradle

Release 2.11.1

---

owncloudApp/src/main/res/layout/share_file_layout.xml

Implements https://github.com/owncloud/android/issues/2581

Release 2.11.1 oem

---

owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/PublicShareDialogFragment.kt

Fixes https://github.com/owncloud/android/issues/2567

Fix glitch when editing folder permissions in public links

---

owncloudApp/src/androidTest/java/com/owncloud/android/shares/domain/publicShares/EditPublicShareTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/shares/presentation/ui/ShareFileFragmentTest.kt
owncloudApp/src/main/java/com/owncloud/android/files/FileMenuFilter.java
owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/ShareFileFragment.kt
owncloudApp/src/main/res/layout/edit_share_layout.xml
owncloudApp/src/main/res/layout/share_file_layout.xml
owncloudApp/src/test-common/java/com/owncloud/android/utils/TestUtil.kt

Fixes #2598 
QA:
https://github.com/owncloud/android/pull/2617#issuecomment-518213737

Fix private link not accessible when disabling share API

---

CHANGELOG.md
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt

Implements #2621 
Needs https://github.com/owncloud/android-library/pull/256

[Release] 2.12 beta 1

---

CHANGELOG.md
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt

Implements https://github.com/owncloud/android/issues/2611
Needs https://github.com/owncloud/android-library/pull/258

[Release] 2.12

---

owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/ShareFileFragment.kt

[Release] 2.12 oem

---

owncloudApp/src/main/java/com/owncloud/android/AppRater.java
owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java
owncloudApp/src/main/java/com/owncloud/android/files/services/RetryDownloadJobService.java
owncloudApp/src/main/java/com/owncloud/android/files/services/TransferRequester.java
owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RateMeDialog.java

Implements https://github.com/owncloud/android/issues/2620

Include more logs to enhance the way of reproducing some issues

---

.idea/codeStyles/Project.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/sharees/presentation/SearchShareesFragment.kt
owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/EditPrivateShareFragment.kt
owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/PublicShareDialogFragment.kt
owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/ShareFileFragment.kt

Simply bring library up to date with
* most recent stable Android Studio
* most recent stable Kotlin
* update libraries
* fix resulting compile errors

Android Studio 3.5.0

---

.github/ISSUE_TEMPLATE/release_template.md
CHANGELOG.md
owncloudApp/build.gradle

Implements owncloud/android#2645
It needs https://github.com/owncloud/android-library/pull/267

[Release] 2.13

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PrepareVideoPlayerAsyncTask.java
owncloudApp/src/main/res/values/strings.xml

Improve oAuth flow UX and wording when token expires or becomes invalid

---

.idea/codeStyles/Project.xml

After a longer break I looked in the code and observed after code formating the line wrap is still 100, but we already agreed to 120 https://github.com/owncloud/android/pull/2447#discussion_r259716269
This PR fulfills this.
(just for completeness: my wish is 150)

line wrap after 120

---

build.gradle

I simply don't like the update suggestion dialog in Android Studio, so lets keep up to date with most recent version

Android Studio 3.5.1 and ktx

---

docs/yarn.lock

@tboerger @settermjd it seems there's a security alert in this docs dependency, can you review it? Thanks

Update handlebars version

---

owncloudApp/src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
owncloudApp/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FilesUploadHelper.java
owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java

Implements #1334
To merge #1369

Sort by date mixing files and folders

---

owncloudApp/src/main/java/com/owncloud/android/extensions/ThrowableExt.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/providers/sharing/UsersAndGroupsSearchProvider.kt
owncloudApp/src/main/res/values/strings.xml

Fix bugs reported in https://github.com/owncloud/android/pull/2708#issuecomment-555965962

[New arch] Some bug fixing (error handling)

---

owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java

Sort by size mixing files and folders

---

owncloudApp/src/main/java/com/owncloud/android/MainApp.kt

I found `MainApp` logging needs an update now.

MainApp logging

---

owncloudApp/src/main/java/com/owncloud/android/MainApp.kt

No need fom `Timber.plant(DebugTree(Log_OC::class.java))`
because
`Timber.plant(FileLoggingTree(...))`
is enough

remove twice log

---

.github/ISSUE_TEMPLATE/release_template.md

Contribution by @mueller-ma 
To merge https://github.com/owncloud/android/pull/2744

Update summary of "Release" issue template

---

CHANGELOG.md
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/authentication/AccountUtils.java
owncloudApp/src/main/java/com/owncloud/android/features/FeatureList.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java

Implements https://github.com/owncloud/android/issues/2765
It needs https://github.com/owncloud/android-library/pull/290

Release 2.14.1

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
owncloudApp/build.gradle

(cherry picked from commit e6d9b72a2b4840c3b549c62649e2a2b5dcdc16d6)

Android Studio 3.5.3

---

owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
owncloudApp/src/main/java/com/owncloud/android/services/SyncFolderHandler.java

Remove a potential crash

---

owncloudApp/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.java

Fix crash when trying to connect to self signed certificate

---

gradle/wrapper/gradle-wrapper.properties
owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
owncloudApp/src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java
owncloudApp/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt
owncloudApp/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
owncloudApp/src/main/java/com/owncloud/android/media/MediaServiceBinder.java
owncloudApp/src/main/java/com/owncloud/android/operations/CopyFileOperation.java
owncloudApp/src/main/java/com/owncloud/android/operations/MoveFileOperation.java
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/ShareFileFragment.kt
owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/CertificateCombinedExceptionViewAdapter.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/DiskLruImageCache.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/SslCertificateViewAdapter.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/SslErrorViewAdapter.java
owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RemoveShareDialogFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PrepareVideoPlayerAsyncTask.java
owncloudApp/src/main/java/com/owncloud/android/widgets/ActionEditText.java
tests/src/com/owncloud/android/test/FileContentProviderTest.java

Continuation of #2770 suggested in https://github.com/owncloud/android-library/pull/293#issuecomment-574991808
Needs https://github.com/owncloud/android-library/pull/297

Use timber instead of printstacktrace

---

owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
owncloudApp/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
owncloudApp/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/RemoteDataSourceModule.kt
owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java
owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java
owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
owncloudApp/src/main/java/com/owncloud/android/services/SyncFolderHandler.java
owncloudApp/src/main/java/com/owncloud/android/syncadapter/AbstractOwnCloudSyncAdapter.java

Implements https://github.com/owncloud/android/issues/2805
Needs https://github.com/owncloud/android-library/pull/301

Fix multiaccount with OAuth does not work + Owncloud Client factories cleanup

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/FileListListAdapter.java
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java

Fixes https://github.com/owncloud/android/issues/2799

Fix crash when moving/copying files to a folder and select a file

---

owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/29.json
owncloudData/src/androidTest/java/com/owncloud/android/data/roommigrations/MigrationTest.kt
owncloudData/src/androidTest/java/com/owncloud/android/data/roommigrations/MigrationToDB28.kt
owncloudData/src/androidTest/java/com/owncloud/android/data/roommigrations/MigrationToDB29.kt
owncloudData/src/main/java/com/owncloud/android/data/OwncloudDatabase.kt
owncloudData/src/main/java/com/owncloud/android/data/ProviderMeta.java
owncloudData/src/main/java/com/owncloud/android/data/sharing/shares/db/OCShareEntity.kt
owncloudData/src/test/java/com/owncloud/android/data/shares/db/OCShareEntityTest.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/shares/model/OCShare.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/shares/model/OCShareTest.kt
owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCShare.kt

Implements (Point 2) https://github.com/owncloud/android/issues/2787
Needs: https://github.com/owncloud/android-library/pull/312

Parse file and item source as string

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java

Fix npe when rotating folder picker activity

---

build.gradle

Library: https://github.com/owncloud/android-library/pull/317

Update Android Studio to 3.6.3

---

owncloudData/src/main/java/com/owncloud/android/data/migrations/Migration_28.kt
owncloudData/src/main/java/com/owncloud/android/data/migrations/Migration_29.kt

Implement #2716 
Needs https://github.com/owncloud/android-library/pull/298

Use moshi to parse capabilities (Library Update)

---

CHANGELOG.md
owncloudApp/build.gradle

Implements #2843 
Needs https://github.com/owncloud/android-library/pull/316

[Release] 2.15 beta 1

---

owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/sharing/SharePublicLinkListAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/sharing/ShareUserListAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/ShareFileFragment.kt
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/authentication/OCAuthenticationViewModelTest.kt
owncloudData/src/main/java/com/owncloud/android/data/capabilities/db/OCCapabilityEntity.kt
owncloudData/src/test/java/com/owncloud/android/data/server/datasources/OCRemoteServerInfoDataSourceTest.kt
owncloudData/src/test/java/com/owncloud/android/data/shares/datasources/OCLocalShareDataSourceTest.kt
owncloudDomain/build.gradle
owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/shares/model/OCShare.kt

Add some pending tests related with #2827

Add some pending tests and general updates

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

(cherry picked from commit 2f90aa81f4a07774b2e9e9afb2131403fd58b6a8)
Library: https://github.com/owncloud/android-library/pull/322

Android Studio 4.0

---

build.gradle
owncloudApp/src/main/AndroidManifest.xml
owncloudApp/src/main/java/com/owncloud/android/authentication/oauth/OAuthConnectionBuilder.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/providers/sharing/UsersAndGroupsSearchProvider.kt
owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt

Implements: #2576 
Needs: https://github.com/owncloud/android-library/pull/325

Upgrade target to v29 (Android 10)

---

owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineHandler.java
owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java
owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java

Fix #2896 
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.15.1/2908_avOfflineRegression.md

Fix iae in FileDataStorageManager constructor

---

owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java
owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java
owncloudApp/src/main/java/com/owncloud/android/operations/ChunkedUploadFileOperation.java
owncloudData/src/androidTest/java/com/owncloud/android/data/authentication/datasources/implementation/OCLocalAuthenticationDataSourceTest.kt
owncloudData/src/main/java/com/owncloud/android/data/authentication/datasources/implementation/OCLocalAuthenticationDataSource.kt

Fixes #2906 
Needs https://github.com/owncloud/android-library/pull/331

[Fix] Refresh credentials

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java

It's not a big deal, it's just to simplify version name display to a single line. Additional it adds `versionCode` as well

Simplify version name display

---

THIRD_PARTY.txt
owncloudApp/src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java

Implements
App: #2862 
Lib: https://github.com/owncloud/android-library/pull/280
Needs: https://github.com/owncloud/android-library/pull/328

Update network library (Okhttp 4.6.0)

---

owncloudData/src/main/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSource.kt
owncloudData/src/test/java/com/owncloud/android/data/server/datasources/OCRemoteServerInfoDataSourceTest.kt

Implements: https://github.com/owncloud/android/issues/2915
Needs: https://github.com/owncloud/android-library/pull/334

Support for version hide config

---

build.gradle

Update Android Studio to [last current version](https://developer.android.com/studio/releases): 4.0.1
Needs https://github.com/owncloud/android-library/pull/337

Android Studio 4.0.1

---

CHANGELOG.md
THIRD_PARTY.txt
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/PublicShareDialogFragment.kt
owncloudApp/src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
owncloudData/src/main/java/com/owncloud/android/data/authentication/datasources/implementation/OCRemoteAuthenticationDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSource.kt
owncloudData/src/test/java/com/owncloud/android/data/server/datasources/OCRemoteServerInfoDataSourceTest.kt

Implements #2903 
Needs https://github.com/owncloud/android-library/pull/333
Regression test:
BUGS & IMPROVEMENTS:

[Release] 2.15.1

---

owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsPrivacyPolicyTest.kt

Reduce matchers to fit the new privacy policy web. Matching main div and text of the title inside

Fix privacy policy ui test after changes in web UI

---

owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java
owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java

Fixes: https://github.com/owncloud/android/issues/2939

Fix crash when notifying download result

---

owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java

Avoid iae when synchonizing av. offline files

---

owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt
owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/32.json
owncloudData/src/main/java/com/owncloud/android/data/OwncloudDatabase.kt
owncloudData/src/main/java/com/owncloud/android/data/ProviderMeta.java
owncloudData/src/main/java/com/owncloud/android/data/migrations/Migration_32.kt

Fixes https://github.com/owncloud/android/issues/2937

Handle migration properly and drop old database tables

---

CHANGELOG.md
owncloudApp/build.gradle

Implements: #2945 
Needs: https://github.com/owncloud/android-library/pull/340

[Release] 2.15.2

---

.idea/codeStyles/Project.xml

Here it is on upstream repo https://github.com/owncloud/android/pull/2960#issuecomment-691011263

Update code style

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/RemoteDataSourceModule.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/RepositoryModule.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/33.json
owncloudData/src/main/java/com/owncloud/android/data/OwncloudDatabase.kt
owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt
owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt
owncloudData/src/main/java/com/owncloud/android/data/migrations/Migration_33.kt
owncloudData/src/test/java/com/owncloud/android/data/file/datasource/OCLocalFileDataSourceTest.kt
owncloudData/src/test/java/com/owncloud/android/data/file/repository/OCFileRepositoryTest.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetFileByIdUseCase.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetFileByRemotePathUseCase.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/GetFileByIdUseCaseTest.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/GetFileByRemotePathUseCaseTest.kt

[New arch] Get file by path or id

---

docs/package.json
docs/yarn.lock

Updated dependencies for documentation to get rid of the security alerts.

[Docs-only] update dependencies for the documentation

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/faq.adoc

- FAQ page added
```
git clone https://github.com/owncloud/android.git
cd android
git checkout docs/faq
cd docs
yarn install
yarn antora
yarn serve
```
Test http://localhost:8080/android/faq.html

[Docs] Add FAQ

---

CHANGELOG.md
owncloudApp/build.gradle

Implements https://github.com/owncloud/android/issues/2963
Needs https://github.com/owncloud/android-library/pull/346

[Release] 2.15.3

---

owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java

Fixes https://github.com/owncloud/android/issues/2984

fix error on empty mimetype returned on propfind

---

THIRD_PARTY.txt
build.gradle
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
owncloudApp/src/main/res/layout-land/account_setup.xml
owncloudApp/src/main/res/layout/account_setup.xml
owncloudApp/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
owncloudData/build.gradle
owncloudDomain/build.gradle
owncloudTestUtil/build.gradle

Update some dependencies and perform a little cleanup over build gradles.
Update Android Studio version to 4.1
Needs https://github.com/owncloud/android-library/pull/351

Update dependencies and perform a little cleanup

---

docs/modules/ROOT/pages/troubleshooting.adoc
owncloudApp/src/androidTest/java/com/owncloud/android/settings/camerauploads/OCSettingsCameraUploadsTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/settings/logs/OCSettingsLogTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/settings/logs/OCSettingsLogsTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsMoreTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsSecurityTest.kt
owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
owncloudApp/src/main/java/com/owncloud/android/db/PreferenceManager.java
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/CommonModule.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/LocalDataSourceModule.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/RemoteDataSourceModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
owncloudApp/src/main/java/com/owncloud/android/providers/LogsProvider.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/main/res/xml/preferences.xml
owncloudData/src/androidTest/java/com/owncloud/android/data/authentication/datasources/implementation/OCLocalAuthenticationDataSourceTest.kt
owncloudData/src/main/java/com/owncloud/android/data/ClientManager.kt
owncloudData/src/main/java/com/owncloud/android/data/authentication/datasources/implementation/OCLocalAuthenticationDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/preferences/datasources/SharedPreferencesProvider.kt
owncloudData/src/main/java/com/owncloud/android/data/preferences/datasources/implementation/SharedPreferencesProviderImpl.kt

Implements https://github.com/owncloud/android/issues/2887
Needs https://github.com/owncloud/android-library/pull/345
____
QA
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.16/2981-logging_network.md
BUGS & IMPROVEMENTS:

Log network calls

---

.github/ISSUE_TEMPLATE/release_template.md

Update release template. Reorder, improve and add new tasks.
Two new tasks: 
- Publish a new release in https://github.com/owncloud/android/releases
- Update readme, if needed (Update screenshots with new designs).

Update release template

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/RemoteDataSourceModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/providers/sharing/UsersAndGroupsSearchProvider.kt
owncloudData/src/main/java/com/owncloud/android/data/sharing/sharees/datasources/RemoteShareeDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/sharing/sharees/datasources/implementation/OCRemoteShareeDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/sharing/sharees/datasources/mapper/RemoteShareeMapper.kt
owncloudData/src/main/java/com/owncloud/android/data/sharing/sharees/repository/OCShareeRepository.kt
owncloudData/src/test/java/com/owncloud/android/data/sharees/datasources/OCRemoteShareesDataSourceTest.kt
owncloudData/src/test/java/com/owncloud/android/data/shares/datasources/OCRemoteShareesDataSourceTest.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/sharees/GetShareesAsyncUseCase.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/sharees/ShareeRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/sharees/model/OCSharee.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/shares/model/OCShare.kt

related Issue: https://github.com/owncloud/android/issues/2704
related lib pr: https://github.com/owncloud/android-library/pull/352
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.16/2994-sharees_moshi.md

[New arch] Use moshi to parse sharees

---

docs/modules/ROOT/pages/troubleshooting.adoc
owncloudApp/src/main/res/values/strings.xml

From https://github.com/owncloud/android/pull/3010

Smirta fixes on docs: contain instead of include

---

owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/EditPrivateShareFragmentTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/TestShareFileActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/EditPrivateShareFragment.kt
owncloudApp/src/main/res/layout/edit_share_layout.xml

Add close button to edit private share view

---

owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java

Fix crash when uploading files with null account

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java

Fix crash when closing search view

---

build.gradle

Update kotlin plugin to 1.4.20
Library: https://github.com/owncloud/android-library/pull/360

Android Studio 4.1.1

---

owncloudApp/src/androidTest/java/com/owncloud/android/settings/logs/OCSettingsLogsTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsMoreTest.kt

Ignore temporary some CI-flaky tests from Settings view

Ignore temporary some CI-flaky tests

---

owncloudApp/src/main/java/com/owncloud/android/db/PreferenceManager.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java

It's not always smart to have a constant twice defined

Harmonize constants

---

owncloudApp/src/main/res/layout/sort_options_layout.xml

Implements https://github.com/owncloud/android/issues/3057

[Release] 2.16 oem

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Bump kotlinVersion from 1.4.20 to 1.4.30
Library: https://github.com/owncloud/android-library/pull/370

Bump kotlinVersion from 1.4.20 to 1.4.30

---

owncloudApp/src/main/java/com/owncloud/android/ui/preview/ViewPagerWorkAround.kt
owncloudApp/src/main/res/layout/preview_image_activity.xml

Fix ViewPager crash

---

owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/FileListListAdapter.java
owncloudApp/src/main/java/com/owncloud/android/ui/preview/ViewPagerWorkAround.kt

Implements #2927 
____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.17/3105-all_file_thumbnails.md

Request thumbnails for every file type

---

owncloudApp/src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
owncloudData/src/main/java/com/owncloud/android/data/oauth/datasource/impl/RemoteOAuthDataSourceImpl.kt
owncloudData/src/test/java/com/owncloud/android/data/oauth/RemoteOAuthUtils.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/authentication/oauth/model/OIDCServerConfiguration.kt
owncloudTestUtil/src/main/java/com/owncloud/android/testutil/oauth/ClientRegistrationRequest.kt
owncloudTestUtil/src/main/java/com/owncloud/android/testutil/oauth/OIDCServerConfiguration.kt

Replace underscores with camelCase following [kotlin naming convention](https://kotlinlang.org/docs/coding-conventions.html#function-names)

Kotlinize naming

---

owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.java

Fix glitch showing lens icon in music player

---

owncloudApp/src/main/java/com/owncloud/android/authentication/AccountUtils.java
owncloudApp/src/main/java/com/owncloud/android/operations/SyncCapabilitiesOperation.java
owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
owncloudData/src/main/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSource.kt
owncloudData/src/test/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSourceTest.kt

Continuation https://github.com/owncloud/android/pull/2970
Needs owncloud/android-library#368

[Fix] Cookie handling

---

CHANGELOG.md
owncloudApp/build.gradle
owncloudApp/src/main/res/values/strings.xml

Implements https://github.com/owncloud/android/issues/3132
Needs https://github.com/owncloud/android-library/pull/376

[Release] 2.17 beta 1

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/ReceiveExternalFilesAdapter.java

fix for https://github.com/owncloud/android/issues/3041

fix scroll jump on share to directory

---

build.gradle

Library: https://github.com/owncloud/android-library/pull/384

Bump gradle version to 1.4.3

---

owncloudApp/src/main/AndroidManifest.xml

From https://github.com/owncloud/android/pull/3156

add the android.permission.REQUEST_INSTALL_PACKAGES permission

---

.github/pull_request_template.md
.github/workflows/calens.yml
CHANGELOG.md
changelog/CHANGELOG.tmpl
changelog/README.md
changelog/TEMPLATE.md
changelog/unreleased/3162

Implements #3124 
We will use Calens to automatically generate the changelog starting from v2.18

[Feature] Calens changelog

---

build.gradle
owncloudData/build.gradle
owncloudDomain/build.gradle

Implements and fixes #3152 
_____

Bump mockk version to 1.11.0

---

CHANGELOG.md
changelog/unreleased/3162
changelog/unreleased/3177
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.java

Do not show sync option in audio preview.

---

.github/ISSUE_TEMPLATE/release_template.md
.github/pull_request_template.md

Update release template with some steps needed to autogenerate the changelog.
Update PR template because some options are not needed anymore

Update some templates with calens steps

---

build.gradle

Bump kotlin version and update library reference.
Library PR (if needed): https://github.com/owncloud/android-library/pull/388

Bump kotlin version

---

owncloudApp/src/main/AndroidManifest.xml

It formats manifest and fixes 
There are no logic changes at all

Format manifest and fix empty body

---

.editorconfig
build.gradle
owncloudApp/src/androidTest/java/com/owncloud/android/settings/logs/OCSettingsLogsTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsMoreTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/EditPrivateShareFragmentTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/ShareFileFragmentTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/utils/matchers/MatcherExt.kt
owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/LocalDataSourceModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/AuthenticatorConstants.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortOptionsView.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/EditPrivateShareFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/drawer/DrawerViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/providers/ContextProvider.kt
owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt
owncloudApp/src/main/java/com/owncloud/android/providers/OCContextProvider.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.kt
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/ViewModelTest.kt
owncloudData/src/main/java/com/owncloud/android/data/RemoteOperationHandler.kt
owncloudData/src/main/java/com/owncloud/android/data/sharing/shares/db/OCShareEntity.kt
owncloudData/src/test/java/com/owncloud/android/data/user/datasources/OCLocalUserDataSourceTest.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/authentication/oauth/OIDCDiscoveryUseCaseTest.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/authentication/usecases/LoginBasicAsyncUseCaseTest.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/server/usecases/GetServerInfoAsyncUseCaseTest.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/user/usecases/GetStoredQuotaUseCaseTest.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/user/usecases/GetUserAvatarAsyncUseCaseTest.kt

You can run int on CI with `./gradlew ktLintCheck`
The fine tuning in file `.editorconfig` is up to you. I added some super annoying exception of strict rules, adding more or less is up to you.
Btw, in current state you have to fix some files.
Library: https://github.com/owncloud/android-library/pull/390

Introduce ktLint

---

CHANGELOG.md
changelog/unreleased/3184
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
owncloudApp/src/main/res/layout/nav_main_container.xml

issue: https://github.com/owncloud/android/issues/3139

fix navbar is vissible in filepreview after rotation

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/sharing/SharePublicLinkListAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/common/BottomSheetFragmentItemView.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortBottomSheetFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortOptionsView.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortType.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/EditPrivateShareFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/PublicShareDialogFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/SearchShareesFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/ShareFileFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileListOption.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
owncloudApp/src/main/res/layout/activity_main.xml
owncloudDomain/build.gradle
owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/shares/model/OCShare.kt
owncloudTestUtil/build.gradle

Let's move to ViewBinding.
App: #3028 
_____

Replace kotlin android extensions

---

build.gradle
owncloudApp/build.gradle

Bump room and exoplayer to the latest version

Bump room and exoplayer dependencies

---

CHANGELOG.md
changelog/README.md
changelog/unreleased/3143

App: https://github.com/owncloud/android/issues/2867 (adding the changelog for this epic)

[Feature] AndroidX settings and new structure changelog

---

CHANGELOG.md
changelog/unreleased/3210
owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPasscodeTest.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
owncloudApp/src/main/res/layout/passcodelock.xml

App: fixes https://github.com/owncloud/android/issues/2722
_____
Checks: https://github.com/owncloud/android/pull/3210#issuecomment-829191968

[FIX] Snackbar in passcode view is not displayed

---

owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
owncloudData/src/main/java/com/owncloud/android/data/LocalStorageProvider.kt

Introduction of LocalStorageProvider in data module. It will help us to continue with [synchronization milestone](https://github.com/owncloud/android/milestone/43)
_____

Use new local storage provider to get storage paths

---

owncloudApp/src/main/res/values/setup.xml

Replace old links for new ones in "new to ownCloud" and help

---

CHANGELOG.md
owncloudApp/src/main/res/values/strings.xml

Introduce some strings that will be included in the wizard for the 2.18 release. This way, we can receive some translations on time.
App: #3197

Introduce new wizard wording

---

owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/ErrorsWhileCopyingHandlerActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RateMeDialog.java

App: https://github.com/owncloud/android/issues/3138
_____

[Feature] Use new extensions in the whole project

---

CHANGELOG.md
changelog/unreleased/3220
owncloudApp/src/main/java/com/owncloud/android/operations/ChunkedUploadFileOperation.java

Fix xodo sync bug.
Issue: owncloud/android#2752
Library PR: https://github.com/owncloud/android-library/pull/396

fix xodo file sync bug

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java

App: https://github.com/owncloud/android/issues/3239
_____

Fix crash when sharing with ownCloud

---

owncloudApp/src/main/res/values/strings.xml

Add wording for wizard 2.18

---

owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/PrivacyPolicyActivityTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPasscodeTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/SettingsSecurityFragmentTest.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsLogsViewModelTest.kt
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsMoreViewModelTest.kt
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModelTest.kt

After adding ktLint, some errors appeared. This PR fixes them.
BTW, added a step in bitrise to check them from now on.

Fix some ktlint errors

---

README.md

Fix - stable branch badge from bitrise with bad token

---

build.gradle

It's only to remove noise.
When it builds, you can merge it. No tests are required

Remove one jcenter()

---

build.gradle
owncloudData/build.gradle

Bump kotlin version, AS, and replace a legacy room dependency.
Library PR (if needed): https://github.com/owncloud/android-library/pull/409
_____

Bump some dependencies

---

build.gradle

App: https://github.com/owncloud/android/issues/2974
_____

Add set up for local execution of sonarcloud

---

build.gradle

Bump kotlin and kotlin gradle
Library PR (if needed): https://github.com/owncloud/android-library/pull/415

Bump kotlin to 1.5.20

---

changelog/unreleased/3296
owncloudApp/src/androidTest/java/com/owncloud/android/settings/SettingsFragmentTest.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsMoreViewModel.kt

Hide more section when everything is disabled and update tests

---

owncloudApp/build.gradle

It's about to build with an aarch64 Android Studio https://stackoverflow.com/a/68285501/1079990

Fix build with aarch64 Studio on Apple Silicon M1

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PrepareVideoPlayerAsyncTask.java
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFragment.java

Bump ExoPlayer to 2.14.1.
_____

Bump ExoPlayer to 2.14.1

---

.github/workflows/calens.yml
CHANGELOG.md
owncloudApp/src/androidTest/java/com/owncloud/android/authentication/LoginActivityTest.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
owncloudApp/src/main/res/values/setup.xml

Added a new option to make the welcome text brandable
_____

Welcome text brandable

---

owncloudApp/src/main/res/values/strings.xml

Add wizard strings for 2.18.1

---

CHANGELOG.md
changelog/unreleased/3336
owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
owncloudData/src/main/java/com/owncloud/android/data/storage/LocalStorageProvider.kt

Related issue: https://github.com/owncloud/android/issues/125
Bugs & reports

clean old user directories

---

CHANGELOG.md
changelog/unreleased/3337
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsLogsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsLogsViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/providers/WorkManagerProvider.kt
owncloudApp/src/main/java/com/owncloud/android/utils/DateUtils.java
owncloudApp/src/main/java/com/owncloud/android/workers/OldLogsCollectorWorker.kt
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsLogsViewModelTest.kt
owncloudData/src/main/java/com/owncloud/android/data/storage/LocalStorageProvider.kt

[Feature] Old logs collector

---

.idea/codeStyles/Project.xml
owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/FileListListAdapter.java
owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt
owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt
owncloudData/src/test/java/com/owncloud/android/data/file/repository/OCFileRepositoryTest.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetFilesSharedByLinkUseCase.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/GetFilesSharedByLinkUseCaseTest.kt
owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCFile.kt

App: https://github.com/owncloud/android/issues/3355
_____

[New arch] Shared by link

---

owncloudApp/src/main/res/layout/passcode_edit_text.xml

shorten length of edit text on longher pin code input

---

CHANGELOG.md
changelog/unreleased/3365
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeActivity.kt

App: https://github.com/owncloud/android/issues/3342
_____

[FIX] Passcode input misbehaving

---

CHANGELOG.md
changelog/unreleased/3363
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/LogHistoryActivity.kt

App: https://github.com/owncloud/android/issues/3357
_____

[FIX] Lack of "Back" button in Logs view 

---

CHANGELOG.md
changelog/unreleased/3383
owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java

[FIX] Reported crash in FileDataStorageManager

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoErrorAdapter.java
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFragment.java

[FIX] Bump exoplayer from 2.14.2 to 2.15.0

---

owncloudApp/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
owncloudData/src/test/java/com/owncloud/android/data/shares/datasources/OCRemoteShareDataSourceTest.kt

App: #3097 
Library PR (if needed): https://github.com/owncloud/android-library/pull/430
_____
[Test report](https://github.com/owncloud/android/files/7215781/serenity_moshi.zip)

[FEATURE REQUEST] Use Moshi to parse shares

---

owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPasscodeTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/PassCodeActivityTest.kt
owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/SettingsSecurityFragmentTest.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeManager.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/security/PassCodeViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/providers/ContextProvider.kt
owncloudApp/src/main/java/com/owncloud/android/providers/OCContextProvider.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/BiometricActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
owncloudApp/src/main/res/values/setup.xml
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/security/PassCodeViewModelTest.kt
owncloudTestUtil/src/main/java/com/owncloud/android/testutil/security/PassCodeUtils.kt
owncloudTestUtil/src/main/java/com/owncloud/android/testutil/security/PatternUtils.kt

App: https://github.com/owncloud/android/issues/3358
_____

[FEATURE REQUEST] Passcode digits brandable

---

owncloudApp/build.gradle
owncloudApp/src/main/res/values/setup.xml

[Release] 2.18.2

---

CHANGELOG.md
changelog/unreleased/3396
owncloudApp/build.gradle

App: #3397 
Library PR (if needed): https://github.com/owncloud/android-library/pull/440
_____
QA checks: https://github.com/owncloud/android/pull/3433#issuecomment-959773309

[Release] 2.19 beta 1

---

owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/observers/EmptyDataObserver.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/res/layout/item_empty_dataset.xml
owncloudApp/src/main/res/layout/main_file_list_fragment.xml
owncloudApp/src/main/res/values/strings.xml

New arch/empty folder

---

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/GetFilesAvailableOfflineUseCaseTest.kt
owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCFile.kt

New arch/bottom nav bar

---

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/SecurityUtils.kt

App: https://github.com/owncloud/android/issues/3458
_____

[FIX] Rotation triggers security lock

---

CHANGELOG.md
changelog/unreleased/3463
owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/PassCodeActivityTest.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/SecurityUtils.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsSecurityFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/security/PassCodeViewModel.kt
owncloudApp/src/main/res/layout/passcodelock.xml
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/security/PassCodeViewModelTest.kt

App: https://github.com/owncloud/android/issues/3320
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.20/3463-brute_force_protection.md

[FEATURE REQUEST] Brute force protection

---

gradle/wrapper/gradle-wrapper.properties

Bump gradle version to 7.3.3
https://github.com/gradle/gradle/releases/tag/v7.3.3

Bump gradle to 7.3.3

---

build.gradle

Kotlin 1.6.10 -> https://github.com/JetBrains/kotlin/releases/tag/v1.6.0
Library: https://github.com/owncloud/android-library/pull/460

Bump kotlin version to 1.6.10

---

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt
owncloudApp/src/main/res/layout/main_file_list_fragment.xml

New arch/fab handling

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt
owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/model/FileListOption.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetFilteredFolderContentUseCase.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetSearchFolderContentUseCase.kt

New arch/search inside folder

---

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt

Show propertly footer on grid mode after searching

---

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt

New arch/navigation

---

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt

Displayed the correct list when the user navigates through the bottom nav bar.

---

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt

Status of Navigation Drawer controlled when multiselection is enabled or disabled

---

owncloudData/build.gradle
owncloudDomain/build.gradle

Remove pointless libs dependencies

---

CHANGELOG.md
changelog/unreleased/3527
owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
owncloudData/src/main/java/com/owncloud/android/data/preferences/datasources/SharedPreferencesProvider.kt
owncloudData/src/main/java/com/owncloud/android/data/preferences/datasources/implementation/SharedPreferencesProviderImpl.kt

App: https://github.com/owncloud/android/issues/3526
_____
Checks done: https://github.com/owncloud/android/pull/3527#issuecomment-1026797638

Enable logs by default in debug builds

---

owncloudApp/src/main/java/com/owncloud/android/presentation/manager/AvatarManager.kt

Prevent a crash when logging in. This crash does not happen in the 2.19 version
_____

Prevent a crash when logging in

---

owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java
owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/DiskLruImageCache.java

This
`if (MainApp.Companion.getEnabledLogging()) {`
makes not that much sense here

Remove pointless debug condition

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/SelectableAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/files/FilesViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/UploadPathActivity.java

New arch/multiselecton menu options

---

owncloudApp/src/main/res/values-fr/strings.xml

App: https://github.com/owncloud/android/issues/3534 
_____

Add "many" entry to french translation about number of selected items

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt

Manage click on files (not folders) to download them implemented

Manage click on files (not folders) to download them implemented

---

.github/ISSUE_TEMPLATE/release_template.md

A little typo has been fixed in the template, the category, and the tag were incorrect.

Fixed template's typo.

---

CHANGELOG.md
changelog/unreleased/3480
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/main/res/values/strings__not_to_translate.xml
owncloudData/src/main/java/com/owncloud/android/data/preferences/datasources/SharedPreferencesProvider.kt
owncloudData/src/main/java/com/owncloud/android/data/preferences/datasources/implementation/SharedPreferencesProviderImpl.kt

App: https://github.com/owncloud/android/issues/3420
_____

[MDM] Provide app feedback to MDM admins

---

CHANGELOG.md
changelog/unreleased/3440
owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/SettingsSecurityFragmentTest.kt
owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/SecurityUtils.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsSecurityFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/res/values/setup.xml
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModelTest.kt

App: #3440 
_____
QA checks: https://github.com/owncloud/android/pull/3547#issuecomment-1044450523

Implemented lock delay enforced

---

.github/ISSUE_TEMPLATE/release_template.md

A small change in the steps of the process of a new release

Reorganized template's order.

---

CHANGELOG.md
changelog/unreleased/3560
owncloudApp/src/main/java/com/owncloud/android/MainApp.kt

App: https://github.com/owncloud/android/issues/3468
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.20/3560-security_flags.md
Reports:

[FIX] Security flags for screen recording

---

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/migration/StorageMigrationActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsPictureUploadsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsVideoUploadsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/ShareActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/EditPrivateShareFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/PublicShareDialogFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/SearchShareesFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/ShareFileFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt

Polish some code: Making `when` exhaustive and some more
_____

[Cleanup] Polish some code

---

CHANGELOG.md
changelog/unreleased/3589
owncloudApp/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/FileListListAdapter.java
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/ReceiveExternalFilesAdapter.java
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java

Crash due to throw exception was fixed

---

CHANGELOG.md
changelog/unreleased/3480
owncloudApp/build.gradle
owncloudApp/src/androidTest/java/com/owncloud/android/authentication/LoginActivityTest.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/CommonModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
owncloudApp/src/main/java/com/owncloud/android/providers/MdmProvider.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt
owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/main/res/values/strings__not_to_translate.xml
owncloudApp/src/main/res/xml/managed_configurations.xml
owncloudData/src/main/java/com/owncloud/android/data/preferences/datasources/SharedPreferencesProvider.kt
owncloudData/src/main/java/com/owncloud/android/data/preferences/datasources/implementation/SharedPreferencesProviderImpl.kt

App: https://github.com/owncloud/android/issues/3553
_____
Check list: https://github.com/owncloud/android/pull/3563#issuecomment-1072224933
1st test matrix: https://github.com/owncloud/android/pull/3563#issuecomment-1069350769
2nd test matrix: https://github.com/owncloud/android/pull/3563#issuecomment-1081716764
Reports:

[MDM] Making code more scalable

---

CHANGELOG.md
owncloudApp/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java

NPE in RefreshFolderOperation - Fixed

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/RemoteDataSourceModule.kt
owncloudApp/src/main/java/com/owncloud/android/workers/UploadFileFromContentUriWorker.kt
owncloudApp/src/main/res/values/setup.xml
owncloudData/src/main/java/com/owncloud/android/data/ClientManager.kt
owncloudData/src/main/java/com/owncloud/android/data/authentication/datasources/implementation/OCRemoteAuthenticationDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/oauth/datasource/impl/RemoteOAuthDataSourceImpl.kt
owncloudData/src/main/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSource.kt
owncloudData/src/test/java/com/owncloud/android/data/oauth/datasource/RemoteOAuthDataSourceTest.kt
owncloudData/src/test/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSourceTest.kt

This is connection Validator.
Library: https://github.com/owncloud/android-library/pull/450
Test Plan (regression): https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.21/ConnectionValidator.md

Connection validator

---

CHANGELOG.md
changelog/unreleased/3592
owncloudApp/src/main/java/com/owncloud/android/MainApp.kt

[Bugfix] Lock displays shown again

---

build.gradle
owncloudApp/build.gradle
owncloudApp/src/main/res/values-fr-rFR/strings.xml
owncloudApp/src/main/res/values-fr/strings.xml

Bump gradle and kotlin versions to the latest ones. And update library reference
Library PR (if needed): https://github.com/owncloud/android-library/pull/478
_____

Bump kotlin and gradle to the latest versions

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsMoreFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsSecurityFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/utils/LargePreferenceCategory.kt

Bump preferences to 1.2.0 and fix related issues
_____

Bump preference-ktx from 1.1.1 to 1.2.0

---

CHANGELOG.md
changelog/unreleased/3616
owncloudApp/src/androidTest/java/com/owncloud/android/settings/SettingsFragmentTest.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/drawable/ic_settings_whats_new.xml
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/main/res/xml/settings.xml

[FEATURE] Add a new option to Settings to show What's new?

---

CHANGELOG.md
changelog/unreleased/3624
owncloudApp/src/androidTest/java/com/owncloud/android/settings/advanced/SettingsAdvancedFragmentTest.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/SettingsActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsAdvancedFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsAdvancedViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/ui/adapter/FileListListAdapter.java
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/main/res/xml/settings.xml
owncloudApp/src/main/res/xml/settings_advanced.xml
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsAdvancedViewModelTest.kt

App: #2578 
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.21/3624-Hidden_files.md

[FEATURE] Support for hidden files

---

owncloudApp/build.gradle
owncloudApp/src/androidTest/java/com/owncloud/android/settings/SettingsFragmentTest.kt
owncloudApp/src/main/res/layout/release_notes_item.xml

[FIX] justified text library removed

---

CHANGELOG.md
changelog/unreleased/3615
owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
owncloudApp/src/main/res/values/setup.xml

[FEATURE] Prevent taking screenshots

---

CHANGELOG.md
changelog/unreleased/3636
owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java

Share text when using public share includes username instead of the full name

---

CHANGELOG.md
changelog/unreleased/3640
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsPictureUploadsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsVideoUploadsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
owncloudApp/src/main/res/layout/files_folder_picker.xml
owncloudApp/src/main/res/values/strings.xml

App: #1414
_____
Old Version / Select upload path  | New Copy Version | New Move Version
------------- | -------------  | -------------

Improved copy/move dialog

---

CHANGELOG.md
changelog/unreleased/3643
owncloudApp/src/main/java/com/owncloud/android/presentation/providers/sharing/UsersAndGroupsSearchProvider.kt

Removed signed in user from the list of users for sharing

---

CHANGELOG.md
changelog/unreleased/3644
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
owncloudApp/src/main/res/layout/preview_image_fragment.xml
owncloudApp/src/main/res/values/strings.xml

Corrupt picture error controlled

---

CHANGELOG.md
changelog/unreleased/3639
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
owncloudApp/src/main/res/layout/preview_image_fragment.xml
owncloudDomain/src/main/java/com/owncloud/android/domain/files/MimeTypeConstants.kt

Previewing SVG files works

---

CHANGELOG.md
changelog/unreleased/3638
owncloudApp/src/main/java/com/owncloud/android/files/FileMenuFilter.java
owncloudApp/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java

App: #3491 
_____
Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.21/3638-Multiple_send.md

[FEATURE] Enable "Send" functionality for file multiselect

---

owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PatternActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/passcode/PassCodeActivity.kt

[BUGFIX] Pattern/Passcode is asked when browsing back

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

App: #3597 
Library PR (if needed): owncloud/android-library/pull/488
_____
Fdroid PR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11040
_____

[Release] 2.21 beta 1

---

owncloudApp/src/main/java/com/owncloud/android/files/FileMenuFilter.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java

App: #3507
_____
QA checks: https://github.com/owncloud/android/pull/3649#issuecomment-1128507582

[FEATURE] "Open with" downloading files

---

owncloudApp/src/main/res/layout/file_details_fragment.xml

bugfix long file name

---

CHANGELOG.md
changelog/unreleased/3657
owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java

Glitch fixed

---

owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt

App: Fix https://github.com/owncloud/android/issues/3677
_____

[Fix] Crash when loading files

---

owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt

Workaround to support pdf privacy policy

---

owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

Clean release notes after 2.21_oem to avoid useless translations

---

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/operations/FileOperationsViewModel.kt

Fixes (2) https://github.com/owncloud/android/issues/2818#issuecomment-834301102
_____

[New Arch] Allow local removal when device is not connected

---

owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/migration/MigrationViewModel.kt
owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt
owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/UpdateAlreadyDownloadedFilesPathUseCase.kt

App: https://github.com/owncloud/android/issues/3741
_____

[FIX] Upgrade from version before Scoped Storage to new arch causes a crash

---

build.gradle

Docs: https://developer.android.com/about/versions/12/behavior-changes-12
App: closes #3485 
_____

Bump target sdk to 31

---

owncloudApp/src/main/java/com/owncloud/android/extensions/ThrowableExt.kt
owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/exceptions/CopyIntoSameFolderException.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/exceptions/MoveIntoSameFolderException.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/CopyFileUseCase.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/MoveFileUseCase.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/CopyFileUseCaseTest.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/MoveFileUseCaseTest.kt

Moving/Copying files into the same folder will fail. An error message will be shown in that case.
App: https://github.com/owncloud/android/issues/3708
_____

[New Arch] Copy/Move into the same folder

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/details/FileDetailsViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

Bump version number and code and add release notes
App: https://github.com/owncloud/android/issues/3743
_____

[Release] 3.0 beta.1

---

owncloudApp/src/main/java/com/owncloud/android/extensions/ThrowableExt.kt
owncloudApp/src/main/java/com/owncloud/android/extensions/WorkManagerExt.kt
owncloudApp/src/main/java/com/owncloud/android/files/FileMenuFilter.java
owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/res/layout/grid_item.xml
owncloudApp/src/main/res/layout/item_file_list.xml

App: https://github.com/owncloud/android/issues/3771
Includes fixes for the reports:
- (1) Remove action blocks the UI https://github.com/owncloud/android/issues/3771#issuecomment-1266978389 [FIXED]
- (18) Share icon missing https://github.com/owncloud/android/issues/3771#issuecomment-1267214898 [FIXED]
- (20) Incorrect message in notification https://github.com/owncloud/android/issues/3771#issuecomment-1278698710 [FIXED]
- (17) ANR when selecting many files https://github.com/owncloud/android/issues/3771#issuecomment-1267192824 [FIXED]
_____

[FIX] Miscellaneous UI fixes for 3.0-Beta.2

---

owncloudApp/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
owncloudApp/src/main/res/values/strings.xml
owncloudData/src/main/java/com/owncloud/android/data/RemoteOperationHandler.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/exceptions/TooEarlyException.kt

App: https://github.com/owncloud/android/issues/3781
Library PR (if needed): https://github.com/owncloud/android-library/pull/517
_____

Handle 425 when trying to open in web

---

owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortType.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/removefile/RemoveFilesDialogFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
owncloudData/src/main/java/com/owncloud/android/data/storage/LocalStorageProvider.kt

App: https://github.com/owncloud/android/issues/3771
Includes fixes for the reports:
- (2) Bad local remove behaviour https://github.com/owncloud/android/issues/3771#issuecomment-1266980128 [FIXED]
- (9) Download bar progress missing in image preview https://github.com/owncloud/android/issues/3771#issuecomment-1267147451 [FIXED]
- (22) Wrong gallery mode sorting method https://github.com/owncloud/android/issues/3771#issuecomment-1293163934 [FIXED]
- (23) Logs disappearing https://github.com/owncloud/android/issues/3771#issuecomment-1293179269 [FIXED]
_____

[FIX] QA reports for 3.0-Beta.2

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/BaseActivity.java

App: #3108 
Capabilities are only retrieved from the new database. 
The last place using usecases without ViewModel is the FileMenuFilter which needs a deep refactor.
_____

Cleanup capabilities

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java

Just a small bugfix to clean up the file paths.
_____

clean up paths before uploading

---

owncloudApp/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
owncloudApp/src/main/res/values/strings.xml
owncloudData/src/main/java/com/owncloud/android/data/RemoteOperationHandler.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/exceptions/TooEarlyException.kt

Library issue: https://github.com/owncloud/android-library/issues/513
Library PR (if needed): https://github.com/owncloud/android-library/pull/515
_____

Handle 425 TOO EARLY propfind responses

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/3724
Includes fixes for the reports:
- (1) Refresh new content in previews https://github.com/owncloud/android/issues/3724#issuecomment-1302054391 [FIXED]
_____

[FIX] Some fixes for 3.0

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/operations/FileOperation.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/operations/FileOperationsViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt

Fixes some reports from https://github.com/owncloud/android/issues/3724
- (3) https://github.com/owncloud/android/issues/3724#issuecomment-1302060258 [FIXED - only file/folder sync]
- (36) https://github.com/owncloud/android/issues/3724#issuecomment-1317084182 [FIXED]
_____

[New arch] 3.0 auth fixes

---

.github/ISSUE_TEMPLATE/release_template.md
owncloudApp/build.gradle

The order of the steps in the release issue template has been changed to keep a more logical way.

[CHANGE] Order of steps in release issue template

---

CHANGELOG.md
changelog/3.0.0_2022-12-12/2934
changelog/3.0.0_2022-12-12/3632
changelog/3.0.0_2022-12-12/3710
changelog/3.0.0_2022-12-12/3719
changelog/3.0.0_2022-12-12/3728
changelog/3.0.0_2022-12-12/3766
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/3724
_____

[Release] 3.0

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/extensions/FileListOptionExt.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
owncloudApp/src/main/res/drawable/ic_spaces.xml
owncloudApp/src/main/res/layout/spaces_list_fragment.xml
owncloudApp/src/main/res/menu/bottom_navbar_menu.xml
owncloudApp/src/main/res/values/strings.xml
owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/40.json
owncloudData/src/androidTest/java/com/owncloud/android/data/roommigrations/MigrationToDB28Test.kt
owncloudData/src/androidTest/java/com/owncloud/android/data/roommigrations/MigrationToDB30Test.kt
owncloudData/src/androidTest/java/com/owncloud/android/data/roommigrations/MigrationToDB36Test.kt
owncloudData/src/main/java/com/owncloud/android/data/OwncloudDatabase.kt
owncloudData/src/main/java/com/owncloud/android/data/ProviderMeta.java
owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/implementation/OCLocalCapabilitiesDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/mapper/RemoteCapabilityMapper.kt
owncloudData/src/main/java/com/owncloud/android/data/capabilities/db/OCCapabilityEntity.kt
owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt
owncloudData/src/main/java/com/owncloud/android/data/migrations/AutoMigration39To40.kt
owncloudData/src/test/java/com/owncloud/android/data/capabilities/datasources/OCRemoteCapabilitiesDataSourceTest.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/capabilities/model/OCCapability.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/model/FileListOption.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/capabilities/model/OCCapabilityTest.kt
owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCCapability.kt

App: https://github.com/owncloud/android/issues/3803
Library PR (if needed): https://github.com/owncloud/android-library/pull/526
_____

[SPACES] Save account type and display new tab for spaces

---

owncloudData/src/androidTest/java/com/owncloud/android/data/spaces/db/SpacesDaoTest.kt
owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/implementation/OCLocalSpacesDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/spaces/db/SpacesDao.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/spaces/model/OCSpaceTest.kt
owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCSpace.kt

Some unit and instrumented tests were added to check the correct behaviour of `OCSpace.kt` and `SpacesDao.kt`.

[SPACES] Tests for OCSpace and SpacesDao

---

owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/40.json
owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/implementation/OCLocalSpacesDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/implementation/OCRemoteSpacesDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/spaces/db/SpacesEntity.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/model/OCSpace.kt

Fix some issues when retrieving the shares space
Library PR (if needed): https://github.com/owncloud/android-library/pull/532
_____

[Spaces] Fix shares space parsing

---

owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListFragment.kt

https://github.com/owncloud/android/issues/3805#issuecomment-1378704787

[SPACES] Fix empty view not showed when all spaces are disabled

---

owncloudApp/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
owncloudApp/src/main/res/layout/spaces_list_item.xml
owncloudApp/src/main/res/values-h640dp/dims.xml
owncloudApp/src/main/res/values-h740dp/dims.xml
owncloudApp/src/main/res/values/dims.xml

The thumbnails were a little bit too small for some resolutions. Now, they should escalate a little bit

[SPACES] Increase spaces thumbnails to support different screen sizes

---

CHANGELOG.md
owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt
owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt
owncloudApp/src/main/res/values/setup.xml
owncloudApp/src/main/res/values/strings__not_to_translate.xml
owncloudApp/src/main/res/xml/managed_configurations.xml
owncloudData/src/main/java/com/owncloud/android/data/authentication/AuthenticationConstants.kt

https://github.com/owncloud/enterprise/issues/5551
_____

OpenId Connect scope brandable

---

CHANGELOG.md
changelog/3.0.2_2023-01-26/3869
changelog/3.0.2_2023-01-26/534
changelog/unreleased/3841
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt
owncloudApp/src/main/res/values/setup.xml
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/main/res/values/strings__not_to_translate.xml
owncloudApp/src/main/res/xml/managed_configurations.xml
owncloudData/src/main/java/com/owncloud/android/data/authentication/AuthenticationConstants.kt
owncloudData/src/main/java/com/owncloud/android/data/capabilities/db/OCCapabilityEntity.kt

App: #3870 
Library PR (if needed): https://github.com/owncloud/android-library/pull/534
_____

[Release] 3.0.2

---

owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/DocumentsStorageProvider.kt

App: https://github.com/owncloud/android/issues/3896
_____

[FIX] [SPACES] Disabled spaces in document provider

---

CHANGELOG.md
changelog/unreleased/3899
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt

App: https://github.com/owncloud/android/issues/3866
_____

[FIX] Bad browsing from Sharing view

---

build.gradle
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt

Bump Room dependency to v2.5.0.
It fixes some issues with automigrations

Bump room dependency to v2.5.0

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
owncloudApp/build.gradle
owncloudApp/src/androidTest/java/com/owncloud/android/authentication/LoginActivityTest.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/settings/security/SettingsSecurityViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/providers/MdmProvider.kt
owncloudApp/src/main/java/com/owncloud/android/providers/WorkManagerProvider.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt
owncloudData/build.gradle
owncloudDomain/build.gradle
owncloudTestUtil/build.gradle

Bump kotlin version to 1.8.10 
Release details: https://kotlinlang.org/docs/whatsnew18.html#ide-support
`kotlin-stdlib-jdk7` and `kotlin-stdlib-jdk8`  have been merged into `kotlin-stdlib`
Library PR: https://github.com/owncloud/android-library/pull/540
_____

Bump kotlin version to 1.8.10 

---

owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/DocumentsStorageProvider.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/documentsprovider/cursors/SpaceCursor.kt

Implements https://github.com/owncloud/android/issues/3888
_____

[SPACES] Refresh spaces list in documents provider

---

.github/ISSUE_TEMPLATE/release_template.md

Fix release template

---

owncloudApp/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java

[SPACES] Support thumbnails for spaces

---

owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt

Update the release notes for 3.0.4_oem release 
_____

[Release] 3.0.4_oem

---

build.gradle
owncloudApp/build.gradle
owncloudData/build.gradle
owncloudDomain/build.gradle

App: #3900 
Library PR (if needed): https://github.com/owncloud/android-library/pull/548
_____

[Technical] Replace kapt with ksp

---

owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt

App: https://github.com/owncloud/android/issues/3964
_____

Potential fix to index out of bounds crash

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListDiffCallback.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/transfers/TransferListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/transfers/TransfersAdapter.kt
owncloudApp/src/main/res/layout/item_file_list.xml
owncloudApp/src/main/res/layout/space_path_line.xml
owncloudApp/src/main/res/layout/upload_list_item.xml
owncloudData/src/main/java/com/owncloud/android/data/spaces/db/SpacesDao.kt

App: https://github.com/owncloud/android/issues/3947
_____

[SPACES] Available offline

---

build.gradle
changelog/unreleased/3973
owncloudApp/src/main/AndroidManifest.xml
owncloudApp/src/main/java/com/owncloud/android/presentation/settings/SettingsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/res/drawable/ic_notifications.xml
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/main/res/xml/settings.xml

App: #3617 
Library PR: https://github.com/owncloud/android-library/pull/550
_____

[TECHNICAL] Bump target sdk to 33

---

owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListDiffCallback.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/transfers/TransferListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/transfers/TransfersAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/transfers/TransfersViewModel.kt
owncloudData/build.gradle
owncloudData/src/androidTest/java/com/owncloud/android/data/spaces/db/SpacesDaoTest.kt
owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/files/db/OCFileAndFileSync.kt
owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/LocalSpacesDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/implementation/OCLocalSpacesDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/spaces/db/SpacesDao.kt
owncloudData/src/main/java/com/owncloud/android/data/spaces/repository/OCSpacesRepository.kt
owncloudData/src/main/java/com/owncloud/android/data/transfers/datasources/LocalTransferDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/transfers/datasources/implementation/OCLocalTransferDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/transfers/db/TransferDao.kt
owncloudData/src/main/java/com/owncloud/android/data/transfers/repository/OCTransferRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/files/model/OCFileWithSyncInfo.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/SpacesRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/usecases/GetPersonalAndProjectSpacesWithSpecialsForAccountAsStreamUseCase.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/usecases/GetProjectSpacesWithSpecialsForAccountAsStreamUseCase.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/usecases/GetSpacesFromEveryAccountUseCaseAsStream.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/transfers/TransferRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/transfers/usecases/GetAllTransfersAsStreamUseCase.kt

App: https://github.com/owncloud/android/issues/3971
_____

Add space to OCFileWithSyncInfo

---

owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/implementation/OCLocalSpacesDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/spaces/datasources/implementation/OCRemoteSpacesDataSource.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/spaces/model/OCSpace.kt
owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCSpace.kt

Permissions will be handled via WebDav. So no need to maintain this parsing.
Library PR (if needed): https://github.com/owncloud/android-library/pull/552
_____

Remove permission parsing from spaces. 

---

owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListAdapter.kt

App: https://github.com/owncloud/android/issues/3981
_____

[FIX] Bad refresh of thumbnails in spaces list

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/3996
_____

[Release] 4.0 beta.2

---

owncloudApp/src/main/res/mipmap-anydpi-v26/icon.xml

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming
Here's the icon next to other apps by Google:
App:
_____

Add monochrome icon

---

changelog/unreleased/4001
changelog/unreleased/4014
changelog/unreleased/4017

There were some contributions that didn't include calens file to complete the changelog, so we add them in this PR

Add some omitted calens files

---

CHANGELOG.md
owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/4007
_____

[RELEASE] 4.0-beta.3

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java

App: #3796 
Refracted findViewById to use ViewBinding in [this Activity](https://github.com/owncloud/android/blob/000a0d97ac8b8f72f29f80818d64e17d0929e2fd/owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java)
@abelgardep please review my PR and let me know what I can improve

updated the findViewById to use view binding

---

changelog/unreleased/4021
owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java

I applied some last polishments and added the calens file for the changelog to be updated, everything related with the contribution https://github.com/owncloud/android/pull/4021

Polishments for ViewBinding in WhatsNewActivity contribution

---

CHANGELOG.md
changelog/unreleased/4032
owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/SettingsMoreFragmentTest.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/settings/more/SettingsMoreFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/settings/more/SettingsMoreViewModel.kt
owncloudApp/src/main/res/values/setup.xml
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/main/res/xml/settings_more.xml
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsMoreViewModelTest.kt

App: https://github.com/owncloud/android/issues/4028
_____

[FEATURE REQUEST] Add suggested app to access document provider

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/4033
_____

[RELEASE] 4.0-beta.4

---

CHANGELOG.md
changelog/unreleased/4089
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt

App: https://github.com/owncloud/android/issues/4027
_____

[FEATURE REQUEST] Improve grid mode

---

owncloudApp/src/main/java/com/owncloud/android/presentation/previews/PreviewTextViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewFormatTextFragmentStateAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
owncloudApp/src/main/res/layout/preview_format_text_fragment.xml
owncloudApp/src/main/res/layout/preview_text_fragment.xml
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/main/res/values/strings__not_to_translate.xml

App: #4025 
_____
https://github.com/owncloud/android/assets/111801812/85dea132-f6fd-41ed-bfc3-5c38eb0e2a49

add tablayout for markdown file

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/4100
_____

[RELEASE ] 4.1.0-beta.1

---

CHANGELOG.md
changelog/unreleased/4122
owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/AccountsManagementActivity.kt

[BUG] List of accounts empty after removing all accounts and adding new ones

---

.github/ISSUE_TEMPLATE/release_template.md

Related:
- https://github.com/owncloud/enterprise/issues/5901

Update Android SBOM as part of the release process

---

CHANGELOG.md
changelog/unreleased/4127
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt

[BUG] Bad error message when copying/moving with server down

---

CHANGELOG.md
changelog/unreleased/4129
owncloudApp/src/main/java/com/owncloud/android/utils/RemoteFileUtils.kt

App: https://github.com/owncloud/android/issues/4079
_____

[FEATURE REQUEST] Apply (1) to uploads' name conflicts

---

owncloudData/build.gradle
owncloudData/src/test/java/com/owncloud/android/data/appRegistry/datasources/implementation/OCLocalAppRegistryDataSourceTest.kt
owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
owncloudData/src/test/java/com/owncloud/android/data/file/repository/OCFileRepositoryTest.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/GetFileWithSyncInfoByIdUseCaseTest.kt

Replace `runBlocking `clauses with `runTest` for testing purposes.
More info: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-test.html

Replace runBlocking with runTest for testing

---

CHANGELOG.md
changelog/unreleased/3966
changelog/unreleased/4179
changelog/unreleased/4183

Just adds the Calens report for the following PRs:
https://github.com/owncloud/android/pull/4183
https://github.com/owncloud/android/pull/4179
https://github.com/owncloud/android/pull/3966

Add missing calens reports

---

CHANGELOG.md
changelog/unreleased/4205
owncloudApp/src/main/java/com/owncloud/android/presentation/logging/LogsListActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/logging/RecyclerViewLogsAdapter.kt
owncloudApp/src/main/res/drawable/ic_baseline_download_grey.xml
owncloudApp/src/main/res/layout/log_list_item.xml
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/4155
_____
https://github.com/owncloud/android/pull/4205#issuecomment-1792110218

[FEATURE REQUEST] Streamlined Log File Upload Functionality

---

owncloudApp/src/main/res/layout/main_file_list_fragment.xml
owncloudApp/src/main/res/values/strings.xml

[FEATURE REQUEST] Improvements in "New content" refresh button

---

owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/43.json

Add `43.json`, which was not added previously accidentally

Add JSON file for database version 43

---

CHANGELOG.md
changelog/unreleased/4237
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt

App: https://github.com/owncloud/android/issues/4145
_____

[FEATURE REQUEST] Thumbnail improvements in grid view

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

[RELEASE ] 4.2.0-beta.1

---

owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values-de-rDE/strings.xml
owncloudApp/src/main/res/values-de/strings.xml
owncloudApp/src/main/res/values-en-rGB/strings.xml
owncloudApp/src/main/res/values-et-rEE/strings.xml
owncloudApp/src/main/res/values-sq/strings.xml
owncloudApp/src/main/res/values/strings.xml

- Fix some strings
- Add missing entry: auto uploads to spaces
- Remove old entries from release notes.
App:
_____

Add some fixes to release notes 4.2.0

---

CHANGELOG.md
changelog/unreleased/4238
owncloudApp/src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java

App: https://github.com/owncloud/android/issues/4207
_____

[BUG] Some NPEs from Google Play Console

---

owncloudApp/src/main/java/com/owncloud/android/presentation/logging/LogsListActivity.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/OCFileLoggingTree.kt

App:https://github.com/owncloud/android/issues/4236
_____

[BUG] Two logs are displayed when you open the app

---

owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt
owncloudApp/src/main/res/layout/grid_item.xml
owncloudApp/src/main/res/values/dims.xml

App: https://github.com/owncloud/android/issues/4248
_____

[BUG] Thumbnails glitches if there are many files in the folder

---

owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt

Fix: #4231
https://github.com/owncloud/android/assets/111801812/6fb3ed46-de0e-4b1f-a628-0a25dff91137

[FEATURE REQUEST] Block UI when deleting files

---

CHANGELOG.md
changelog/unreleased/4283
owncloudApp/src/main/java/com/owncloud/android/presentation/security/biometric/BiometricActivity.kt

App: https://github.com/owncloud/android/issues/4180
_____

[TECHNICAL] Improve biometrical authentication security

---

CHANGELOG.md
changelog/unreleased/4205
owncloudApp/src/main/java/com/owncloud/android/presentation/logging/LogsListActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/logging/RecyclerViewLogsAdapter.kt

App: https://github.com/owncloud/android/issues/4217
_____

[BUG] Some bugs in log files downloads

---

CHANGELOG.md
changelog/unreleased/4295
owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/CopyFileUseCase.kt

App: https://github.com/owncloud/android/issues/4293
_____

[BUG] Invalid copy into descendant in different spaces

---

owncloudApp/src/main/java/com/owncloud/android/presentation/security/biometric/BiometricViewModel.kt

Just a comment to clarify the use of the `Cipher` object
_____

Added comment explaining the purposes of Cipher object in biometrics

---

CHANGELOG.md
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/OCFileLoggingTree.kt

[FIX] Hardcoded name in logs leads to crash

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/release_template.md
.github/pull_request_template.md

Changes in the templates:
- In pull request template: 
- Add release notes in advance to give time to be translated. Removed from issue template.
- In release template:
- Move the signing tag to the end of the checklist, to assure there are no commits between the approved and the merge
- Clarify that release branches will not be rebased anymore (direct merge instead)
- New patch release section, with tasks for minor bugfixes 
Please @JuancaG05 and @Aitorbp review this and throw as many questions as needed to understand correctly the complete processes and why changes are suggested. Specially, the tasks in patch releases.

More changes in templates

---

CONTRIBUTING.md

App:
No Calens and release notes required for this one.
_____

Add conventional commits to CONTRIBUTING.md file in order to be understood by community

---

CHANGELOG.md
changelog/unreleased/4388
owncloudApp/src/main/res/layout/preview_image_activity.xml
owncloudApp/src/main/res/values/strings.xml

App:https://github.com/owncloud/android/issues/4361
_____

[a11y] 11.1.1.1b Non-text content (graphics and objects)

---

CHANGELOG.md
changelog/unreleased/4385
owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
owncloudApp/src/main/java/com/owncloud/android/workers/AccountDiscoveryWorker.kt

App: https://github.com/owncloud/android/issues/4213
_____

[BUG] Request review in fresh install

---

CHANGELOG.md
changelog/unreleased/4394
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PrepareVideoPlayerAsyncTask.java
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/4328
_____

[BUG] Can't stream video from space

---

CHANGELOG.md
changelog/unreleased/4387
owncloudApp/src/main/java/com/owncloud/android/presentation/avatar/AvatarUtils.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/sharing/ShareActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.kt
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
owncloudApp/src/main/res/layout-land/nav_drawer_footer.xml
owncloudApp/src/main/res/layout/account_item.xml
owncloudApp/src/main/res/layout/nav_drawer_footer.xml
owncloudApp/src/main/res/layout/owncloud_toolbar.xml
owncloudApp/src/main/res/layout/share_file_layout.xml
owncloudApp/src/main/res/layout/share_public_link_item.xml
owncloudApp/src/main/res/layout/share_user_item.xml
owncloudApp/src/main/res/layout/sort_options_layout.xml
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/4360
_____

[a11y] 11.1.1.1a Non-text content (control elements)

---

owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListAdapter.kt

[FIX] Duplicate image for personal space

---

CHANGELOG.md
changelog/unreleased/4391
owncloudApp/src/main/java/com/owncloud/android/presentation/common/BottomSheetFragmentItemView.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

App:https://github.com/owncloud/android/issues/4105
_____

[FEATURE REQUEST] Show app provider icon from endpoint 

---

owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListFragment.kt

App: https://github.com/owncloud/android/issues/4405
_____

[FIX] Disabled spaces are listed

---

.github/ISSUE_TEMPLATE/release_template.md

Send a ping when release is done, in order to keep https://owncloud.com/mobile-apps/ updated 
No calens or release notes required here

Add new step to release template

---

.github/ISSUE_TEMPLATE/release_template.md

References: #4419 (Add new step to release template)
Just a small typo fix for my name 😅

Update release_template.md (name fix)

---

CHANGELOG.md
changelog/unreleased/4423
owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/SettingsMoreFragmentTest.kt
owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/common/DrawerViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/settings/more/SettingsMoreFragment.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/settings/more/SettingsMoreViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
owncloudApp/src/main/res/values/setup.xml
owncloudApp/src/main/res/values/strings.xml
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/DrawerViewModelTest.kt

[FEATURE REQUEST] Encourage users to report on GitHub instead of android-app@owncloud.com and ios-app@owncloud.com

---

.github/ISSUE_TEMPLATE/bug_report.md

Change test instance URL to an operative one in templates

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

[RELEASE] 4.4.0-beta.1

---

owncloudApp/src/main/java/com/owncloud/android/presentation/files/SortOptionsView.kt
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/4473
_____

[a11y] "New folder" option in folder picker with incorrect dictation 

---

owncloudApp/src/main/java/com/owncloud/android/presentation/sharing/ShareFileFragment.kt

[a11y] Wrong name in toolbar Share View

---

CHANGELOG.md
changelog/unreleased/4479
owncloudApp/src/main/AndroidManifest.xml
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/4474
_____

[FIX] Audio player does not work

---

.github/ISSUE_TEMPLATE/release_template.md

Just added an extra step to the Open release template

[DOCUMENTATION] Added extra step to open release template

---

owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values-de/strings.xml
owncloudApp/src/main/res/values-en-rGB/strings.xml
owncloudApp/src/main/res/values-es/strings.xml
owncloudApp/src/main/res/values-et-rEE/strings.xml
owncloudApp/src/main/res/values-fi-rFI/strings.xml
owncloudApp/src/main/res/values-ja-rJP/strings.xml
owncloudApp/src/main/res/values-ko/strings.xml
owncloudApp/src/main/res/values-pt-rBR/strings.xml
owncloudApp/src/main/res/values-ru-rRU/strings.xml
owncloudApp/src/main/res/values-ru/strings.xml
owncloudApp/src/main/res/values-sq/strings.xml
owncloudApp/src/main/res/values/strings.xml

Remove 4.4.0 release notes

---

CHANGELOG.md
changelog/unreleased/4516
owncloudApp/src/main/AndroidManifest.xml
owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AccountAuthenticator.java
owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AuthenticationViewModel.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt
owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/oauth/OAuthUtils.kt
owncloudApp/src/main/res/values/setup.xml
owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/authentication/AuthenticationViewModelTest.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/params/TokenRequestParams.kt
owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/responses/OIDCDiscoveryResponse.kt
owncloudData/src/main/java/com/owncloud/android/data/oauth/datasources/implementation/OCRemoteOAuthDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/server/datasources/RemoteServerInfoDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSource.kt
owncloudData/src/main/java/com/owncloud/android/data/server/repository/OCServerInfoRepository.kt
owncloudData/src/test/java/com/owncloud/android/data/oauth/RemoteOAuthUtils.kt
owncloudData/src/test/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSourceTest.kt
owncloudData/src/test/java/com/owncloud/android/data/server/repository/OCServerInfoRepositoryTest.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/authentication/oauth/model/OIDCServerConfiguration.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/authentication/oauth/model/TokenRequest.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/server/ServerInfoRepository.kt
owncloudDomain/src/main/java/com/owncloud/android/domain/server/usecases/GetServerInfoAsyncUseCase.kt
owncloudDomain/src/test/java/com/owncloud/android/domain/server/usecases/GetServerInfoAsyncUseCaseTest.kt

App: https://github.com/owncloud/android/issues/4500
_____

[FEATURE REQUEST] Enforce OIDC auth flow

---

CHANGELOG.md
changelog/unreleased/4535
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt

App: https://github.com/owncloud/android/issues/4340
_____

[FIX] Up button in navigation in folder picker for auto-uploads not appearing

---

owncloudApp/build.gradle
owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt

App: https://github.com/owncloud/android/issues/4530
_____
https://github.com/owncloud/android/pull/4547#issuecomment-2651194620

[RELEASE] 4.5.0-beta.1

---

CHANGELOG.md
changelog/unreleased/4549
owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/SettingsMoreFragmentTest.kt
owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
owncloudApp/src/main/res/values-de-rDE/strings.xml
owncloudApp/src/main/res/values-de/strings.xml
owncloudApp/src/main/res/values-en-rGB/strings.xml
owncloudApp/src/main/res/values-es/strings.xml
owncloudApp/src/main/res/values-et-rEE/strings.xml
owncloudApp/src/main/res/values-fi-rFI/strings.xml
owncloudApp/src/main/res/values-ja-rJP/strings.xml
owncloudApp/src/main/res/values-ko/strings.xml
owncloudApp/src/main/res/values-pt-rBR/strings.xml
owncloudApp/src/main/res/values-ru/strings.xml
owncloudApp/src/main/res/values-sq/strings.xml
owncloudApp/src/main/res/values-ug/strings.xml
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/4540
_____

 [FEATURE REQUEST] Remove survey and chat from feedback

---

owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values-de-rDE/strings.xml
owncloudApp/src/main/res/values-de/strings.xml
owncloudApp/src/main/res/values-en-rGB/strings.xml
owncloudApp/src/main/res/values-es/strings.xml
owncloudApp/src/main/res/values-et-rEE/strings.xml
owncloudApp/src/main/res/values-fi-rFI/strings.xml
owncloudApp/src/main/res/values-ja-rJP/strings.xml
owncloudApp/src/main/res/values-pt-rBR/strings.xml
owncloudApp/src/main/res/values-ru/strings.xml
owncloudApp/src/main/res/values-sq/strings.xml
owncloudApp/src/main/res/values/strings.xml

[TECHNICAL] Remove 4.5.1 release notes

---

CHANGELOG.md
changelog/unreleased/4578
owncloudApp/src/main/res/values-et-rEE/strings.xml
owncloudApp/src/main/res/values-pt-rBR/strings.xml
owncloudApp/src/main/res/values-sq/strings.xml
owncloudApp/src/main/res/values/strings.xml

App: https://github.com/owncloud/android/issues/4572
_____

[TECHNICAL] Change biometrics fail source string

---

CHANGELOG.md
changelog/unreleased/4580
owncloudApp/src/main/res/menu/drawer_menu.xml

App: https://github.com/owncloud/android/issues/4513
_____

[FIX] Side menu collapses info in landscape

---

CHANGELOG.md
changelog/unreleased/4594
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt

App: https://github.com/owncloud/android/issues/4577
_____

[FIX] Crash in PreviewImageFragment (Play Console)

---

CHANGELOG.md
changelog/unreleased/4600
owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt

App: https://github.com/owncloud/android/issues/4596
_____

[FIX] Crash in PreviewImagePagerAdapter (Play Console)

---

.github/workflows/sbom.yml

fix: add step to check ssh permissions

---

.github/workflows/sbom.yml

fix SBOM comparations

---

.github/workflows/sbom.yml

fix: improve comparison with current sbom and add condition

---

.github/workflows/sbom.yml

[FIX] Change predefined step that used https for another with commands

---

owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values-de/strings.xml
owncloudApp/src/main/res/values-es/strings.xml
owncloudApp/src/main/res/values-et-rEE/strings.xml
owncloudApp/src/main/res/values-pt-rBR/strings.xml
owncloudApp/src/main/res/values-sq/strings.xml
owncloudApp/src/main/res/values-tr/strings.xml
owncloudApp/src/main/res/values/strings.xml

[TECHNICAL] Remove 4.6.0 release notes

---

CHANGELOG.md
changelog/unreleased/4652
owncloudApp/src/main/java/com/owncloud/android/presentation/transfers/TransferListFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java

App: https://github.com/owncloud/android/issues/4650
_____

[FIX] Crash in TransferListFragment (Play Console)

---

CHANGELOG.md
changelog/unreleased/4654
owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt
owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileActivity.java

App: https://github.com/owncloud/enterprise/issues/7277
_____

[FIX] Re-login not working properly when credentials expire

---

owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
owncloudApp/src/main/res/values-de/strings.xml
owncloudApp/src/main/res/values-es/strings.xml
owncloudApp/src/main/res/values-et-rEE/strings.xml
owncloudApp/src/main/res/values-pt-rBR/strings.xml
owncloudApp/src/main/res/values-sq/strings.xml
owncloudApp/src/main/res/values-tr/strings.xml
owncloudApp/src/main/res/values/strings.xml

[TECHNICAL] Remove 4.6 release notes
